### ISSUE TITLE
Recaptcha v2 issues

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1856] opened 2018-01-15 18:27 UTC
Just upgraded an early V6 store to the latest V6, changed the store theme to the latest foundation theme. the store is configured to use Recaptcha v2.

unfortunately, it doesn't look like V2 works anymore with foundation without some changes. It's configured correctly in the store admin area.

![image](https://user-images.githubusercontent.com/10614018/34956583-b2b31912-fa21-11e7-8688-cd228ec5101a.png)

**Comment by abrookbanks** [comment] 2018-01-16 15:06
I would ned to look at this as a tech support issue. This is not a bug with latest build. 

I haven't come across this issue with any upgrades to date. I'm going to close this but possibly come back to it another time.

**Closed as completed by abrookbanks** 2018-01-16 15:06 UTC
Labels: invalid
