### ISSUE TITLE
Text Editor is broken on some pages

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1076] opened 2016-04-11 07:10 UTC
Since the upgrade of the text editor version there have been a few oddities in some places.

For example, on the Store Settings -> Offline tab the buttons are not visible within the editor.

I've also seen the same behaviour on some of my plugins that include the text editor.

See attached.

![fck](https://cloud.githubusercontent.com/assets/10614018/14419308/e67aca44-ffbc-11e5-9e9c-0d0d26a84b99.PNG)

**Comment by bhsmither** [comment] 2016-04-13 22:06
See #1058 
https://forums.cubecart.com/topic/51085-resolved-after-upgrade-to-6011-ckeditor-toolbar-issue-on-copyright-offline-tab/

**Comment by abrookbanks** [comment] 2016-04-18 11:12
Duplicate of #1058

**Closed by abrookbanks** 2016-04-18 11:12 UTC
Labels: duplicate
