### ISSUE TITLE
Bug - Documents

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#345] opened 2015-03-10 03:02 UTC
In beta 7 if you click on 'Documents' in the Admin under File Manager it simply reloads the current page?

**Comment by abrookbanks** [comment] 2015-03-10 07:44
Duplicate of #335

Fix here: https://github.com/cubecart/v6/commit/79fefc07756f2c2f9d89a827b25361e78381789f

**Closed by abrookbanks** 2015-03-10 07:44 UTC
Labels: duplicate
