### ISSUE TITLE
No gift certificate email sent if it is the only item

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#1291] opened 2016-10-19 13:47 UTC

**Comment by bhsmither** [comment] 2016-10-21 01:29
Maybe a duplicate of #764?

**Comment by abrookbanks** [comment] 2016-10-21 06:35
Yeah looks like it. 👍🏻

**Closed** 2016-10-21 13:55 UTC

**Comment by bhsmither** [comment] 2016-11-27 22:59
Some of this made it into the CC611 milestone, but fix 9fcb202 didn't.

May we have the state of this fix?

**Comment by abrookbanks** [comment] 2016-11-28 10:09
This isn't needed because it checks against the database now instead if it's been sent or not.

See:
https://github.com/cubecart/v6/blob/master/classes/order.class.php#L1272-L1282
https://github.com/cubecart/v6/blob/master/setup/db/install/structure.sql#L198
https://github.com/cubecart/v6/blob/master/setup/db/upgrade/6.1.0.sql#L32
