### ISSUE TITLE
Home icon links to different URL than Breadcrumb Home link

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#74] opened 2015-01-15 19:01 UTC
I've made an effort to install all the code changes for currently closed issues for 6.2.03b, but it's certainly possible this is a coding error on my part!!

Icon - http://dirtybutter.com/plushcatalog/v6b2/index.php
HOME breadcrumb - http://dirtybutter.com/plushcatalog/v6b2
Logo link - http://dirtybutter.com/plushcatalog/v6b2

**Comment by abrookbanks** [comment] 2015-01-16 09:51
Duplicate of #69. Thanks for sharing though Rosemary great work and much appreciated!! :)

**Closed by abrookbanks** 2015-01-16 09:51 UTC
Labels: duplicate
