### ISSUE TITLE
Product attributes not showing in plain text after upgrade from 6.29 to 6.41

### ISSUE THREAD

**Issue by spacekids** [cubecart/v6#2703] opened 2020-11-30 21:24 UTC
Hope someone can give me some pointers, just recently upgraded from Version 6.29 to 6.41.

Since the upgrade, every time I get an order, when I view the order in Admin Control Panel or print it, any product with a size attribute, the size comes up as a set of numbers and letters like this example:

1 x ISS Astronaut White Space suit by Galactic Gear - SK049-3 (£37.99) £37.99
YToxOntpOjE4ODtzOjEyOiJTaXplczogU21hbGwiO30= 

But when I receive the email notification about the order, I see the size attribute correctly:

ISS Astronaut White Space suit by Galactic Gear
Sizes: Small

Makes the processing of orders a real pain as I need to keep going between Admin control panel and the emails.  

Hope someone can offer a suggestion

**Comment by bhsmither** [comment] 2020-11-30 21:37
Possibly a duplicate of #2698.

**Comment by abrookbanks** [comment] 2020-12-01 08:43
I can't reproduce this. 
http://static.cubecart.com/issue-2703.mp4 

I expect the admin files are not at the latest version.

**Closed as completed by abrookbanks** 2020-12-01 08:43 UTC
Labels: invalid

**Comment by abrookbanks** [comment] 2020-12-01 10:52
Code improved via https://github.com/cubecart/v6/commit/269183fbec82c6f04e68634b6969362a93d579ef
