### ISSUE TITLE
"sort by" isn't working

### ISSUE THREAD

**Issue by opensourceCoding** [cubecart/v6#821] opened 2015-09-19 12:28 UTC
I'm filing this bug report on behalf of @gayledawn who has mentioned the "sort by" on product list isn't working, I can verify this is also not working for me either, I've tried it on the CubeCart demo https://demo.cubecart.com/cc6/sale-items.html when selecting sort by highest price first the page does indeed reload but the products are still not sorted by highest price first, I'm using Windows 7 and have tried this on Firefox and Chrome.

https://forums.cubecart.com/topic/50327-sale-item-product-sorting-not-working/

**Comment by abrookbanks** [comment] 2015-09-29 09:52
This is a lot more complex than one would imagine! Hopefully we have a solution soon.

**Comment by Noodleyman** [comment] 2016-04-01 14:22
Hi Al,

I was wondering how progress for this issue is going. I know this issue is a pain, but it's quite an important one as the sort not working correctly can really annoy customers, which can result in a loss of sales.

For example, viewing a category where you have configured the default sort order to be price low->high, but you get randomly priced produced. 

If the customer changes the sort order, it doesn't always give the expected results.

Any chance this can be addressed in the next update?

**Comment by Noodleyman** [comment] 2016-09-15 11:28
I've implimented my own custom fixes for this for a couple of my customers, but wondered how far away a solution is in a core version of CC?

**Comment by abrookbanks** [comment] 2016-09-15 11:37
Can you share your fix?

**Comment by briansandall** [comment] 2016-12-16 19:30
Not sure if this is related, but the usage of `$_REQUEST`, `$_GET`, and `$_POST` in `cubecart.class.php::_category()` are all over the place, for example:
```
// lines 750 - 758
// first condition keyed off $_POST, no problem
if (isset($_POST['sort'])) {
	list($field, $order) = explode('|', $_POST['sort']);
	$query['sort'][$field] = $order;

	// but now we're checking $_GET? why would both $_GET['search'] and $_POST['search'] be set?
	if (isset($_GET['search'])) {
		foreach ($_GET['search'] as $key => $value) {
			$query['search'][$key] = $value;
		}
	}
}

// lines 760-762, condition based on $_REQUEST followed by $_POST
if (isset($_REQUEST['search'])) {
	// the following line produces an 'Undefined index' PHP warning
	if ($_POST['search']) {
		foreach ($_POST['search'] as $key => $value) {
			// note that changing the for loop to use $_REQUEST causes infinite redirect loop

// Or line 802 (broken up for clarity)
$page = (isset($_REQUEST['page']) &&
		// either this should also use $_REQUEST, or the other two should use $_GET
		!empty($_GET['page'])) 
		? $_REQUEST['page'] : 1;
```
Those are just a few examples from that function.

I'm sure there are (or were) valid reasons for coding it that way, but it is unclear to me what those may be.

**Comment by briansandall** [comment] 2016-12-19 20:52
Line 802 seems to be responsible for #1264

**Comment by briansandall** [comment] 2016-12-19 21:30
Re: `Product List Sorting` under Store Settings => Layout

I'm not yet sure of the cause, but the setting does not seem to be applied consistently and the 'sort by' option that is listed as currently selected when viewing products is not always correct when the page first loads. This is somewhat related to #431.

A few examples from a store using a copy of the master branch:

1. Settings: Sort ASC by price including tax; results in correct sorting, but incorrect 'sort by' option selected in the dropdown:
![cc821a](https://cloud.githubusercontent.com/assets/14335170/21329665/b847fc16-c5ee-11e6-8517-37c6253e7958.jpg)

2. Settings: Sort ASC by Product Name; results in incorrect sorting (sorting appears to be by price in this particular case, but who knows) but has the correct option selected in the 'sort by' dropdown
![cc821b](https://cloud.githubusercontent.com/assets/14335170/21329673/c250a622-c5ee-11e6-89ba-30e14b2e0d1e.jpg)

**Comment by briansandall** [comment] 2016-12-19 22:32
Further testing has shown that as long as the store setting option is one that exists in the customer dropdown, e.g. 'Retail Price' instead of 'Price inclusive of tax', then the drop-down option will be correctly selected.

However, the default sort order is otherwise completely ignored when initially displaying the page.

**Comment by briansandall** [comment] 2016-12-30 18:40
@abrookbanks I believe this issue can be closed now, no?

**Closed** 2017-01-03 11:40 UTC
Labels: bug
