### ISSUE TITLE
Structured Data - Feature Request

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#933] opened 2015-12-19 23:01 UTC
I have noticed you have begun to add structured data for rich snippets at the beginning of content.product.php. At this stage you only have the name but can you add other properties such price, image and ratings?
https://developers.google.com/structured-data/rich-snippets/products?rd=1

**Comment by bondimedical3** [comment] 2016-01-02 04:11
I have created some code for this using the Google Structured Data Markup Helper. Please note that both Name and Price are required for products. The attached screenshot is from the Galaxy X skin but the changes would be similar for Foundation. Line 20 adds the markup for the main image. Lines 35 and 38 add the markup for the price. Other markup can also be added for reviews...
![structured data](https://cloud.githubusercontent.com/assets/10808588/12073180/d259cc48-b162-11e5-8de9-033758cd7f40.png)

**Comment by bondimedical3** [comment] 2016-01-05 01:14
My structured markup appeared in SERPs today but I noticed that all prices where in US dollars and it was saying USD249.95 when I wanted AUD. So before line 38 you need to set the currency as well. 
<meta itemprop="priceCurrency" content="AUD" />
<span itemprop="price" class="sale_price" id="ptp" data-price="{$PRODUCT.price_to_pay}">{$PRODUCT.sale_price}</span>

**Comment by havenswift-hosting** [comment] 2016-08-19 14:33
This functionality is now provided by an extension that works for the Foundation skin and any skin based on this (most V6 skins available) - see https://www.cubecart.com/extensions/product-feeds/7-day-trial-google-schema-org-microdata-plugin for full description of the functionality

**Comment by abrookbanks** [comment] 2016-09-22 06:43
Duplicate of #82

**Comment by havenswift-hosting** [comment] 2017-03-06 13:41
Doesnt this mean that you can close two issues ?

**Closed** 2017-05-04 14:27 UTC
Labels: duplicate, feature request
