### ISSUE TITLE
Feature Suggestion: Search result shows products listing as you type

### ISSUE THREAD

**Issue by tonyrsutton** [cubecart/v6#2790] opened 2021-02-19 19:53 UTC
Feature Suggestion: Search result shows products listing as you type. Also similar to Autocomplete.

Seeing more and more webpages doing this - showing you the products while you type in the product name in the search box. I think it's done by AJAX Live Search but instead of pulling the string from a file, this could be pulling the product details from the  product database to show you the listing of products.

I feel this would generate more sales if people can see what is available to buy as they type in, and gives them wider ranges of products to see.

Thanks.

**Comment by havenswift-hosting** [comment] 2021-02-19 23:34
Great you are getting involved but please check if suggestions have already been made.  This is a duplicate of https://github.com/cubecart/v6/issues/2600 search will be massively improved by using ElasticSearch and / or Sphinx Search

**Comment by tonyrsutton** [comment] 2021-02-19 23:52
Thank you, I did look for it before posting here, but I was not aware of a feature called ElasticSearch.

Cheers

**Comment by tonyrsutton** [comment] 2021-02-19 23:58
I however found this post from Al regarding ElasticSearch. :(

https://forums.cubecart.com/topic/52138-resolved-improved-search-facility-elasticsearch/

**Comment by abrookbanks** [comment] 2021-03-08 09:30
Yes Elastic search is going to be our next big push I hope. I have mountains of work to catch up on.

**Closed as completed by abrookbanks** 2021-03-08 09:30 UTC
Labels: duplicate

**Comment by abrookbanks** [comment] 2021-09-20 14:32
Duplicate of #2790  (sorry I didn't see this)
