### ISSUE TITLE
hreflang isnt working for any languages other than the default language

### ISSUE THREAD

**Issue by Caranxnet** [cubecart/v6#3073] opened 2022-10-28 11:26 UTC
Unfortunately looks like Google isn't indexing the pages I have in the other languages, main one is spanish but I also have translations in english and italian. What also happens is that through search controle some of the meta descriptions in other languages are seen as duplicated, but I think this is part of the same problem. Thanks in advance for your help, I look forward to hearing back from you

regards

Nicola

**Comment by havenswift-hosting** [comment] 2022-10-29 23:35
We have a couple of international clients where this isnt working so if access is needed to be able to work on this, please get in contact - it is a BIG deal for clients that use multi languages.

**Comment by bhsmither** [comment] 2022-10-31 05:23
According to my shallow research, the `hreflang` attribute requires Fully Qualified Domain Names. An FQDN does **not** include any part of the querystring (although the use of querystrings has been used as a workaround that inhibits browsers from caching page resources) -- *according to my research which does not mention this one way or the other*.
```
<link rel="alternate" hreflang="x-default" href="http://cc646.example.com/index.php?set_language=en-US">
<link rel="alternate" href="http://cc646.example.com/index.php?seo_path=&set_language=en-GB" hreflang="en-GB">
<link rel="alternate" href="http://cc646.example.com/index.php?seo_path=&set_language=en-US" hreflang="en-US">
<link rel="alternate" href="http://cc646.example.com/index.php?seo_path=&set_language=es-ES" hreflang="es-ES">
<link rel="alternate" href="http://cc646.example.com/index.php?seo_path=&set_language=fr-FR" hreflang="fr-FR">
<link rel="alternate" href="http://cc646.example.com/index.php?seo_path=&set_language=it-IT" hreflang="it-IT">
```
I conclude the above is not the solution.

**HOWEVER**, the following is from a Google Developer page:
```
<link rel="alternate" href="https://developers.google.com/search/docs/specialty/international/localized-versions?hl=ar" hreflang="ar">
<link rel="alternate" href="https://developers.google.com/search/docs/specialty/international/localized-versions?hl=zh-cn" hreflang="zh-Hans">
<link rel="alternate" href="https://developers.google.com/search/docs/specialty/international/localized-versions?hl=zh-tw" hreflang="zh-Hant">
<link rel="alternate" href="https://developers.google.com/search/docs/specialty/international/localized-versions?hl=fr" hreflang="fr">
<link rel="alternate" href="https://developers.google.com/search/docs/specialty/international/localized-versions?hl=de" hreflang="de">
<link rel="alternate" href="https://developers.google.com/search/docs/specialty/international/localized-versions?hl=pt-br" hreflang="pt-BR">
```
Obviously, using the querystring as the distinctive characteristic is good enough for Google.

**Comment by bhsmither** [comment] 2022-11-01 01:58
Part of my untested solution is to create hreflang links using this format:
```
cc646.example.com/~es-ES/tesa31
```
Then, in controller.index.php, after the existing three lines, add these new lines:
```
if (!defined('CC_INI_SET')) {
  die('Access Denied');
}
if (preg_match('/^\~([a-z]{2}(-[a-z]{2})?)/', $_GET['seo_path'], $lang_match)) { // looking for ~es-es, for example
  $_GET['set_language'] = $lang_match[1]; // found 'es-es'
}
$_GET['seo_path'] = preg_replace('/(\~[-\w]{1,}\/)/', '', $_GET['seo_path']); // Remove /~anything/ from seo_path
```
I also commented out the `preg_replace()`statement after the point where the SEO class gets instantiated. (Anyway, that PHP statement may need to be tested.)

The next part is to change the code that creates the hreflang links.

**Comment by bhsmither** [comment] 2022-11-01 02:40
For Foundation, in element.meta.php, I used this:
```
{if $LANGUAGES}<link rel="alternate" hreflang="x-default" href="{$STORE_URL}/~{$CONFIG.default_language|lower}/index.php" />
{foreach from=$LANGUAGES item=language}
<link rel="alternate" href="{$STORE_URL}/~{$language.code|lower}{$current}" hreflang="{$language.code}">{/foreach}{/if}
```
This has not been extensively tested, nor has it been proven compliant by Google.

**Comment by havenswift-hosting** [comment] 2022-11-01 11:37
Thanks Brian - I will speak to a couple of our clients and see whether they would be willing to test this is a live environment and will let you know

**Comment by abrookbanks** [comment] 2022-11-15 09:05
Hi guys I'm hopping to hop onto this one ASAP. Let me know if you have any further findings.

**Comment by abrookbanks** [comment] 2022-11-21 13:43
Really we want something like this. I think we could add this as a feature but it would require setup in the hosting account. I suppose each language would need a subdomain assigned to it. This has to be the best way.

```
<link rel="alternate" hreflang="en" href="https://www.example.com"/>
<link rel="alternate" hreflang="id" href="https://id.example.com"/>
<link rel="alternate" hreflang="ko" href="https://ko.example.com"/>
<link rel="alternate" hreflang="ar" href="https://ar.example.com"/>
<link rel="alternate" hreflang="de" href="https://de.example.com"/>
<link rel="alternate" hreflang="es" href="https://es.example.com"/>
<link rel="alternate" hreflang="fr" href="https://fr.example.com"/>
<link rel="alternate" hreflang="it" href="https://it.example.com"/>
<link rel="alternate" hreflang="nl" href="https://nl.example.com"/>
<link rel="alternate" hreflang="pt" href="https://pt.example.com"/>
```

**Comment by abrookbanks** [comment] 2022-11-21 13:47
Following on this will be quite simple to achieve. CubeCart just need a look up table of domain to language. The developer will need to create the subdomains.

**Comment by havenswift-hosting** [comment] 2022-11-21 14:00
We would be happy to give this a go on a live client site that is having problems with this if you can provide a set of instructions

**Comment by abrookbanks** [comment] 2022-11-21 14:04
Awesome. Hopefully I haven't opened a can of worms but I think its very straightforward to develop.

**Comment by Caranxnet** [comment] 2022-11-21 14:20
Thanks, I hope this can be sorted out easily

 

Regards

 

Nicola

 

De: Al Brookbanks ***@***.***> 
Enviado el: lunes, 21 de noviembre de 2022 15:05
Para: cubecart/v6 ***@***.***>
CC: Caranxnet ***@***.***>; Author ***@***.***>
Asunto: Re: [cubecart/v6] hreflang isnt working for any languages other than the default language (Issue #3073)

 

Awesome. Hopefully I haven't opened a can of worms but I think its very straightforward to develop.

**Comment by abrookbanks** [comment] 2022-11-21 15:43
<img width="987" alt="Screenshot 2022-11-21 at 15 37 08" src="https://user-images.githubusercontent.com/4520803/203097059-d8179d4e-8231-473e-a4b8-ba60ec5abc01.png">
<img width="611" alt="Screenshot 2022-11-21 at 15 44 02" src="https://user-images.githubusercontent.com/4520803/203097251-bbb4e69d-8e15-4e63-a645-612ff9cc4bd3.png">

**Comment by abrookbanks** [comment] 2022-11-21 15:48
This was a pretty simple job and works a treat!

**Comment by abrookbanks** [comment] 2022-11-21 15:51
To test this create the DB table `CubeCart_domains`. Annoyingly there is one skin change... https://github.com/cubecart/v6/commit/93727f5dae8fe2989e3db050150820823a5b0347#diff-b5620a89ddc188cbd3844d0dd5bd9c938bd24eba845d8ef162ab98da3ef3bb92

**Comment by havenswift-hosting** [comment] 2022-11-21 15:53
I will take a look straight away, although when are you planning on releasing 6.4.8

**Comment by abrookbanks** [comment] 2022-11-21 15:54
> I will take a look straight away, although when are you planning on releasing 6.4.8

Within the next fortnight.

**Closed as completed** 2022-11-22 15:19 UTC

**Comment by havenswift-hosting** [comment] 2022-11-24 15:25
So summarising the testing and problems that I found on a live site.  The code was correctly added without any problems

1) I wasn't able to save urls against any languages except the first one - in order to continue testing, I manually added the records to the database for the two additional languages

2) The language switching to the newly created language domains ie en.domain.com and it.domain.com worked fine, however, no images were displayed for either alternate language as all links were returning 404 errors. Images for the primary language worked fine

3) Not sure what caused the issue yet but these changes caused major problems with the production of the site sitemap file

I removed the urls against each of the three languages and this solved the sitemap production problem - each url is now being included in the sitemap file using ?set_language=en-GB"

**Comment by abrookbanks** [comment] 2022-11-24 15:37
Hmm. I can't reproduce these issues. Thanks for the feedback though. It will get a bit more testing prior to release.
