### ISSUE TITLE
Text fields not importing to order inventory

### ISSUE THREAD

**Issue by NaturalSigns** [cubecart/v6#218] opened 2015-02-13 11:27 UTC
I have just tested this on a new listing made on the demo store https://demo.cubecart.com/cc6/text-test.html it has a single line text field and a multi line text field.  Checkout process records the values correctly as below...

![error 1](https://cloud.githubusercontent.com/assets/10531097/6186480/ca318bc2-b371-11e4-9376-d033ba0dfe8c.png)

But checking the admin side, fields are blank ...

![error 2](https://cloud.githubusercontent.com/assets/10531097/6186483/dfd19c4c-b371-11e4-9a45-f3b38de49b55.png)

Though 1 field (single line text) is recorded when you opt to print the invoice...

![error 3](https://cloud.githubusercontent.com/assets/10531097/6186488/f6641e58-b371-11e4-805f-2960e237383a.png)

I think this is per precious issue #189 (nightmare fix), possibly still an issue?

**Comment by abrookbanks** [comment] 2015-02-13 11:45
Duplicate of #189

**Closed by abrookbanks** 2015-02-13 11:45 UTC
Labels: duplicate
