### ISSUE TITLE
Exchange Rate - issue fetching rates

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2219] opened 2018-12-14 10:37 UTC
CubeCart calls the following URL: 
http://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml

however, this redirects to https URL, which some times can't be followed and results in a 301 error and a white screen in CubeCart.

The URL's need to be updated to HTTPS rather than HTTP for both the initial request, and fall back method.

**Comment by bhsmither** [comment] 2018-12-16 23:30
Probable duplicate of #2165.

**Closed as completed** 2019-01-23 10:51 UTC
Labels: duplicate
