### ISSUE TITLE
Foundation stock skin layout issue on Header

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#45] opened 2015-01-11 00:11 UTC
Name of language and abbreviation overlaps flag.

**Comment by abrookbanks** [comment] 2015-01-11 16:34
Have you got a screenshot? p.s. If you have it on your desktop just drag it into the text field on here.

**Comment by Dirty-Butter** [comment] 2015-01-11 20:31
![v6 - dirty butter estates collectible shoppe intro 2015-01-11 14-30-23](https://cloud.githubusercontent.com/assets/6146505/5696696/8d35fdd0-999e-11e4-89dc-17f2a352b56d.jpeg)

**Comment by Dirty-Butter** [comment] 2015-01-13 15:36
Same issue in 6.0.0b2 English (US) still overlaps flag image in header.

**Comment by abrookbanks** [comment] 2015-01-13 15:38
Hmm. I can't reproduce this. Does it happen on our demo store? https://demo.cubecart.com/cc6

**Comment by Dirty-Butter** [comment] 2015-01-13 15:55
Try installing US English and see if it shows up on your homepage then.

**Comment by abrookbanks** [comment] 2015-01-13 15:58
Hmmm mine looks like this..
![screen shot 2015-01-13 at 15 58 10](https://cloud.githubusercontent.com/assets/4520803/5723606/0621584e-9b3d-11e4-98a3-351134406470.png)

**Comment by abrookbanks** [comment] 2015-01-13 16:01
It worked on the demo store too:
![screen shot 2015-01-13 at 16 00 38](https://cloud.githubusercontent.com/assets/4520803/5723643/602b3b0c-9b3d-11e4-84e4-5cb11b094798.png)

**scratching head**

**Comment by Dirty-Butter** [comment] 2015-01-13 16:07
Me too! I'll see what it looks like in different browsers. Also, I'm on Windows 8.1. Even if it's an issue on my end, your screenshot looks odd to me. v5 would have had a row of flags with no alt showing, just as your British flag is.

**Comment by Dirty-Butter** [comment] 2015-01-13 16:19
Chrome looks right for the American flag, but the UK flag does not show, even though both languages are checked as active

**Comment by abrookbanks** [comment] 2015-01-13 16:34
Does the flag image exist in the language/flags folder?

**Comment by Dirty-Butter** [comment] 2015-01-13 17:22
The flag is there and is not corrupted.

**Comment by Dirty-Butter** [comment] 2015-01-14 17:44
Using Clean install 6.0.0b2 - Tried Chrome, IE, and FF again. None show both US and UK flag/language choices on Storefront, although both are checked in Admin Languages. Only FF has alt text overlapping flag on storefront.

**Comment by Dirty-Butter** [comment] 2015-01-14 21:08
Decided to try validator.w3.org for http://dirtybutter.com/plushcatalog/v6b2/index.php
I perhaps I spotted the problem.
Error Line 111, Column 118: Element img is missing required attribute src.

<a href="#" data-dropdown="language-switch" class="button white small"><img class="flag flag-US" alt="English (US)" /></a><br>

**Comment by abrookbanks** [comment] 2015-01-16 11:01
Excellent! Well spotted. The other issues in that report should be fixed.

**Comment by abrookbanks** [comment] 2015-01-16 11:03
Hopefully this solves it. Assuming so and closing.. we can reopen this if the issue persists after 6.0.0b3. :)

**Closed by abrookbanks** 2015-01-16 11:03 UTC
Labels: bug
