### ISSUE TITLE
http_build_query() error

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2267] opened 2019-03-18 18:02 UTC
Getting this PHP warning in the PHP error_log file across multiple 6.2.4 sites

[18-Mar-2019 17:59:02 Europe/London] PHP Warning:  http_build_query() [<a href='http://docs.php.net/manual/en/function.http-build-query.php'>function.http-build-query.php</a>]: Parameter 1 expected to be Array or Object.  Incorrect value given in /home/XXXXXXXX/public_html/classes/db/database.class.php on line 522

**Comment by bhsmither** [comment] 2019-03-19 02:43
Duplicate of #2259.

**Comment by abrookbanks** [comment] 2019-03-19 09:34
Thanks!!

**Comment by bhsmither** [comment] 2019-03-19 15:45
It seems to me that moving
```
$params = array();
```
to outside and above the `if()` block accomplishes nothing.

Am I not seeing something?

**Comment by abrookbanks** [comment] 2019-03-19 15:57
Haha... I tested it honestly I did! Over confident.. I'll have another look. Thanks for putting up with me.

**Comment by bhsmither** [comment] 2019-03-19 22:57
I meant to say there is no better results than what was accomplished via #2259.

**Comment by abrookbanks** [comment] 2019-03-27 11:33
Fixed with https://github.com/cubecart/v6/commit/ca55a8419f834d723cedef80a99652d953e9fb92

**Closed as completed by abrookbanks** 2019-03-27 11:33 UTC
