### ISSUE TITLE
Text option bug in Admin

### ISSUE THREAD

**Issue by whitepandaltd** [cubecart/v6#637] opened 2015-06-23 19:51 UTC
If a customer has made an order with text options attached to the product, The customers text stays when setting the order to processing but disappear when setting the order to complete using save and reload. Meaning that any information that has been entered using a text option is lost.

**Comment by abrookbanks** [comment] 2015-06-23 21:01
Thanks Marco. This is a duplicate of https://github.com/cubecart/v6/issues/630 which has been reopened.

**Closed by abrookbanks** 2015-06-23 21:01 UTC
