### ISSUE TITLE
Add to Basket Doubled

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#263] opened 2015-02-22 18:07 UTC
In the Foundation template file main.php, there are hard-coded `<script src=''>` for:
foundation.min.js
cubecart.js
cubecart,validat.js

Then following, $JS_SCRIPTS is iterated.

JS_SCRIPTS is assigned in the GUI class from a collection of all filenames found in the /js/ folder. The filenames located there are:
foundation.min.js
cubecart.js
cubecart.validate.js

Not being a javascript expert, I will, however, have to say that having two copies of these files *in play* invites mayhem.

(This also applies, after a fashion, when using Foundation with CC5216.)

**Comment by abrookbanks** [comment] 2015-02-23 13:14
I'm not able to reproduce this in the latest v6 build. Foundation should not be used with v5 there is added functionality to the v6 codebase for aspects of this skin that are not present in v5. Sorry! :(

**Comment by bhsmither** [comment] 2015-02-23 14:34
Is the latest build what I see on the <Code> pages?

**Comment by abrookbanks** [comment] 2015-02-23 15:07
Thats right. A sample page output (on my dev store is):

```
<!DOCTYPE html>
<html class="no-js" xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-GB">
   <head>
      <title>CubeCart</title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="canonical" href="http://www.example.com/store/">
      <link rel="shortcut icon" href="http://www.example.com/store/favicon.ico" type="image/x-icon">
      <link rel="stylesheet" href="http://www.example.com/store/skins/foundation/css/normalize.css">
      <link rel="stylesheet" href="http://www.example.com/store/skins/foundation/css/foundation.min.css">
      <link href="http://www.example.com/store/skins/foundation/css/font-awesome/css/font-awesome.min.css" rel="stylesheet">
      <link rel="stylesheet" href="http://www.example.com/store/skins/foundation/css/cubecart.css">
      <link rel="stylesheet" href="http://www.example.com/store/skins/foundation/css/cubecart.common.css">
      <link rel="stylesheet" href="http://www.example.com/store/skins/foundation/css/cubecart.helpers.css">
      <link rel="stylesheet" href="http://www.example.com/store/skins/foundation/css/cubecart.default.css">
      <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
      <meta name="description" content="">
      <meta name="keywords" content="">
      <meta name="robots" content="index, follow">
      <meta name="generator" content="cubecart">
      <script src="http://www.example.com/store/skins/foundation/js/vendor/modernizr.min.js"></script>
      <script src="http://www.example.com/store/skins/foundation/js/vendor/jquery.js"></script>
   </head>
   <body>
      <div class="off-canvas-wrap" data-offcanvas>
         <div class="inner-wrap">
            <aside class="right-off-canvas-menu">
               <div class="box-basket-content" id="box-basket-content">
                  <h4 class="mini-basket-title nomarg pad-side">Your Basket</h4>
                  <div class="pad-side basket-detail">
                     <p class="pad-top text-center">Your basket is empty.</p>
                  </div>
               </div>
            </aside>
            <aside class="left-off-canvas-menu">
               <ul class="off-canvas-list">
                  <li><label>Your Account</label></li>
                  <li><a href="http://www.example.com/store/login.html">Login / Register</a></li>
               </ul>
               <ul class="off-canvas-list">
                  <li><label>Change Currency</label></li>
                  <li><a href="http://www.example.com/store/index.php?set_currency=USD">$ USD  (United States dollar)</a></li>
                  <li><a href="http://www.example.com/store/index.php?set_currency=JPY">¥ JPY  (Japanese yen)</a></li>
                  <li><a href="http://www.example.com/store/index.php?set_currency=CAD">$ CAD  (Canadian Dollar)</a></li>
                  <li><a href="http://www.example.com/store/index.php?set_currency=EUR">€ EUR  (Euro)</a></li>
                  <li><a href="http://www.example.com/store/index.php?set_currency=AUD">$ AUD  (Australian Dollar)</a></li>
               </ul>
            </aside>
            <div class="row marg-top">
               <div class="small-5 medium-4 large-3 columns">
                  <a href="http://www.example.com/store" class="main-logo"><img src="/cc6/skins/foundation/images/default/logo/default.png" alt="CubeCart"></a>
               </div>
               <div class="small-7 medium-8 large-9 columns nav-boxes">
                  <div class="row">
                     <div class="right text-center">
                        <div id="mini-basket">
                           <div class="show-for-medium-up">
                              <a href="#" id="basket-summary" class="button white small"><i class="fa fa-shopping-cart"></i> £0.00</a> 
                              <div class="basket-detail-container hide" id="basket-detail">
                                 <div class="mini-basket-arrow"></div>
                                 <div class="box-basket-content" id="box-basket-content">
                                    <h4 class="mini-basket-title nomarg pad-side">Your Basket</h4>
                                    <div class="pad-side basket-detail">
                                       <p class="pad-top text-center">Your basket is empty.</p>
                                    </div>
                                 </div>
                              </div>
                           </div>
                           <div class="show-for-small-only">
                              <div class="show-for-small-only"><a class="right-off-canvas-toggle button white tiny" href="#"><i class="fa fa-shopping-cart fa-2x"></i></a></div>
                              <div class="hide panel radius small-basket-detail-container js_fadeOut" id="small-basket-detail"><i class="fa fa-check"></i> Added to Basket</div>
                           </div>
                        </div>
                     </div>
                     <div class="right text-center show-for-small"><a class="left-off-canvas-toggle button white tiny" href="#"><i class="fa fa-bars fa-2x"></i> <a class="button white tiny show-small-search" href="#"><i class="fa fa-search fa-2x"></i></a></div>
                     <div class="right text-center show-for-medium-up" id="box-currency">
                        <a href="#" data-dropdown="currency-switch" class="button white small">&pound; GBP </a>
                        <ul id="currency-switch" data-dropdown-content class="f-dropdown">
                           <li class="text-left"><a href="http://www.example.com/store/index.php?set_currency=USD">$ USD  (United States dollar)</a></li>
                           <li class="text-left"><a href="http://www.example.com/store/index.php?set_currency=JPY">&yen; JPY  (Japanese yen)</a></li>
                           <li class="text-left"><a href="http://www.example.com/store/index.php?set_currency=CAD">$ CAD  (Canadian Dollar)</a></li>
                           <li class="text-left"><a href="http://www.example.com/store/index.php?set_currency=EUR">&euro; EUR  (Euro)</a></li>
                           <li class="text-left"><a href="http://www.example.com/store/index.php?set_currency=AUD">$ AUD  (Australian Dollar)</a></li>
                        </ul>
                     </div>
                     <div class="right text-right show-for-medium-up" id="box-session">
                        <a href="http://www.example.com/store/login.html" class="button white small nopad-sides">Login</a> / <a href="http://www.example.com/store/register.html" class="button white small nopad-sides">Register</a>
                     </div>
                  </div>
                  <div class="row show-for-medium-up">
                     <div class="small-12 columns">
                        <div  id="box-search">
                           <form action="http://www.example.com/store/search.html" id="search_form" method="get">
                              <div class="row collapse">
                                 <div class="small-10 large-11 columns">
                                    <input name="search[keywords]" type="text" placeholder="Search our store" required>
                                 </div>
                                 <div class="small-2 large-1 columns">
                                    <button class="button postfix" type="submit" value="Search"><i class="fa fa-search"></i></button>
                                 </div>
                              </div>
                              <input type="hidden" name="_a" value="category">
                           </form>
                           <div class="hide" id="validate_search">Please enter a search keyword</div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
            <div class="row hide" id="small-search">
               <div class="small-12 columns">
                  <div  id="box-search">
                     <form action="http://www.example.com/store/search.html" id="search_form" method="get">
                        <div class="row collapse">
                           <div class="small-10 large-11 columns">
                              <input name="search[keywords]" type="text" placeholder="Search our store" required>
                           </div>
                           <div class="small-2 large-1 columns">
                              <button class="button postfix" type="submit" value="Search"><i class="fa fa-search"></i></button>
                           </div>
                        </div>
                        <input type="hidden" name="_a" value="category">
                     </form>
                     <div class="hide" id="validate_search">Please enter a search keyword</div>
                  </div>
               </div>
            </div>
            <div class="row">
               <div class="small-12 columns small-collapse">
                  <nav class="top-bar category-nav" data-topbar="" id="box-navigation">
                     <ul class="title-area">
                        <li class="name"></li>
                        <li class="toggle-topbar left"><a href="">Shop by Category <i class="fa fa-caret-down"></i></a></li>
                     </ul>
                     <section class="top-bar-section">
                        <ul class="left">
                           <li class="show-for-medium-up"><a href="http://www.example.com/store" title="Home"><i class="fa fa-home"></i></a></li>
                           <li class="has-dropdown">
                              <a href="http://www.example.com/store/werwer-c3.html" title="werwer">werwer</a>
                           </li>
                           <li class="has-dropdown">
                              <a href="http://www.example.com/store/werwer.html" title="werwer">werwer</a>
                           </li>
                           <li class="has-dropdown">
                              <a href="http://www.example.com/store/test-category.html" title="Test Category">Test Category</a>
                           </li>
                           <li><a href="http://www.example.com/store/sale-items.html" title="Sale Items">Sale Items</a></li>
                        </ul>
                     </section>
                  </nav>
               </div>
            </div>
            <div class="row">
               <div class="small-12 columns small-collapse">
                  <div id="element-breadcrumbs">
                     <div class="thickpad-top"></div>
                  </div>
               </div>
            </div>
            <div class="row home_wrapper">
               <div class="small-12 large-9 columns small-collapse">
                  <div id="content_homepage">
                     <h1>Welcome to CubeCart</h1>
                     <ul class="example-orbit" data-orbit>
                        <li>
                           <img src="skins/foundation/images/examples/slide1.jpg" alt="slide 1" />
                           <div class="orbit-caption">
                              Promotional Message One
                           </div>
                        </li>
                        <li class="active">
                           <img src="skins/foundation/images/examples/slide2.jpg" alt="slide 2" />
                        </li>
                        <li>
                           <img src="skins/foundation/images/examples/slide3.jpg" alt="slide 3" />
                           <div class="orbit-caption">
                              Promotional Message Two
                           </div>
                        </li>
                     </ul>
                     This message and the slider above (including the images) can be edited using the <strong><span style="color: red;">Rich</span> <span style="color: blue;">Text</span> <span style="color: green;">Editor</span></strong> which can be found in the admin control panel of your store under <i>File Manager &gt; Documents</i>.
                  </div>
                  <div id="content_latest_products">
                     <h2>Latest Products</h2>
                     <ul class="small-block-grid-1 medium-block-grid-3 large-block-grid-3" data-equalizer>
                        <li>
                           <form action="http://www.example.com/store/" method="post" class="panel add_to_basket" data-equalizer-watch>
                              <div class="text-center">
                                 <a class="th" href="http://www.example.com/store/test-category/test-product.html" title="Test Product"><img src="http://www.example.com/store/skins/foundation/images/noimage.png" alt="Test Product"></a>
                              </div>
                              <h3><a href="http://www.example.com/store/test-category/test-product.html" title="Test Product">Test Product</a></h3>
                              <span class="old_price">£10.00</span> <span class="sale_price">£6.99</span>
                              <!--<a href="http://www.example.com/store/test-category/test-product.html" title="Test Product" class="button tiny secondary left">Info</a>-->
                              <div class="marg-top">
                                 <div class="row collapse marg-top">
                                    <div class="small-3 columns">
                                       <input type="text" name="quantity" value="1" class="quantity required text-center">
                                    </div>
                                    <div class="small-9 columns ">
                                       <button type="submit" value="Add to Basket" class="button small postfix">Add to Basket</button>
                                    </div>
                                 </div>
                              </div>
                              <input type="hidden" name="add" value="1">
                           </form>
                        </li>
                     </ul>
                  </div>
               </div>
               <div class="large-3 columns show-for-large-up">
                  <div class="panel" id="box-featured">
                     <h3>Featured Product</h3>
                     <a class="th" href="http://www.example.com/store/test-category/test-product.html" title="Test Product">
                     <img src="http://www.example.com/store/skins/foundation/images/noimage.png" alt="Test Product">
                     </a>
                     <h4><a href="http://www.example.com/store/test-category/test-product.html" title="Test Product">Test Product</a></h4>
                     <span class="old_price">£10.00</span> <span class="sale_price">£6.99</span>
                  </div>
                  <div class="panel" id="box-popular">
                     <h3>Best Sellers</h3>
                     <ol>
                        <li><a href="http://www.example.com/store/test-category/test-product.html" title="Test Product">Test Product</a><br>
                        </li>
                     </ol>
                  </div>
                  <div class="panel" id="box-sale_items">
                     <h3>On Sale</h3>
                     <ul>
                        <li>
                           <a href="http://www.example.com/store/test-category/test-product.html" title="Test Product (Save £3.01)">Test Product</a><br>
                           <span class="old_price">£10.00</span> <span class="sale_price">£6.99</span>
                        </li>
                     </ul>
                  </div>
               </div>
               <a href="#" class="back-to-top"><i class="fa fa-angle-up"></i> Top</a>
            </div>
            <footer>
               <div class="row">
                  <div class="medium-7 large-7 columns">
                     <div id="box-documents">
                        <h3>Information</h3>
                        <nav>
                           <ul class="small-block-grid-1 medium-block-grid-3 large-block-grid-3">
                              <li><a href="http://www.example.com/store/about-us.html" title="About Us" >About Us</a></li>
                              <li><a href="http://www.example.com/store/terms-and-conditions.html" title="Terms and Conditions" >Terms and Conditions</a></li>
                              <li><a href="http://www.example.com/store/privacy-policy.html" title="Privacy Policy" >Privacy Policy</a></li>
                              <li><a href="http://www.example.com/store/returns-policy.html" title="Returns Policy" >Returns Policy</a></li>
                              <li><a href="http://www.example.com/store/contact-us.html" title="Contact Us">Contact Us</a></li>
                           </ul>
                        </nav>
                     </div>
                     <p>
                        &copy;2015 osh.cubecart.com - All rights reserved.
                     </p>
                  </div>
                  <div class="medium-5 large-5 columns">
                     <div class="element-social">
                        <h3>Follow Us</h3>
                        <ul class="small-block-grid-4 no-bullet nomarg social-icons text-left">
                           <li><a href="https://twitter.com/cubecart" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                           <li><a href="https://www.facebook.com/cubecart" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                           <li><a href="https://plus.google.com/0" title="Google+"><i class="fa fa-google-plus"></i></a></li>
                           <li><a href="http://www.youtube.com/user/cubecart" title="YouTube"><i class="fa fa-youtube"></i></a></li>
                        </ul>
                     </div>
                     <div class="row collapse">
                        <div class="large-12 columns">
                           <div id="box-newsletter">
                              <h3>Mailing List</h3>
                              <form action="http://www.example.com/store/" method="post" id="newsletter_form_box">
                                 <div class="hide">Enter your e-mail address to receive our newsletter</div>
                                 <div class="row collapse">
                                    <div class="small-9 columns"><input name="subscribe" id="newsletter_email" type="text" size="18" maxlength="250" title="Subscribe"/></div>
                                    <div class="small-3 columns"><input type="submit" class="button postfix" value="Subscribe"></div>
                                 </div>
                              </form>
                              <div class="hide" id="validate_email">Please enter a valid email address.</div>
                              <div class="hide" id="validate_already_subscribed">Email address already subscribed.</div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </footer>
            <script src="http://www.example.com/store/skins/foundation/js/foundation.min.js"></script>
            <script src="http://www.example.com/store/skins/foundation/js/vendor/jquery.rating.min.js"></script>
            <script src="http://www.example.com/store/skins/foundation/js/vendor/jquery.validate.min.js"></script>
            <script src="http://www.example.com/store/skins/foundation/js/vendor/jquery.jscroll.min.js"></script>
            <script src="http://www.example.com/store/skins/foundation/js/vendor/jquery.cookie.min.js"></script>
            <script src="http://www.example.com/store/skins/foundation/js/cubecart.js"></script>
            <script src="http://www.example.com/store/skins/foundation/js/cubecart.validate.js"></script>
            <script type="text/javascript" src="http://www.example.com/store/skins/foundation/js/cubecart.js"></script>
            <script type="text/javascript" src="http://www.example.com/store/skins/foundation/js/cubecart.validate.js"></script>
            <script type="text/javascript" src="http://www.example.com/store/skins/foundation/js/foundation.min.js"></script>
            <script>
               $(document).foundation({
                  orbit: {
                     slide_number: false,
                     timer_show_progress_bar: false
                  }
               });
            </script>
            <a class="exit-off-canvas"></a>
            <div class="row" id="ccpower">
               <div class="large-12 columns text-center">
                  <p>eCommerce by <a href="http://www.cubecart.com">CubeCart</a></p>
               </div>
            </div>
         </div>
      </div>
   </body>
</html>
```

**Comment by bhsmither** [comment] 2015-02-23 15:42
In this code, I see two calls each for: foundation.min.js, cubecart.js, and cubecart.validate.js.

I just had a thought -- aren't browsers supposed to be smart about fetching a page's resources and only fetch one copy of an image, a CSS file, a javascript file, etc, no matter how many times any such resource is used in the document?

But fetching a resource only once **does not mean** it's put in play only once.

And, we are discussing a browser's handling of the document and the execution of the javascript connected to the document, not the PHP code that rendered and delivered the document. So I will assert this is a Foundation issue and **not** the version of CubeCart.

**Comment by abrookbanks** [comment] 2015-02-23 15:50
Well I'm code blind because there are in there twice!!

**Comment by abrookbanks** [comment] 2015-02-23 16:03
This is fixed now. Thanks Brian!

**Closed by abrookbanks** 2015-02-23 16:03 UTC
Labels: bug
