### ISSUE TITLE
Changing Order Status Save Not Working

### ISSUE THREAD

**Issue by adzpower** [cubecart/v6#206] opened 2015-02-12 04:52 UTC
In the admin section, select an order to work on. When changing the order status to declined or cancelled etc then hitting Save or Save & Reload button causes a quote looking white text box to pop up at the very top left of your browser "Please fill out this field." It is not pointing to any field to fill out and you can't proceed to save the status.

**Comment by NaturalSigns** [comment] 2015-02-12 11:13
Have you looked at the "Inventory" tab?, i have the same issue (running beta 6.0.0b5).  If you raise an order from the store front then view in admin the data is not recorded correctly [some text fields are blank].  To change the order status put something in a 'required' field on the inventory tab, save and then you can change the order status (works for me).  You don't get the 'Please fill out this field' warning in chrome (only found it using firefox).

**Comment by abrookbanks** [comment] 2015-02-12 13:47
I can't reproduce this one on b5.

**Comment by adzpower** [comment] 2015-02-12 22:36
It still pops up, but seems to be saving. Hopefully gets sorted soon, don't want to teach the client this run around fix. Here's screen shots of both tabs, one with the pop up.

![screenshot-statusupdate](https://cloud.githubusercontent.com/assets/10970873/6178471/00e56c68-b35b-11e4-8b65-f87ee307d8d1.jpg)
![screenshot-statusupdate2](https://cloud.githubusercontent.com/assets/10970873/6178470/00e2c6b6-b35b-11e4-9688-fb74f1dc91a6.jpg)

**Comment by abrookbanks** [comment] 2015-02-18 14:30
I still can't reproduce this. Please may I have access to your store.

I'll take a look at this internally... please send URL, admin login and FTP access to our sales dept and I'll pick it up.. https://support.cubecart.com/index.php?/Tickets/Submit

**Comment by abrookbanks** [comment] 2015-02-19 17:35
This is fixed in another issue (I can't find for the life of me). It was a bug that caused product options to not assign to the category properly. The form is complaining that some of the required product options don't have a value. These are hidden in a tab that's not visible and the browser doesn't know where to render the message to complete them. Hence they show up there... 

I don't think product options should be required in admin. The customer has to pick required ones but the staff should know whats required. For this reason I am about to submit a fix..

**Closed** 2015-02-19 17:40 UTC
Labels: duplicate, optimisation
