### ISSUE TITLE
Possible Product Images Bug #1 - Refresh Required To Display Main Product Image

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#1730] opened 2017-09-14 16:27 UTC
This one has been mentioned to me by store owners using:
- stock foundation skin
- custom copies of the foundation skin
- my 'Custom Foundation 5' skin

Upon loading a product page for the first time, the main product image is not displayed.
Doing a refresh of the page, the main product image loads correctly.

If this issue occurs for you:
- what skin were you using?
- what browser were you using?
- was a soft or hard refresh required to display the main product image?

**Comment by briansandall** [comment] 2017-09-15 15:20
I have this issue - I use a custom skin based on foundation, but haven't changed any/much of the image HTML.

Happens to me using both Chrome and Firefox. Usually a soft refresh is enough to sort it out, but sometimes a hard refresh is required.

**Comment by MrGweb** [comment] 2017-09-15 23:08
This also is a problem with our site - Im trying to see if i can find the issue as well - does not seem to happen on stock skin

**Comment by MrGweb** [comment] 2017-09-20 21:49
only thing i see but dont know why its getting an Element giving max/min  at 0 
<a href="#" class="open-clearing" data-thumb-index="0" **style="min-height: 0px;max-height: 0px;"**><img src="https://www.aviationmuseum.com.au/shop/images/cache/13420.500.jpg" alt="T Shirt - Spitfire Mk XVI" id="img-preview"></a>

**Comment by abrookbanks** [comment] 2017-09-22 15:29
I couldn't reproduce this. I then deleted all images and tried again. I found that if there were no images in the system at all I could reproduce it. The upload image was given a checkbox and not a star. Working on this...

**Comment by abrookbanks** [comment] 2017-09-26 08:35
I was able to reproduce this if an image was deleted then the product was edited to have a new image. On deletion of the image the image_index was not removed! This meant that the second time it was assigned the new image was not assigned as main image by default as it thought it had one already. 

The fix was to delete the image_index row(s) for the deleted file. This resolved the issue. 

I took it one stage further and updated the CubeCart_category table too to set the category image ID to 0 when deleted.

**Comment by briansandall** [comment] 2017-09-26 14:58
@abrookbanks None of the images on my site that have this issue were deleted / reassigned - this is happening with newly added products.

Those with more than one image correctly show the thumbnails. Only the main image requires a refresh to display.

**Comment by abrookbanks** [comment] 2017-09-26 14:59
Do you mean the main image showing in the preview space to the right of the file manager or on the front end of the shop?

**Comment by briansandall** [comment] 2017-09-26 14:59
Front end of the shop.

**Comment by abrookbanks** [comment] 2017-09-26 15:00
Hmmmm...  must have found a different related bug..

**Comment by abrookbanks** [comment] 2017-09-26 15:35
I'm sorry I just cannot reproduce this.. What am I doing differently?

Movie here: http://static.cubecart.com/github-1730.mp17304

**Comment by briansandall** [comment] 2017-09-26 15:46
Hm, I'm not sure, either. I'm using the horizontal template, if that makes a difference, and I only notice this on the live store - my local test sites all work fine.

**Comment by briansandall** [comment] 2017-09-26 15:50
Something I just discovered: if multiple products share the same image, the image will display correctly for any product you open after the first, even without refreshing the page on the first product.

**Comment by abrookbanks** [comment] 2017-09-26 15:52
So it sounds like the cached version of the image isn't made on first page load. That's not something I have been able to reproduce. It's not asynchronous.

**Comment by briansandall** [comment] 2017-09-26 15:55
The cached images already existed in my case.

**Comment by abrookbanks** [comment] 2017-09-27 09:10
I just can't reproduce this. :(

**Comment by abrookbanks** [comment] 2017-09-27 09:17
It might have even been fixed already with the latest 6.1.11 branch. I've reworked parts of the file manager.

**Comment by briansandall** [comment] 2017-09-27 15:37
I don't believe this is an issue with the file manager - commenting out the line mentioned in #1731 seems to resolve this issue entirely, so it appears that the `ip` variable is somehow ending up with a 0 height or width.

**Comment by abrookbanks** [comment] 2017-09-27 15:38
Oh right! Wow I was way off the mark.. let me look into that..

**Comment by abrookbanks** [comment] 2017-09-27 15:45
Can someone try this for me?

```
    if($('a.open-clearing img#img-preview').length) {
        $('a.open-clearing img#img-preview').load(function() {
            var ip = $('a.open-clearing img#img-preview');
            var ip_height = ip.height();
            var ip_width = ip.width();
            var min_height = ip_width * 0.7;
            if(ip_height<min_height) {
                ip_height = min_height;
            }
            $('a.open-clearing img').css({'min-height':ip_height+'px', 'max-height': ip_height+'px'});
        });
    }
```

**Comment by briansandall** [comment] 2017-09-27 15:46
Just one minute, please.

**Comment by abrookbanks** [comment] 2017-09-27 15:47
You are fast!

**Comment by briansandall** [comment] 2017-09-27 15:48
So far so good! Haven't been able to reproduce the issue with your new code. I'm so glad you decided to continue working on CubeCart, btw. :)

**Comment by abrookbanks** [comment] 2017-09-27 15:53
Fab.. well lets commit that and hope this doesn't raise its head again. 

Want to get 6.1.11 out and then make some more functionality progress... I started a new default theme but I think it may be heading to the trash..

**Comment by abrookbanks** [comment] 2017-09-27 15:55
Closing.. but I will reopen if anyone thinks it still needs work.

**Closed by abrookbanks** 2017-09-27 15:55 UTC
