### ISSUE TITLE
PayPal Express Checkout 1.0.4 with v6.0.2

### ISSUE THREAD

**Issue by indrum** [cubecart/v6#471] opened 2015-04-17 13:03 UTC
v6.0.2 and PayPay Pro 1.0.4 - Express Checkout Orders are arriving as 'pending', when they should be ‘processing’, while transaction logs confirm order from PayPal

The Customer List page shows the type, name, email and date while their 'orders' is marked as 0 and remains at 0 when order status updated or complete

**Comment by abrookbanks** [comment] 2015-04-17 13:26
What does your PayPal IPN History say? I've seen this issue a million and one times. :) https://support.cubecart.com/index.php?/Knowledgebase/Article/View/213/41/orders-placed-with-paypal-are-not-automatically-changing-status-to-processing

**Comment by indrum** [comment] 2015-04-17 13:33
http://www.kulacards.co.uk/index.php?_g=rm&type=plugins&cmd=call&module=PayPal_Pro

**Comment by indrum** [comment] 2015-04-17 13:44
Not much. Therefore I assume one would need to set up an Instant Payment Notification (IPN) and choose and IPN setting?

**Comment by abrookbanks** [comment] 2015-04-17 13:46
Please can you elaborate on "not much". CubeCart specifies the IPN notification URL on every transaction. Do you see any IPN history logs? If you do please can you tell me the status of them.

**Comment by indrum** [comment] 2015-04-17 13:54
The status is stated as 'Sent' for all

**Comment by abrookbanks** [comment] 2015-04-17 13:55
OK whats the HTTP response code.

**Comment by indrum** [comment] 2015-04-17 14:01
200

**Comment by abrookbanks** [comment] 2015-04-17 14:09
Are you 100% sure that those IPN requests are for the orders with a status of pending? The order number will be in the IPN message.

**Comment by indrum** [comment] 2015-04-17 14:11
I will monitor the status as new orders arrive and reply in due course

**Comment by abrookbanks** [comment] 2015-04-17 14:14
Ok great, it really should work. I'll be surprised if there is a bug here but its possible.

**Comment by indrum** [comment] 2015-04-17 14:19
PayPal Express Checkout order marked as Pending - IPN log confirms SENT : 200 and Invoice ID matched

**Comment by abrookbanks** [comment] 2015-04-20 08:13
I am able to reproduce this issue. The previous release of the modules work 1.0.3 but 1.0.4 doesn't. I should have a fix in the next hour.

**Comment by abrookbanks** [comment] 2015-04-20 09:13
Ok this is now working. If you;

1. upgrade your PayPal module to 1.0.6: https://www.cubecart.com/extensions/plugins/paypal-pro-express-checkout
2. download the latest build and upload all files excluding the setup folder https://github.com/cubecart/v6/archive/master.zip

All should then be fine. The latest build with latest PayPal can be tested here: http://brooky.com/ipntest/

**Closed by abrookbanks** 2015-04-20 09:13 UTC
Labels: bug

**Comment by tainbare** [comment] 2015-04-20 12:30
I can confirm I have done above and works for me. Thank you.

**Comment by abrookbanks** [comment] 2015-04-20 13:12
GREAT! Thanks for following up.
