### ISSUE TITLE
Sort not working on Transaction Logs

### ISSUE THREAD

**Issue by wairds** [cubecart/v6#2167] opened 2018-09-09 05:37 UTC
Sort does not appear to be working on any of the columns in Dashboard/Orders/Transaction Logs.

**Comment by abrookbanks** [comment] 2019-01-31 14:56
Hmm.. I can't reproduce this. Are there specific steps I need to reproduce this?

![screenshot 2019-01-31 at 14 55 20](https://user-images.githubusercontent.com/4520803/52062359-4c649f00-2568-11e9-8f59-e8ad865d1658.png)
![screenshot 2019-01-31 at 14 55 15](https://user-images.githubusercontent.com/4520803/52062360-4c649f00-2568-11e9-9fb5-6ebf2e425227.png)
![screenshot 2019-01-31 at 14 55 10](https://user-images.githubusercontent.com/4520803/52062362-4c649f00-2568-11e9-9ffe-58093bab3f0f.png)
![screenshot 2019-01-31 at 14 55 05](https://user-images.githubusercontent.com/4520803/52062363-4cfd3580-2568-11e9-9101-e23cfcee8127.png)
![screenshot 2019-01-31 at 14 55 00](https://user-images.githubusercontent.com/4520803/52062364-4cfd3580-2568-11e9-8a39-e41bf9f834bf.png)

**Comment by abrookbanks** [comment] 2019-01-31 14:57
Closing but I will reopen if I can have further instructions to reproduce this.

**Closed as completed by abrookbanks** 2019-01-31 14:57 UTC
Labels: invalid
