### ISSUE TITLE
Images assigned to a product is not ticked when browsing to the product under admin

### ISSUE THREAD

**Issue by bos4711** [cubecart/v6#1931] opened 2018-04-06 11:36 UTC
CC 6.1.13

I found out that when cloning an existing product (with images) and replacing the clone's images with new ones, the active images are not ticked under Products -> (Product) -> Images. Then I found out that this problem applies to all products, and not clones.

[Image showing the problem](https://www.dropbox.com/s/dvlosr1fb50j8ai/cc6_no_images.png?dl=0)

The four images marked in red are used for the active product, but there are no ticks.

**Comment by abrookbanks** [comment] 2018-04-06 15:17
I dragged your screenshot into GitHub to ensure we don't lose it. Thanks. 
![cc6_no_images_preview](https://user-images.githubusercontent.com/4520803/38429347-fc1e5368-39b5-11e8-9772-288908979302.png)

**Comment by abrookbanks** [comment] 2018-04-10 11:20
I can't reproduce this. Can you give me precise steps and clarify exactly what you do when you are "replacing the clone's images with new ones"?

Do you upload new ones? Choose existing ones? 

Please can you also update to the latest version of CubeCart.

**Comment by abrookbanks** [comment] 2018-04-10 11:26
I'm going to close this for now as it's such a core feature with no known problems. If you can log a support ticket we can look at your store for you. It may be worth clearing your browser cache after updating to the latest version.

**Closed as completed by abrookbanks** 2018-04-10 11:26 UTC

**Comment by bos4711** [comment] 2018-04-10 12:16
Hi again.
Forget about the cloning, the issue applies to all products. Whenever going into Product -> Images, no images at all are ticked in that list (even if the product has images from there). For categories, the images are ticked, but not for images.

Here's a screen recording showing the error for one of my products:

https://www.dropbox.com/s/0i110mpi926sx62/cc6_no_images.mp4?dl=0

Unfortunately the mouse movement was not captured, but hopefully you will see what's going on.

**Comment by bos4711** [comment] 2018-04-10 12:21
I will upgrade as soon as I can, but since this error has been there for the past 2-3 upgrades (it's not until now it became annoying enough for me to report) I don't have much faith in that an upgrade will help here.

**Comment by demand73** [comment] 2018-05-01 00:56
Can this be because the images are in a sub-folder? 
I will correct myself in this mather, works fine even with subfolders.

**Comment by bos4711** [comment] 2018-05-02 10:15
Highly unlikely, since the categories are in a sub-folder as well, and the category ticks are working as expected.

**Comment by abrookbanks** [comment] 2018-05-02 11:10
Guys I'll look at this asap. GDPR issues have to come first.

**Comment by bos4711** [comment] 2018-05-25 06:11
Upgraded to 6.2.0 yesterday, and the issue is resolved there.
