### ISSUE TITLE
Adding products from list view doubles in shopping cart (6.0.0b2)

### ISSUE THREAD

**Issue by Rob-Tea** [cubecart/v6#68] opened 2015-01-15 00:19 UTC
Adding X products to cart from list view gives 2X in the shopping basket.  Product pages works OK though.

Also on default foundation skin, when using "expanded category navigation tree" the width of the expanded options becomes full width of the header (shown below).  I think this should instead behave like the main www.cubecart.com site and be a narrow column.

![image](https://cloud.githubusercontent.com/assets/10531097/5750340/8113320c-9c4b-11e4-858c-44d1b89ee1d8.jpg)

**Comment by abrookbanks** [comment] 2015-01-15 11:11
I can't reproduce this issue of double contents in the basket. Maybe you can share store access securely so I can check it out? 
https://support.cubecart.com/index.php?/Tickets/Submit

Hmmm our demo store doesn't do this. It is at a particular screen resolution?
![screen shot 2015-01-15 at 11 08 36](https://cloud.githubusercontent.com/assets/4520803/5756386/ecfd9e02-9ca6-11e4-88c2-ff65b69dab17.png)

**Comment by NaturalSigns** [comment] 2015-01-15 11:47
No problem on separating the issues, a very good point, sorry.  Next time i will raise on different posts.

ISSUE 1
Bizarrely the double basket contents only occurs on IOS (tested on a ipad), its fine on PC/chrome & firefox.  Just checked on someone elses ipad and it still happens. My temporary site is here www.naturalsigns.co.uk/new_cc if that helps.

ISSUE 2
Again this behaves slightly different on an ipad, but your example above shows hovering over "TV & Home Cinema", when you click on the demo site it goes full wicth, this may be as intended (so please ignore me).  but the 2 sites which seem to have the same style bar ... https://www.cubecart.com/ (looks to work correctly) unlike https://demo.cubecart.com/cc6/(goes full width when clicked (not hover over) .

![screen shot](https://cloud.githubusercontent.com/assets/10531097/5756814/d2c90742-9cab-11e4-8fc3-81491f9e7258.png)

**Comment by abrookbanks** [comment] 2015-01-21 12:46
I can't reproduce this with the latest code but we had quite a few issues around it and a lot of the JS has been recoded. I'm pretty confident this is resolved so I am going to close it. If the issue persists after the beta 3 release we can reopen and investigate some more.

**Closed by abrookbanks** 2015-01-21 12:46 UTC
