### ISSUE TITLE
Address Book Bug

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#305] opened 2015-03-03 04:54 UTC
I cannot save my shipping address details in the address book. It says its been saved but when I look at it again it is gone?

**Comment by abrookbanks** [comment] 2015-03-03 09:50
I can't reproduce this at all. Maybe I can take a look at your store privately.

**Comment by bondimedical3** [comment] 2015-03-03 10:11
Hi

Can I just email you the admin username and password?

Regards

Marty E
Bondimedical

**Comment by abrookbanks** [comment] 2015-03-03 10:20
Will probably need FTP too. Don't reply to this email with it as its public.

https://support.cubecart.com/index.php?/Tickets/Submit

**Comment by bondimedical3** [comment] 2015-03-04 07:34
Did you do anything because it seems to be working now?

**Comment by abrookbanks** [comment] 2015-03-04 07:35
I haven't changed anything. I'll close this. Please reopen if the issue persists.

**Comment by bondimedical3** [comment] 2015-03-06 05:02
I have just done a whole new install of beta 7 and selected the drop tables to overwrite data and the same issue has occured?

**Closed** 2015-03-09 08:39 UTC
Labels: invalid / unreproducible

**Comment by farl4biz** [comment] 2015-03-28 16:06
I have the same problem on http://www.hebbestools.nl. People who signed in cannot add their address and cannot order anything. I get the message: Saving address failed (translated from Dutch). 
There is no error about it in the error logboek in the admin. And I want to say we did not delete (drop) the database. I am using the latest version 6.0.2.

![schermafbeelding 2015-03-28 om 12 31 52](https://cloud.githubusercontent.com/assets/2842652/6881733/79de1d8a-d56c-11e4-8d33-d968e8f50df8.png)
