### ISSUE TITLE
Registering a Ghost

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#194] opened 2015-02-10 00:31 UTC
Unless I missed something, I think #95 has not yet fixed this issue.

Specifically, when the shopper clicks the "?_a=register" link instead of  `[ ] I would like to create an account` at checkout.

In `User->registerUser()`, `$existing` will have the record, and `'type'` is 2. The record is updated to have `'type'` = 1 and the password that was entered on the form. Then, a test is made that will always be true and control is passed to `User->authenticate()`.

I think here is one problem (need to confirm): the `'new_password'` column currently contains zero from when this record was first created during ghost/guest checkout when `User->createUser()` was called and is not getting set to 1 when registerUser() creates a CC5 salted hash. There is now an out-of-sync situation between the hash and the hash-type flag.

In `authenticate()`, fix #95 then queries for a `'type'` = 2 record, **which fails**. Password->getSaltedOld() is called **which does not match** the previously derived password hash.

The failure to execute fix #95 means CubeCart is not building a `createUser()`'d situation.

Also, I fail to understand the need to recurse into `authenticate()`. It just seems to me that working through `authenticate()` once is sufficient.

**Comment by bhsmither** [comment] 2015-02-10 05:57
This what I tried in `User->registerUser()`:
```
if($existing[0]['type']==2) {
  $_POST['type'] = 1;
  $_POST['new_password'] = 1;
  $GLOBALS['db']->update('CubeCart_customer', $_POST, array('email' => strtolower($_POST['email'])));
  $insert = $existing[0]['customer_id'];
```
I got logged in. Fix #95 wasn't needed.

Of course, testing is required.

**Comment by bhsmither** [comment] 2015-02-10 06:20
But I ended up at `_a=account`, not back at `_a=confirm` like fix #95 says.

**Comment by SemperFiWS** [comment] 2015-05-26 16:38
I noticed something similar regarding the redirect on a clients store a while back.

If you log in via the login page, with contents in the basket, you do get redirected to the basket correctly.
I believe this is done via the hidden redir field.

But this does not exist as part of the registration page.

I may be wrong here, but in CC3/CC4 I believe the redir field existed in both.
It might also have had its value set by what page the customer was on previously, rather than if basket contents exist.
That way if they were in the basket, they were redirected back to the basket upon logging in or registering.
But if they were not in the basket, they were returned to what page they were on previously.

Could a similar system be used in CC6?

**Comment by abrookbanks** [comment] 2015-05-29 15:56
I got round to this one eventually!!! I added the new_password value as 1 and then experimented with redirects depending on the basket having contents. The problem is that if you force a redirect to checkout it then prompts for an address which is confusing. It's a bit pressuring. It seems to make sense to redirect to the account overview page after registration. Redirecting to the profile page too felt odd. Closing for now but happy to discuss if you so wish.

**Closed by abrookbanks** 2015-05-29 15:56 UTC
