### ISSUE TITLE
Partial product code search

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#650] opened 2015-06-28 21:14 UTC
When searching for a product via admin you can do a partial search.
e.g.
Product Code = ABCDE12345
Running a search for just 12345 or ABCDE will return the product.

This same functionality should exist on the customer side of the store too.
But currently if you search for an incomplete product code, no results are returned.

**Comment by abrookbanks** [comment] 2015-06-29 08:08
Duplicate of #599 fixed in 6.0.6 already.

**Closed by abrookbanks** 2015-06-29 08:08 UTC
Labels: duplicate
