### ISSUE TITLE
Delivery Address Not Updated...

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#532] opened 2015-05-18 13:57 UTC
Under very specific scenarios the delivery address array does not get updated correctly. This is especially painful when the setting "Allow delivery to non-invoice address" is disabled.

I've observed the behaviour by outputting the $basket variable via a shipping module (Since I was debugging a shipping thing anyway!)

1) Register as a customer and define your default delivery & billing address.

2) Add an item to your cart and proceed to the checkout

3) Navigate to "Your Profile" and into the address book. Add a new address, check the boxes to make it your default delivery and shipping address. Save and go back to the checkout.

4) The new billing address is correctly displayed, but the delivery address in the basket array has not been updated and still holds the old address. This is then passed to the shipping modules and the wrong prices can be returned based on quotes from the old address.

This also causes issues with shipping if the customer directly adds their address via the address book instead of via the checkout page as it still has the store address as the delivery address

**Comment by SemperFiWS** [comment] 2015-05-26 16:01
Could the profile edit function be altered to check the basket array then update it accordingly?

**Comment by abrookbanks** [comment] 2015-05-28 11:06
MASSIVE improvement here. New function to deal with formatting of address instead of all the crap repetitive code making too much room for error.

**Comment by Noodleyman** [comment] 2015-09-23 07:31
I have re-tested this issue in 607 and it still exists.

You can see the issue if you var_dump the $basket_data variable within cart.class.php before $shipping  = new $module['folder']($basket_data);

Adding a new delivery address at the checkout page does not change the delivery address in the basket array which can cause issues with shipping modules returning invalid results.

**Comment by Noodleyman** [comment] 2015-09-23 07:44
Thank you for re-opening Al :+1:

**Comment by abrookbanks** [comment] 2015-09-25 10:58
Hi Alec where is ```$shipping = new $module'folder';```?

**Comment by abrookbanks** [comment] 2015-09-25 11:00
Hi Alec, I can't find ```$shipping = new $module['folder']($basket_data);``` anywhere?

**Comment by Noodleyman** [comment] 2015-09-25 11:00
that would be helpful to list wouldn't it...

$shipping  = new $module['folder']($basket_data)

cart.class.php
around line 965 within the loadShippingModules function

**Comment by abrookbanks** [comment] 2015-09-25 11:06
got it now.. I did a global search and it didn't come up. Thanks.

**Comment by abrookbanks** [comment] 2015-09-25 11:09
This fix takes the current basket data rather than potentially old data in the cart class.

**Comment by abrookbanks** [comment] 2015-09-25 11:11
I'm trigger close happy. Please let me know if this is still and issue and I'll reopen.

**Comment by bhsmither** [comment] 2015-10-11 03:48
I cannot accept the assertion that using `$GLOBALS['cart']` *inside the Cart class* is in any way different than using `$this` inside the class.

**Comment by abrookbanks** [comment] 2015-12-30 16:27
> I cannot accept the assertion that using $GLOBALS['cart'] inside the Cart class is in any way different than using $this inside the class.

I completely agree. I must have been snoozing at the time.

**Comment by Noodleyman** [comment] 2016-09-16 12:19
@abrookbanks 
There are still cases where this issue exists. I experienced it today on a 6.0.12 store. I was trying to figure out why a shipping module was offering free shipping when the rules suggest it should only apply to specific destination countries. Turns out, the contents of the "delivery_address" array did not match the billing address array information. The store only allows shipping/delivery to the same address.

In my specific case, I replicated by logging in as the customer via the admin area. The delivery address data was for a totally different customer which should never happen.

I've not yet isolated the root cause, but this reported problem is still an issue in the most recent versions. In my customers store it's directly related to several incorrect shipping charges. Can this be reopened and investigated again?

**Comment by abrookbanks** [comment] 2016-09-16 12:40
So I'd imagine the customer created their addressed before the stores settings where changed? Even so it should just take the billing address.

**Comment by Noodleyman** [comment] 2016-09-16 12:43
The store settings hadn't changed, it's had that config for about 18 months. It's as if the delivery address isn't being repopulated from the billing address under some scenarios. 

You can replicate the issue by logging in as multiple customers using the "Login as customer" feature and going to the checkout. The addresses for customers are being mixed up. I think at some point, "somewhere" the delivery_address should be repopulated, perhaps even on the act of loading the checkout page. It should solve the issue. 

In this case, as a quick work around I've updated the shipping module to use the billing address instead as that is updated correctly. Since the store only allows shipping to the billing address, it's a valid work around in this case.

**Comment by abrookbanks** [comment] 2017-02-09 15:38
> In my specific case, I replicated by logging in as the customer via the admin area. The delivery address data was for a totally different customer which should never happen.

This is a database fault caused by redundant addresses in the database and a CubeCart_customer table with a cardinality lower than the max customer_id assigned to redundant order. 

Essentially new customers registers and get assigned addresses that already exist in the database. 

I have seen this before and it was fixed by increasing the value of the next auto increment on the customers table to be higher than the maximum customer_id in the CubeCart_addresses table. 

Closing as this is not a bug in a fresh v6 install but an issue caused by corrupt database.

**Closed by abrookbanks** 2017-02-09 15:38 UTC
Labels: bug
