### ISSUE TITLE
Upgrade from 4.4.7 > 6.0.11, images with capitlised extensions are changed to lowercase

### ISSUE THREAD

**Issue by cb2004** [cubecart/v6#1102] opened 2016-05-23 16:23 UTC
I have a store running 4.4.7 and we are upgrading to 6.0.11. Lets say I have a product on the old site that uses image-01.JPG as the uploaded image, but also image-01.jpg was in the filesystem, on upgrade the product would end up having the lowercase file extension as the main image.

**Comment by Noodleyman** [comment] 2016-05-25 16:46
if the image is in lower case on the file system, then it is correct that the lower case extension be in CubeCart. 

The file manager will scan the images in the /images/source directory and rebuild the information in the filemanger table.

When you say "uses image" how do you mean?

**Comment by cb2004** [comment] 2016-05-25 17:09
So on CubeCart 4.4.7 a product has the image selected as image-01.JPG. Also in the file system is image-01.jpg but this is not a selected image. When the upgrade to 6.0.11 is done, the selected image is image-01.jpg but it should be image-01.JPG

**Comment by abrookbanks** [comment] 2016-06-01 11:08
It tries to fix "bad" image paths. 

e.g. image (1).JPG

It will replace special characters like whitespace and brackets to underscores. I'm not sure it should be case sensitive.

**Comment by cb2004** [comment] 2016-06-01 11:11
No it shouldnt be case sensitive, but I can confirm there are no special characters, it is literally:

example.JPG

Being set as:

example.jpg

**Comment by abrookbanks** [comment] 2016-06-01 11:12
.. the regex has the "i" modifier to make it case insensitive.. 
```
$regex_slash_keep = '#[^\w\.\-\_\/]#i';
$regex_slash_remove = '#[^\w\.\-\_]#i';
```

Trying to figure out where it is made lowercase..

**Comment by Noodleyman** [comment] 2016-06-01 13:18
random thought... DB set to case sensitive, then CI?

**Comment by cb2004** [comment] 2016-06-01 14:22
I dont think the DB is set to case sensitive no, and encoding is utf8_general_ci. I have attached an image, you will see the lowercase is selected after upgrade but the uppercase is the selected image in 4.4.7. 

![untitled-1](https://cloud.githubusercontent.com/assets/6205980/15713002/8141612e-280c-11e6-8649-ac6e98b51147.png)

**Comment by abrookbanks** [comment] 2016-06-14 12:38
I setup a v4 store with an images named earrings1482.JPG before and after upgrade it remained the same. 

I can't reproduce this. I have closed this for now but please let me know if you have any further info or if it happens again. If you have a backup of this store prior to upgrade I'd love to try and see if I can reproduce it.

**Comment by abrookbanks** [comment] 2016-06-14 12:40
Just FYI I have made some changes to improve reliability on upgrade image association from v3 and v4 to v6. 

https://github.com/cubecart/v6/commit/4453645782af53a45286d58d24ace0fe2e9a5592

**Comment by cb2004** [comment] 2016-06-14 12:40
But did you also have an image with the filename earrings1482.jpg (lowercase extension)? Nothing is getting renamed, its just selecting the lowercase extension as the main image if the uppercase extension is selected in V4.

**Comment by abrookbanks** [comment] 2016-06-14 12:42
Oh I see! This certainly relates to the database then as it is case insensitive.

**Comment by abrookbanks** [comment] 2016-06-14 12:47
I think the only way this can be achieved is by changing the columns to be VARBINARY instead of VARCHAR. I'm not overly keen to do that. 

I can't see this being a common problem.

**Comment by cb2004** [comment] 2016-06-14 12:51
I can select the uppercase extension images as main after upgrading, but I will have to do this 300+ times for the site we are nearly launching. Anything you can recommend to get it working and then switch it back to default CubeCart setup?

**Comment by abrookbanks** [comment] 2016-06-14 12:55
You could try adding an SQL command in the setup/db/upgrade/5.0.0b1.sql file to alter the filename column to be VARBINARY.

Then the code in setup/scripts/5.0.b1.php will select the correct file. 

```if ($reference = $db->select('CubeCart_filemanager', 'file_id', $where)) {```

**Comment by abrookbanks** [comment] 2016-06-14 12:56
I'm going to close this as it is so specific to this store.

**Closed by abrookbanks** 2016-06-14 12:56 UTC
Labels: invalid / unreproducible

**Comment by cb2004** [comment] 2016-06-14 13:18
OK I will look into changing it. Agreed it is very specific, but I am struggling to see how I can upload an image to a product with UPPERCASE.JPG and that is fine but this is not allowed on upgrade.

**Comment by Noodleyman** [comment] 2016-06-14 14:11
counter question. 

why do you have duplicate file names with variying cases?

you should split these out into sub directories or use unique file names.

**Comment by cb2004** [comment] 2016-06-14 14:25
This was handed over to the client years ago so no idea why there are varying cases.

I think folder creation for image management would be a great idea and I would recommend that to my client, however this needs to be in the product section as well as the file manager in my opinion, otherwise they will be lazy and not use the file manager, then go to add the product.

**Comment by Noodleyman** [comment] 2016-06-14 14:34
that sounds like a good enhancement request, but it would require it's own ticket. It's something that bothered me for a while as well :)
