### ISSUE TITLE
Bug when I use "add to basket" using Responsive Design (tested with chrome dev-tools Galaxy S5) 

### ISSUE THREAD

**Issue by theoneandonly-vector** [cubecart/v6#1925] opened 2018-04-03 10:01 UTC
I'm using the latest v6 from github (cloned it yesterday)
Similar bug like https://github.com/cubecart/v6/issues/1900
There aren't multiple sites, which 
sometimes (it only happens sometimes!, not every single time BUT it happens much more often when I select "low-end-mobile" (screenshot)
![image](https://user-images.githubusercontent.com/10380051/38243072-b7e8ad64-3736-11e8-8015-61925831ea54.png)
) the item disappears when I go to basket.
tested with chrome dev-tools Galaxy S5

**Comment by abrookbanks** [comment] 2018-04-03 10:09
I can't see anything wrong in that screenshot? What exactly is the problem?

Provide as much info as possible.

**Comment by theoneandonly-vector** [comment] 2018-04-03 10:11
when I add an item and then go to "show basket" it's gone.

**Comment by theoneandonly-vector** [comment] 2018-04-03 10:13
1.
![image](https://user-images.githubusercontent.com/10380051/38243578-40249566-3738-11e8-9c4a-c2017bc398aa.png)
2.
![image](https://user-images.githubusercontent.com/10380051/38243592-4d0763d0-3738-11e8-9a65-b9d13d876bc6.png)
3.
![image](https://user-images.githubusercontent.com/10380051/38243613-5e9ba412-3738-11e8-8f40-6cc52523d492.png)

**Comment by abrookbanks** [comment] 2018-04-03 10:16
Can you reproduce this on our demo store? I can't. Please make sure server side/proxy caching is disabled and use mod_expires to make sure HTML is not cached past 1 second.

https://demo.cubecart.com/cc6/

![screen shot 2018-04-03 at 11 17 04](https://user-images.githubusercontent.com/4520803/38243800-94e75a14-3730-11e8-8b8b-6b0e694c885d.png)

**Comment by theoneandonly-vector** [comment] 2018-04-03 10:21
the demo site still has this bug: https://github.com/cubecart/v6/issues/1900

**Comment by abrookbanks** [comment] 2018-04-03 10:24
How do I reproduce it? I have tried with exactly the same Chrome dev tools settings (Galaxy S5, "low-end-mobile").

**Comment by theoneandonly-vector** [comment] 2018-04-03 10:37
hm.. somehow d'couldn't made it right now through chrome, but this is a video (just recorded it) using oneplus 5:
https://youtu.be/9-5aTr_OcY8

**Comment by abrookbanks** [comment] 2018-04-03 10:46
Thanks for the movie. I'll try to reproduce it.

**Comment by theoneandonly-vector** [comment] 2018-04-03 15:16
do you know a way to create a profile from a specific smartphone whoch could then be used to test it in chrome?, like by browsing to a website?

**Comment by abrookbanks** [comment] 2018-04-10 14:11
I just can't reproduce this.

**Comment by abrookbanks** [comment] 2018-04-10 14:11
Closing until I can get more specific steps to reproduce.

**Closed as completed by abrookbanks** 2018-04-10 14:11 UTC
Labels: invalid
