### ISSUE TITLE
Fetch Rates does not work after upgrade from 6.2.0 -> 6.2.2

### ISSUE THREAD

**Issue by demand73** [cubecart/v6#2192] opened 2018-09-24 23:38 UTC
After upgrading from 6.2.0 -> 6.2.2 Fetch Rates does not work any more and worked before the upgrade.

I just get a white page after pressing the button and my error log says:
"PHP Warning:  SimpleXMLElement::__construct()"

Has anything changed with Fetch Rates?

Regards
Krister

**Comment by demand73** [comment] 2018-09-24 23:49
Sorry i did not check closed issues before writing this. Did find issue 2165 that solves this problem.

**Comment by abrookbanks** [comment] 2018-09-25 08:44
Duplicate of #2165

**Closed as completed by abrookbanks** 2018-09-25 08:44 UTC
Labels: duplicate

**Comment by abrookbanks** [comment] 2019-01-24 08:20
Ignore "Fixed file permission logic" accidental typo in commit.
