### ISSUE TITLE
AdWords problems after upgrade to 6.0.10

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1003] opened 2016-02-05 19:23 UTC
After an upgrade from 6.0.8 to 6.0.10, the AdWords plugin causes a white screen when going to homepage.  No errors recorded in error logs but disabling that single plugin solves the problem

**Comment by bhsmither** [comment] 2016-02-06 00:31
White screen usually happens when Smarty does not like something in the template. Rarely does anything get logged when that happens.

But this is a plugin?

**Comment by abrookbanks** [comment] 2016-02-08 09:32
Hmmm the issue is to do with Smarty->registerFilter i think.

**Comment by abrookbanks** [comment] 2016-09-20 15:08
This was fixed with GoogleAdwords-1.0.1.zip
https://www.cubecart.com/extensions/plugins/google-adwords-tracker

**Closed** 2016-09-21 12:29 UTC
Labels: bug
