### ISSUE TITLE
Promotional codes dont work correctly when including / excluding products

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1707] opened 2017-08-17 10:52 UTC
Set up a promotional code to give say 5% discount, then add a list of products that should be excluded from the promotion.  The 5% discount is correctly applied when there are only a few products in the excluded list (I haven't tested but expect the same problem happens when using included only product lists) but if you have a lot of products (our client for example has 120 products in the excluded list that are already discounted and which they dont want to offer a further discount on) then it calculates the 5% on every item in the cart ignoring the exclusion list

**Comment by abrookbanks** [comment] 2017-09-27 11:00
I've spent the last couple of hours on this but I can't reproduce it. Can you ask the merchant to send a support ticket?

![screen shot 2017-09-27 at 11 58 16](https://user-images.githubusercontent.com/4520803/30910149-7ef4eb2a-a37b-11e7-9e39-02559b509191.png)

![admin control panel](https://user-images.githubusercontent.com/4520803/30910158-8386071e-a37b-11e7-8bfc-1926aa90a86e.png)

**Comment by abrookbanks** [comment] 2017-09-27 12:26
Really there should be a flat rule to ignore sale items.

**Comment by abrookbanks** [comment] 2017-09-27 15:59
Closing for now. I will reopen if you think I need to try something else or if you spot some other variable. I'm sorry the user has this issue. Happy to look via support if they need help still.

**Closed by abrookbanks** 2017-09-27 15:59 UTC
Labels: invalid / unreproducible
