### ISSUE TITLE
Admin Add Customer Bug - Address Check Boxes

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#182] opened 2015-02-04 22:05 UTC
Here is how to replicate
- log into admin
- click add customer (admin.php?_g=customers&action=add)
- fill out all fields on the general tab
- click the addresses tab (admin.php?_g=customers&action=add#address)
- click add new address link (admin.php?_g=customers&action=add#)
- fill out all the address fields
- try to tick the billing address checkbox (you can't)
- try to tick the default checkbox (you can't)
- click add
- click save
- click on edit for the customer just created
- click on addresses tab
- click on the edit link for address added above
- you will see both checkboxes are now ticked

Additional Note #1 
The layout of the add address (in the lightbox) is a complete mess)

Additional Note #2
Back in CC5, when you get to the tick stage above, you can check the boxes but your choices are not saved.
Only if you go back in and edit them, the choices are respected.

**Comment by abrookbanks** [comment] 2015-02-05 11:30
Duplicate of #34

From my testing this works fine. Are you using a recent Beta build?

**Comment by abrookbanks** [comment] 2015-02-05 13:03
Closing for now but can reopen if needed. The checkboxes work for me.

**Closed by abrookbanks** 2015-02-05 13:03 UTC
Labels: duplicate
