### ISSUE TITLE
Database Backup May Not Complete

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1460] opened 2017-01-19 03:53 UTC
In Database->sqldumptable(), after a *page* (of 50 rows) is written to the backup file, `$page` is incremented and this function is recursed into.

Zend Engine enhancements (examples are Zend Optimizer, Zend Debugger, Turck MM Cache, APC, Xdebug and ionCube loader) often modify engine behavior.

By default, Xdebug has a maximum function nesting level of 100 -- probably for aborting some types of infinite loops. When CubeCart is installed in a development environment, Xdebug and other environmental tweaks are necessary.

So, in this environment, a table of 5000+ records will hit this limit and cause a PHP Fatal error.

Even so, in a regular production environment, recursion when you don't know how deep you will go is not a good idea.

Suggest abandoning the recursion approach and use a `do/while/until` loop structure wholly contained within the function.

**Comment by abrookbanks** [comment] 2017-01-19 10:28
We are stumped both ways. do/while/until will only work for small databases as the memory limit will exceed quickly. The recursion approach won't cause memory exhaustion.

**Comment by bhsmither** [comment] 2017-01-19 15:57
Please give your reasoning on why recursion was chosen. If the intent was to prevent memory exhaustion, then I say for every level getting recursed into, the "stack" gets deeper. (How many bytes comprise a stacked element? I don't know.)

But the other thing I noticed about the process is that the file being written to is opened and closed for every iteration. If THAT was the idea on how to save memory (by not loading the entire table in memory to then be written out whole), then within the loop, the file could be opened and closed the same way as the recursion method.

If the idea was to get 50 records at a time (and writing that out to a file, with open/close or keeping it open regardless) to use as little memory as practical, then that approach should be sufficient.

I am befuddled how recursion is believed to be the key to the solution where a while loop that does the same thing won't work.

**Comment by abrookbanks** [comment] 2017-01-19 16:09
The problem is a loop without recursion on a large table will fail with memory error. Maybe the recursion limit needs to be increased.

I'll perform some more tests.

**Comment by bhsmither** [comment] 2017-01-19 17:22
It's just that I am not seeing **at what point in the loop** (with the complete machinations involved) where any memory being used to hold a recordset is not being released, any more or less than a recursion method.

How does recursion save memory?

**Comment by abrookbanks** [comment] 2017-01-19 19:11
Attempting to read a large table into PHP memory all at once will cause a memory crash.

**Comment by abrookbanks** [comment] 2017-01-19 19:13
... even before getting to looping it out to file.

**Comment by abrookbanks** [comment] 2017-01-19 19:14
... let alone time out.

Sorry for multiple comments on at home on my phone enjoying a beer.

**Comment by abrookbanks** [comment] 2017-01-19 19:20
Maybe I've over thought this. Happy to revaluate.

**Comment by bhsmither** [comment] 2017-01-19 19:31
Timing out will be hard to quash without using httpredir back to the process (maintain a session state?). Good way to provide a status indicator!

Here's my code (untested):
```
  public function sqldumptable($file_name, $tableData, $dropTables = false, $incStructure = true, $incRows = true, $maxRows = 50, $page = 1) { dbgClue(__METHOD__);
    
    $fp = fopen($file_name, 'a+');
    $tabledump = '';
    if ($dropTables && $page===1) {
      fwrite($fp, "-- --------------------------------------------------------\n\nDROP TABLE IF EXISTS `".$tableData['Name']."`; #EOQ\n\n");
    }
    if ($incStructure && $page===1) {
      $schema = $this->query('SHOW CREATE TABLE `'.$tableData['Name'].'`');
      fwrite($fp, "-- --------------------------------------------------------\n\n-- \n-- Table structure for table `".$tableData['Name']."`\n--\n\n");
      fwrite($fp, $schema[0]['Create Table']); 
      fwrite($fp, "; #EOQ\n\n");
      fclose($fp);
    }
    if ($incRows) {

      $fp = fopen($file_name, 'a+');
      while(true) {

        ## get data chunk
        $limit = $page>0 ? "LIMIT $maxRows OFFSET ".($page - 1) * $maxRows : "LIMIT $maxRows";

        $this->_query = "SELECT * FROM ".$tableData['Name']." ".$limit;
        $this->_execute(false);
      
        if($this->_result) {

          if($page===1) {
            fwrite($fp, "--\n-- Dumping data for table `".$tableData['Name']."`\n--\n\n");
          }
          foreach($this->_result as $row) {
            fwrite($fp, "INSERT INTO `".$tableData['Name']."` VALUES(");
            ## get each field's data
            $comma = false;
            foreach($row as $key => $value) {
              fwrite($fp, $comma ? ', ' : '');
              fwrite($fp, $this->sqlSafe($value, true));
              $comma = true;
            }
            fwrite($fp, "); #EOQ\n");
          }
          $page++;
        } // WAS: $this->sqldumptable($file_name, $tableData, $dropTables, $incStructure, $incRows, $maxRows, $page);
        else { break; }

      }
      if($page===1) { // WAS:  } elseif($page===1) {
        fwrite($fp, "-- Table `".$tableData['Name']."` has no data\n\n");
      }
      fclose($fp);
    }
    return false;
  }
```

**Comment by abrookbanks** [comment] 2017-02-01 14:27
Closing for now but will revaluate based on real world testing.

**Closed by abrookbanks** 2017-02-01 14:27 UTC
Labels: question
