### ISSUE TITLE
New System Errors after 6.0.9 install

### ISSUE THREAD

**Issue by svrabel** [cubecart/v6#969] opened 2016-01-16 18:59 UTC
Today, 13:58	[Notice] /homexyz./public_html/store/admin/sources/settings.errorlog.inc.php:61 - Undefined variable: smarty_data
	Today, 13:58	[Notice] /home/xyz/public_html/store/admin/sources/maintenance.index.inc.php:551 - Undefined variable: existing_backups
	Today, 13:58	[Notice] /home/xyzl/public_html/store/classes/ajax.class.php:46 - Undefined index: function

**Comment by bhsmither** [comment] 2016-01-16 21:46
Duplicate of #965.

**Closed** 2016-01-18 17:10 UTC
Labels: duplicate
