### ISSUE TITLE
Hook Request - Documents

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#1015] opened 2016-02-17 20:34 UTC
File: /modules/plugins/hooks.xml
Find This:
```
 <hook trigger="class.gui.display_documents" deprecated="" />
```
Below That Add This:
```
 <hook trigger="class.gui.documents.list" deprecated="" />
```

File: /classes/gui.class.php
Find This:
```
		$GLOBALS['smarty']->assign('DOCUMENTS', $vars);
```
Below That Add This:
```
		$documents_list_hooks = array();
		foreach ($GLOBALS['hooks']->load('class.gui.documents.list') as $hook) include $hook;
		$GLOBALS['smarty']->assign('DOCUMENTS_LIST_HOOKS', $documents_list_hooks);
```

File: /skins/foundation/templates/box.documents.php
Find This:
```
         {if isset($CONTACT_URL)}
         <li><a href="{$CONTACT_URL}" title="{$LANG.documents.document_contact}">{$LANG.documents.document_contact}</a></li>
         {/if}
```
Below That Add This:
```
         {foreach from=$DOCUMENTS_LIST_HOOKS item=list_item}
         <li><a href="{$list_item.href}" title="{$list_item.title}">{$list_item.title}</a></li>
         {/foreach}
```

Allows appending URLS to the documents list, no skin edit required.

**Comment by briansandall** [comment] 2016-02-17 21:42
Wouldn't the following code using the existing class.gui.display_documents hook achieve the same result?
`$vars[] = 'http://mycustomurl.html'`

That should append the custom url(s) to the list of documents displayed in the store footer.

**Comment by SemperFiWS** [comment] 2016-02-23 17:39
Yes it absolutely can be done that way.
In addition to not requiring a skin edit, the code I suggested is consistent with similar code used for the session box and account page.

**Comment by briansandall** [comment] 2016-02-23 18:35
Forgive me for not understanding, but since you can already append links using the existing hook, what would be a use case for the proposed changes? It seems redundant.

**Comment by SemperFiWS** [comment] 2016-02-23 21:19
Session Box
/classes/gui.class.php
```
		$session_list_hooks = array();
		foreach ($GLOBALS['hooks']->load('class.gui.session.list') as $hook) include $hook;
		$GLOBALS['smarty']->assign('SESSION_LIST_HOOKS', $session_list_hooks);
```
/skins/foundation/templates/box.session.php
```
      {foreach from=$SESSION_LIST_HOOKS item=list_item}
      <li class="text-left"><a href="{$list_item.href}" title="{$list_item.title}">{$list_item.title}</a></li>
      {/foreach}
```

Account Page
/classes/cubecart.class.php
```
		$account_list_hooks = array();
		foreach ($GLOBALS['hooks']->load('class.cubecart.account.list') as $hook) include $hook;
		$GLOBALS['smarty']->assign('ACCOUNT_LIST_HOOKS', $account_list_hooks);
```
/skins/foundation/templates/content.account.php
```
   {foreach from=$ACCOUNT_LIST_HOOKS item=list_item}
   <li><a href="{$list_item.href}" title="{$list_item.title}" class="button secondary expand nomarg">{if !empty($list_item.fa)}<i class="fa {$list_item.fa}"></i> {/if}{$list_item.title}</a></li>
   {/foreach}
```

Documents Box
/classes/gui.class.php
```
        $documents_list_hooks = array();
        foreach ($GLOBALS['hooks']->load('class.gui.documents.list') as $hook) include $hook;
        $GLOBALS['smarty']->assign('DOCUMENTS_LIST_HOOKS', $documents_list_hooks);
```
/skins/foundation/templates/box.documents.php
```
         {foreach from=$DOCUMENTS_LIST_HOOKS item=list_item}
         <li><a href="{$list_item.href}" title="{$list_item.title}">{$list_item.title}</a></li>
         {/foreach}
```

Consistent code structure for all 3 locations :)

**Comment by briansandall** [comment] 2016-02-23 21:57
That's true, however the session / account links are not stored in an array, so there was not any way to add links there without adding an empty array specifically for the hook, whereas there is already the $vars array storing the document links.

Perhaps it would be better to change it so the session and account links are stored in an array which the hook can modify, and add the 'Contact Us' link to the document array? Then they could all be handled consistently without adding a redundant hook.

I.e. for documents, change $vars to $document_list_hooks and pre-populate it with the existing document links plus the contact link, and keep the existing hook as is (or perhaps rename it).

E.g. for account:
```
$account_list_hooks = array(
    0 => array(
          'href' => $GLOBALS['storeURL'].'/index.php?_a=profile',
          'title' => $GLOBALS['language']->account['your_details'],
          'fa' => 'fa-user',
    ),
    1 => array(
          'href' => $GLOBALS['storeURL'].'/index.php?_a=vieworder',
          'title' => $GLOBALS['language']->account['your_orders'],
          'fa' => 'fa-truck',
    ),
    // etc.
);
foreach ($GLOBALS['hooks']->load('class.gui.session.list') as $hook) include $hook;
$GLOBALS['smarty']->assign('SESSION_LIST_HOOKS', $session_list_hooks);

// then in the template, simply remove all the hard-coded links - the ACCOUNT_LIST_HOOKS
// array now contains all of them plus any added by users via the hook
```
This would allow users to not only add links, but also to remove (don't offer downloads? no problem) or sort or anything else they can think of.

You seem to have lots of experience in the plugin / hook area, so what do you think of the above proposal? Personally, I'm more of a direct edit kind of guy, so this is mostly academic for me ;)

**Comment by abrookbanks** [comment] 2016-02-24 12:31
Duplicate of #1016

**Closed by abrookbanks** 2016-02-24 12:31 UTC
Labels: duplicate

**Comment by briansandall** [comment] 2016-02-24 17:38
@SemperFiWS Well I guess it's a moot point now, but I'd still like to hear what you think of my last suggestion. I think it would make those 3 hooks more flexible in addition to providing a more consistent code base.
