### ISSUE TITLE
It's possible to overwrite completed orders as a customer.

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1012] opened 2016-02-15 07:26 UTC
Tested and validated in a clean install of CubeCart 610 using the print order form module as the payment gateway.

It's possible under some scenarios for a customer to overwrite an existing order with a new order which eleminates the original order altogether from CubeCart.

Steps to reproduce.
1) Place an order as a customer, checkout and pay for the order. During the checkout / payment process use the back button. The order goes to "Processing" state.

2) As the admin, mark the order as Completed.

3) As a customer, place another order. The original order number is used and the completed order is replaced.

Although not something that happens often, this is something that I have seen happening on a live customer store. I noted the following.

If the order is in a "Pending" state and the customer tries to place a new order, the old order is updated with the new order details.

If the order is in a "Processing" state and the customer tries to place a new order a new order number is generated.

If the order is in a "Complete" state and the customer tries to place a new order the existing order number is updated and the old order details are lost.

There definately needs to be an enhancement here to prevent completed orders from being overwritten.

**Comment by abrookbanks** [comment] 2016-03-11 11:18
I can't reproduce this. If I click back from the print order form the basket is empty and the order status is pending.

**Comment by abrookbanks** [comment] 2016-03-11 11:36
Note to self: Try back from PayPal to cart.

**Comment by abrookbanks** [comment] 2016-03-11 14:36
Now CubeCart will check that the current order hasn't been paid for already and create a new order if stock change time is at "Pending" and browser back button has been used.

**Comment by Noodleyman** [comment] 2016-03-11 14:37
you sir... are a legend :+1:

**Comment by abrookbanks** [comment] 2016-03-11 14:37
Seems to work well. I have a client to test it on.

**Comment by abrookbanks** [comment] 2016-03-16 08:50
Closing due to positive feedback from client.

**Comment by Noodleyman** [comment] 2016-03-16 08:52
Yay, thank you Al.. I know this one was a pain to reproduce

**Comment by schulzie** [comment] 2016-03-16 08:59
Any change of getting installed on the user that first raised the issue? Only had another order today with the same issue.... Thanks to Noodleman and Al for fixing it!

**Comment by abrookbanks** [comment] 2016-03-16 09:00
Please send a tech support ticket and we can look into this for you.

**Comment by Noodleyman** [comment] 2016-03-29 09:52
Morning Al, need to re-open this one I am afraid. It's still happening in the latest version. See attached screen shots, both from the same order.

The order was placed and paid for (Pending -> Processing). The order was then completed (Processing --> Completed). 

A new order was placed later and overwrote the original order number. The order went from "Order Complete" to "Pending" and through it's normal order cycle. The customer checked out with a different payment method between orders if that is related?

![sc1](https://cloud.githubusercontent.com/assets/10614018/14104295/61af8c16-f59c-11e5-9608-db90abad42b6.PNG)
![sc2](https://cloud.githubusercontent.com/assets/10614018/14104298/6324eee2-f59c-11e5-8d9b-83989e90ab7e.PNG)

**Comment by abrookbanks** [comment] 2016-03-29 09:58
FFS :(

**Comment by mackecm2** [comment] 2016-04-27 15:11
We have seen a similar problem to this today - same scenario, different order statuses: 
![image](https://cloud.githubusercontent.com/assets/7928551/14857056/a88d9986-0c92-11e6-899c-4e65ab8ede2f.png)

**Comment by mackecm2** [comment] 2016-07-06 18:11
We've had this happen again with CCv6.0.12:
The customer is on a mobile, and (we think) he's hit the back button after the going into Paypal via the gateway. The order has gone from Pending to Processing and back to Pending again once he's hit the back button.
    
![ccv12](https://cloud.githubusercontent.com/assets/7928551/16629292/2e50f616-43ad-11e6-99de-4b09cf60ea82.JPG)

**Comment by Noodleyman** [comment] 2016-07-07 08:39
I think the changes to address this issue had been backed out of 6.0.12 as it was causing some other issues in 6.0.11. I suspect it's pending another review by CubeCart before attempting to resolve it again. (Just guessing, as I can't speak on behalf of CubeCart..) 

@abrookbanks , can you confirm please?

Thanks,

**Comment by keat63** [comment] 2016-07-20 10:38
We've seen this problem a few times recently.


This latest episode...
Customer placed an order on the 19th, which was processed and dispatched.

On the 20th we have a paypal payment for a different amount (showing the same order number), but  we have no record of the order details.

On the 20th yet another order (with the same order number), along with a Secpay payment to match.

I'm currently suspecting 3 orders utilising the same order ID, with order number 3 overwriting order number 2 (hence no record of)

Until fully clarified, it looks like the customer is using Chrome.

**Comment by Noodleyman** [comment] 2016-08-01 08:42
I've also had another customer of mine report the issue using CC 6.0.12, in 6.0.11 the customers were getting warnings during checkout when this condition existed, but it did prevent them from checking out. This issue urgently requires a fix as it has a real world financial impact on businesses.

**Comment by havenswift-hosting** [comment] 2016-08-23 13:08
We are also getting multiple reports of similar problems and it does seem to be tied to customers using the back button in their browser.  We have one customer in particular where problems are happening regularly but often result in duplicate orders but also have some other complications such as order totals being incorrect (also reported multiple times by others).

In one scenario we had the following sequence  with a store using 6.0.11 :  Customer placed an order with 30 plus items, went through to PayPal in order to pay but then didnt as they couldnt remember their password.  They came back to it several hours later that day and hit the back button and this automatically created a new order with exactly the same products but left the old order in the system.

One further complication is that this client reduces stock at Pending order stage and for one product there had been only one in stock and so was taken by the "original" pending order.  On the new order, the item line still showed but with no description but even worse, the value of the item was still showing against the item but was not included in the total !!  The original order had this item removed from the line items but even worse the amount was still included in the total !!

We have had verbal confirmation from another customer on the same site that going through to PayPal and then hitting the back button (in this case to check the delivery address entered which was different to what PayPal was showing for delivery) creates a duplicate order

I think this has been an issue for a long time as we have had multiple store owners reporting duplicate orders, orders not adding up and missing line items all of which are obviously major problems

**Comment by mackecm2** [comment] 2016-08-23 13:38
We had the same problem again a couple of days ago; thankfully however we don't seem suffer from duplicate orders being created:
![screenshot](https://cloud.githubusercontent.com/assets/7928551/17893864/29eaa678-693f-11e6-9dc0-a282f09b3eb6.png)

**Comment by abrookbanks** [comment] 2016-08-23 13:58
The next release adds a column here which shows if the order status was changed by staff, customer or the server (remote server call). This may help shed clues...

**Comment by havenswift-hosting** [comment] 2016-08-23 14:55
I think there are two slightly different issues here - although maybe caused by using the back button and / or invalid session management.

In the two cases that I highlighted in the last update, the customers had created the order, gone through to PayPal and hit the back button before completing payment and so the order never gets set to Processing and it is this process that I believe creates the second order.

Adding the column to show who / what changed the order status might be useful, although I think you will need to add more information for it to be really helpful and while it may help in the situation that is being reported by Mike and Alec, I dont think it will be much help at all in the situation I am reporting

**Comment by schulzie** [comment] 2016-08-23 18:44
Al,
As per Alec's previous response and from other customers of yours, please fix this issue rather than skipping around it. This issue has real impact for us end users, its a complete pain in the arse and embarrassing for us sellers when we have to chase up customers asking what they actually did order and try to work out the mess that cubecart has left us with. It is far from professional and gives our customers that lack of trust.

Frankly i find this extremely disappointing that no real fix has been made within 6 months of reporting for a bug that has been around since the late CC5 days. Yes the little column fix will prove that the customer is altering the orders after they have been placed by using the back button... but it wont resolve the issue that needs your immediate attention. We need a fix!

I apologize for being blunt, but as a long time cubecart supporter when issues like this aint fixed in a reasonable time, i get pretty upset. I am happy to chat to you via facebook or phone about it should you need more end user scenarios.

**Comment by abrookbanks** [comment] 2016-08-24 05:55
@schulzie I understand your disappointment but I can't fix something that I am not able to reproduce. Someone give me exact steps to reproduce this where the issue happens every time and we'll figure it out.

Right now this is extremely complicated and fluffy.

**Comment by abrookbanks** [comment] 2016-08-24 06:00
Please can you all confirm to me that all of you suffering prom this problem have stuck change time set to "Pending"?

Also can you confirm that the orders suffering this issue contain items that are low in stock or singular?

**Comment by abrookbanks** [comment] 2016-08-24 06:04
Just as a general heads up we are getting about 600 new stores a month. I manage this project alone and cant afford to hire staff. CubeCart is free and open source and 95% of my time is consumed supporting customers paying for our technical support plans. I'm sorry if this doesn't make you feel very special but I get to these issues as and when I can. We have very thin resources.

**Comment by abrookbanks** [comment] 2016-08-24 06:09
`Frankly i find this extremely disappointing that no real fix has been made within 6 months`

If you have a look through this issue you will see numerous proposed fixes. I have spent a huge amount of time on this already but regrettably none of the proposed fixes have worked out. This issue has simply not need overlooked and idle.

**Comment by schulzie** [comment] 2016-08-24 06:58
Al,
No need to get all cranky and upset about it, just pointing out when we (a real time end user) see on smaller non urgent issues get resolved here on github and yet this real world issue has been around for some time with no Cubecart staff response since April. I understand, yes we are all time poor, i get that. Yes, i agree you put in a lot of hard work to make the cubecart a great eCommerce platform that's why we purchased the cubecart package 11 years ago . Heck we're all trying to improve Cubecart for the better of all involved, and I'm not here to feel special.... just would like to see it resolved as currently its preventing me from upgrading to 6.0.12 and i know from experience there is nothing worse that looking like a fool in front of your customers from an error that is basically from them being tools and hitting the back button for whatever stupid reason they feel fit.

For us, we always run low stock levels as we have 100's if not 1000's of product lines, but as stated earlier on it more seems to be from customers (orders in all pending/ checkout / completed stages) clicking back on their browsers which for some reason is keeping their pre-saved cart. They make whatever change they want, then re-checkout again (using what ever payment method they so choose, as i have seen it with all types of payments) overwriting their previous order with the same order number. For me, i believe its happening more so from mobile devices v's pc users but we have also seen it from older browser versions. Alec maybe able to shed more technical light on it, but thats what we see at seller level and from simple feedback we have had from customers.

**Comment by Noodleyman** [comment] 2016-08-24 07:20
I've been able to reproduce this and I've a theory about what makes it happen in the real world..

Firstly, I've a CLEAN install of CubeCart 612, i've changed the settings:
Allow physical orders even if no shipping options are available = ON

I also installed the PayPal payment module and configured it for real world payments.

In my testing, I was logged into the store front in Chrome, and the admin area in FireFox, thus preventing any mixed session "stuff".

Add some random test products to your store, then purchase just 1 of them. Go via the checkout process and get redirected to PayPal. At this point, don't worry about making a payment. However, the order has been created and visible in the admin area in a "Pending" status. 

Simulate the IPN updating the order status to processing by manually setting the order status to Processing.

as the customer, use the back button to go back to the store, add some other items to your basket and checkout again.

The same order number is used again, the original order is overwritten and lost, even though it was in a processing status.

Using those steps, I can reproduce it every time.

**Comment by abrookbanks** [comment] 2016-08-24 08:55
Thanks Alec.

**Comment by havenswift-hosting** [comment] 2016-08-24 11:09
Al - the scenario I have outlined is reproducible as well and is even easier as doesnt even need a payment or the order changing to Processing.  We also have a very helpful (increasing frustrated though) store owner who is willing to help and I obviously have access to detailed server logs so happy to work with you to help get sorted.  Alec also has several client accounts on our servers so he may also be able to help.  Our client had one customer who managed to create 3 Pending and 1 Processing orders, 20 minutes apart yesterday !

**Comment by abrookbanks** [comment] 2016-08-24 11:14
This has slipped through the net a bit then. I spend pretty much all day on tech support and this has only come up a few times on rare occasions. As a result I haven't prioritized it.

I'll get back onto it when I can.

**Comment by abrookbanks** [comment] 2016-08-24 11:31
@havenswift-hosting Has your client come to us via support at all?

**Comment by havenswift-hosting** [comment] 2016-08-24 12:18
@abrookbanks No, we havent logged a support ticket for this client but can do if you like and it would help ?  Maybe it is a combination of factors or maybe more to do with the type of website and therefore the type of customers using it ?  This specific client is getting 1 or 2 instances per day although 4 orders is extreme even for them !

**Comment by abrookbanks** [comment] 2016-08-31 09:53
Guys, there is a line of code in the order class to retrieve existing line items prior to adding new lines when an order is updated. I noticed that this is cached! It shouldn't be and could be the simple problem to this headache. 

Can you make this code amendment https://github.com/cubecart/v6/commit/24edd1c5eb252d80d1406b717b7aa7b002a49240 and see if the issue can be reproduced?

**Comment by Noodleyman** [comment] 2016-08-31 10:16
Using the steps to reproduce that I added previously, and your code change the issue still exists. This did not resolve the issue.

**Comment by Noodleyman** [comment] 2016-09-07 13:06
For my steps to reproduce, this resolves the issue:
https://github.com/cubecart/v6/commit/36b55168f7f55331ecc6e62cd24dc49c0ad48e5f

It's a "potential" fix, but requires some more in depth testing. With that change, I was no longer able to break it!

**Comment by mackecm2** [comment] 2016-09-16 18:26
I've installed Noodleyman's fix on my client's store - let's see what happens.....

**Comment by Noodleyman** [comment] 2016-10-04 10:00
@mackecm2 , since you added the fix did you run into the issue again?

**Comment by mackecm2** [comment] 2016-10-16 00:54
Since applying the fix, we've had 211 orders. I've gone through the order history for all of them and cannot find any instances of the order slipping back from processing to pending.

However I have found three orders that look very much like duplicates, so I will check these with the client and get back with his response.

**Comment by mackecm2** [comment] 2016-11-07 16:04
I see this code made it into release 6.1.0.

**Comment by abrookbanks** [comment] 2017-02-07 12:05
From what I am reading from @mackecm2 it looks like this is fixed since 6.1.1. 

Closing but I will reopen if anyone can confirm that they are still encountering this issue from 6.1.4 (latest at time of writing).

**Closed by abrookbanks** 2017-02-07 12:05 UTC
Labels: bug

**Comment by mackecm2** [comment] 2017-02-07 15:50
I've just gone through over 400 orders that my client's store has had since 16 Oct 2016, and can't see any instance of this problem reocurring. I reckon it';s fixed.

**Comment by abrookbanks** [comment] 2017-02-07 15:51
Thanks so much for getting back to me.
