### ISSUE TITLE
Add search facility to images / image assignment 

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2599] opened 2020-09-10 15:02 UTC
Building on the fantastic improvements with the image gallery, what would also really help would be search functionality when in the images option and also within the product image assignment option to be able to look for and narrow down the list of images containing a word or phrase

**Comment by abrookbanks** [comment] 2020-09-11 14:53
Duplicate of https://github.com/cubecart/v6/issues/2599. I hadn't seen this.

**Closed as completed by abrookbanks** 2020-09-11 14:53 UTC
Labels: duplicate
