### ISSUE TITLE
Incremental Order Numbers not working

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#636] opened 2015-06-23 17:11 UTC
See feature request: https://features.cubecart.com/topic/incremental-order-numbers

I know that this says it is experimental but I believe it should be taken out until completed as it doesnt work correctly.

It is possible to place an order and the order numbering works OK, the order gets sent through to whichever gateway you want but returns with the old style order numbers and so order isnt updated from Pending to processing ; there is a mix of what order numbers have been used between the orders listing (incremental) and the transactions (old) and worse still the product code details seem to be lost from the order after payment - you can see an order with detail lines and prices but no product details

**Comment by abrookbanks** [comment] 2015-06-24 09:05
Thanks.

**Comment by abrookbanks** [comment] 2015-06-24 09:06
See commit b4e9ae49312ebb5dcd1d3a423649c862ffd31a4f

**Comment by Dirty-Butter** [comment] 2015-06-24 13:25
FYI - I have been using Chuggyskin's Incremental Order Numbers mod for years very successfully. Perhaps you can work something out with him to make it stock??????

**Comment by NaturalSigns** [comment] 2016-02-20 21:51
Has this now been abandoned?.  Its a shame as in the UK you have to invoice with a sequential number (to my understanding, see HMRC guidelines [http://www.hmrc.gov.uk/manuals/vatrecmanual/vatrec5020.htm] ). + sequential seems to be the logical approach for a clean store install.

**Comment by Dirty-Butter** [comment] 2016-02-21 14:25
I still use the v5 code from Chuggyskins (at some point modified by Bsmither). I cannot, however, merge the mod code with CC code anymore - I have to comment out the newer order number code sections in 6.0.10 to use the mod.

**Comment by Dirty-Butter** [comment] 2018-02-12 15:16
Referencing your last comment with images on #1867. I like the idea of keeping the randomized REFERENCE to the order, while the human (admin and customer) sees an incremental order number. I have a very low volume store, so my incremental modification based on ChuggySkins works well for me. I suspect a large volume store might run into problems with a true incremental order number system that is easily human read. Good luck with this!!!

**Comment by abrookbanks** [comment] 2018-02-12 15:21
Thanks. I think my new approach will work. I'm only making changes to the views and not any mechanics.

**Comment by Dirty-Butter** [comment] 2018-02-12 16:02
Sounds good! I would suggest that the admin be able to set the initial number of the sequence. For instance, my last order number was 2018-PC-4019. If I changed to your system right now, I would want the next order to be 4020. (the year turns over automatically with Chuggyskins, and I set the PC for plushcatalog - I also have the choice of starting numbering over for the new year or continuing with the sequence. I chose continuing.

**Comment by abrookbanks** [comment] 2018-02-12 16:56
Duplicate of #193

**Comment by PloughGuy** [comment] 2018-02-13 03:58
I have been working on a version of this recently.  (I will now stop).
For maximum flexibility, and to knock over other development requests in the queue, I was planning to allow the user to specify some decorations:

- A static prefix stored as a global that, if defined, is applied before the number (this is a development request.)
- A static suffix stored as a global that, if defined, is applied after the number. (Not requested, if we are doing a prefix, we should do a suffix for symmetry, if nothing else.)
- a number of digits and a leading filler (zeros, for example, or unicorn emojis.)
- a next order number initialization value.  This would allow a store to seed from order numbers other than 1 or to prefix the order number with the year (201800000001) or to migrate from some other platform with an existing order book.  It should be possible to update this at any time.

**Benefits** of prefix and suffix: Useful for people with multiple stores that want to transfer transactions to a central accounting system.
**Benefit** of fixed length numbers - predictable formatting.
**Benefit** of starting with any number - new number range for each year, (e.g. 1000000 this year, 2000000 next year.)  - seeding 000132000 disguises that your store opened yesterday - makes it easy to move into CC from some other store with order number continuity.

If this was implemented using hooks, alternate order numbering schemes can be implemented as required.  The Elboonian digits-in-reverse-order requirement, for example, can be met with relataive ease.

**An Implementation Test**
Finally, I will share some SQL.  This is the core of my solution.  You are all smart folk, and I am sure you have already thought of this.  However, I have heard rumblings in the ethers that a database-resident solution will impose performance problems.  I have tested this, and it works a treat, is very fast and fully atomic.  There are performance numbers below, and scripts to help you confirm it.

// Read the current value to an SQL variable, and add 1 to it for next time.  This operation is atomic.
// The table always contains the next order number.
$mysqli->query("UPDATE next_order_number SET next_order_number = (@order_number := next_order_number) + 1 WHERE number_name = 'next_order_number'");

// Extract the SQL variable, which is local to this session.  
$result = $mysqli->query("SELECT @order_number;");
$row = $result->fetch_assoc();
$order_number = $row['@order_number'];

// Use it.
printf("<br/>next order number is %d",$order_number)

**Performance Tests**
Running it at the command line level from a shell script, I get 10,000 numbers in just over three seconds, for better than 3000 order numbers per second, atomically sourced from an innodb table.
-------------------------------8<-------------------------------
RussMBP17:test_sequential_orders russ$ time ./runem.sh 1
threads is  1
Localhost via UNIX socket
Running 10000 iterations
next order number is 119142

real	0m3.076s
user	0m0.300s
sys	0m0.359s
RussMBP17:test_sequential_orders russ$ 
-------------------------------8<-------------------------------
Note the hostname - this is running under OS X on a 2012 MacBook Pro 17", which I know you all covet.

- OS X 10.13.3
- 4 cores - so 8 processors with hyperthreading
- 16 GB RAM

Lets scale it up:  Eight parallel threads.
-------------------------------8<-------------------------------
RussMBP17:test_sequential_orders russ$ time ./runem.sh 8
threads is  8
threads is  7
threads is  6
threads is  5
threads is  4
threads is  3
threads is  2
threads is  1
Localhost via UNIX socket
Running 10000 iterations
Localhost via UNIX socket
Running 10000 iterations
Localhost via UNIX socket
Running 10000 iterations
Localhost via UNIX socket
Running 10000 iterations
Localhost via UNIX socket
Running 10000 iterations
Localhost via UNIX socket
Running 10000 iterations
Localhost via UNIX socket
Running 10000 iterations
Localhost via UNIX socket
Running 10000 iterations
next order number is 109021
next order number is 109056
next order number is 109089
next order number is 109102
next order number is 109119
next order number is 109135
next order number is 109140
next order number is 109142

real	0m12.716s
user	0m3.206s
sys	0m3.447s
-------------------------------8<-------------------------------
We get 80,000 sequential order numbers from 8 threads in under 13 seconds or 6,153 per second.  CPU utilization is about 40%,.

Ramping it up to 32 concurrent threads for 320,000 order numbers, I get: 
-------------------------------8<-------------------------------
real	0m12.416s
user	0m3.156s
sys	0m3.512s
-------------------------------8<-------------------------------
This gives 26,000 order numbers per second. The time improves, presumably, because the PHP and MySQL initializations are amortised over a much larger sample.  Once again, CPU load peaked at 40%, presumably limited by the speed of the SSD.

I expect the load to connect to the database, save the order_summary and order_inventory rows, and update stock levels for the order would well eclipse this, so the cost of managing sequential order numbers in a database table will not impose an onerous load, even for very-high-throughput stores.

Conclusion: We have nothing to fear from storing the next available number in a database table like grown-ups should, and using appropriate SQL to retrieve it atomically.

If someone has a more modern bit of hardware to run it on (2015, perhaps?) then the numbers would be interesting.  Still not buying a new Mac until this one dies, my spare dies, and no more 17" MBPs are available on eBay.

The scripts are uploaded so you can play with it yourself.  Remove the .txt from the end.  runem,sh takes a single parameter which is the number of threads.  The php program contains a constant which sets the number of iterations.

A rudimentary check for duplicates is to confirm that the largest reported number of a run is appropriately larger than the result at the start.

[runem.sh.txt]
(https://github.com/cubecart/v6/files/1718525/runem.sh.txt)
[test_sequential_orders.php.txt](https://github.com/cubecart/v6/files/1718526/test_sequential_orders.php.txt)

The table was created as follows:
-------------------------------8<-------------------------------
CREATE TABLE `next_order_number` (
 `number_id` int(10) NOT NULL AUTO_INCREMENT COMMENT 'Primary Key - in case we need more numbers later',
 `number_name` text COLLATE utf8_unicode_ci NOT NULL COMMENT 'Next order''s order number',
 `next_order_number` int(10) NOT NULL,
 PRIMARY KEY (`number_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
-------------------------------8<-------------------------------

**Comment by PloughGuy** [comment] 2018-02-13 04:30
I believe Amazon uses those crazy order numbers because they have vast numbers of loosely coupled online stores for scalability and availability reasons.  Each store generates its own distinct and scrambled order numbers to prevent duplication, which include redundancy coding and other security features.

The system CubeCart currently uses has a 1/10000 chance of generating a duplicate for two orders arriving in the same second.  It is probably due to the relatively low traffic (two orders every hour would be good) that this has not caused problems already.

My preference would be to replace the existing order number solution completely with hooks and offer some choices.  I bet the uptake on the long order numbers would be very low...

**Comment by PloughGuy** [comment] 2018-02-13 04:36
Dirty-butter said

> I suspect a large volume store might run into problems with a true incremental order number system that is easily human read

I work with SAP systems that can process thousands of orders per second.  They use sequential order numbers (because its the law) and have no problems with it.  Each of the application servers in a system grabs a couple of hundred numbers from the database in a chunk and issues them until depleted, whereupon it grabs a bunch more.  I expect that unless Amazon itself wants to switch to CC, we will have no problems.

There is no reason to not go sequential except (in our case) effort.  I have demonstrated the throughput above on an ancient laptop.  Currently available XEON servers will do much better.

**Comment by abrookbanks** [comment] 2018-02-13 08:00
Thanks for the very detailed response. I've started building this from the CubeCart_order_summary auto incremented id column. I'll code it so this column can be changed. The easiest approach would be to create a new column with stored procedure to format itbased on the auto incremented id column.

E.G. {prefix}{leading zeros}{auto increment id + starting integer}{postfix}.

**Comment by PloughGuy** [comment] 2018-02-13 08:02
Al, you are a saint.  Provided the Elbonians don't come to us wanting the least significant digits on the left, it sounds like a solution.

Let me know if you need any other bright ideas.
Russ

**Comment by PloughGuy** [comment] 2018-02-13 08:06
Let me also say that using the order_id as the counter is a stroke of genius.  I almost can't think of any reason not to.

**Comment by abrookbanks** [comment] 2018-02-13 08:58
> Al, you are a saint.

I've not got it working fully yet. Hopefully I crack it this time. :)

> Let me also say that using the order_id as the counter is a stroke of genius. I almost can't think of any reason not to.

Yes it makes sense. The challenge will be running the stored procedure for some merchants. It might be a bit manual but lets see... Also some MySQL users don't have permission to create stored procedures. That's tough luck though.

**Comment by abrookbanks** [comment] 2018-02-13 09:18
I think we need to be using triggers and not stored procedures.

**Comment by abrookbanks** [comment] 2018-02-13 09:37
This works a dream for an extra column called `custom_id` to prefix ABC with two leading zeros. 

```
UPDATE `CubeCart_order_summary` SET `custom_id` = CONCAT('ABC', LPAD(`id`, 3, '0'));
DROP TRIGGER IF EXISTS `custom_oid`;
CREATE TRIGGER `custom_oid` BEFORE INSERT ON `CubeCart_order_summary` FOR EACH ROW SET NEW.custom_id = CONCAT('ABC', LPAD(LAST_INSERT_ID(), 3, '0'));
```

**Comment by havenswift-hosting** [comment] 2018-02-13 09:56
Al - great that you are making good headway with this.  Can you ensure that you document the usage of a trigger like this for users that dont have good MySQL usage.

As you said, some users may not have MySQL permissions to create triggers - they simply need to move to a good hosting company lol

**Comment by abrookbanks** [comment] 2018-02-13 09:57
Yes definitely. I'll write a support article. If I can manage it dynamically I'll write the code to do it automatically. Seems to be just a combination of four options. Prefix, postfix, leading zeros and starting point.

**Comment by havenswift-hosting** [comment] 2018-02-13 10:05
Even better - fields to enter as many of these as they want and you delete any existing trigger and create the new trigger on save !

**Comment by abrookbanks** [comment] 2018-02-13 10:10
Yes I can automate it all. Nice!

**Comment by PloughGuy** [comment] 2018-02-13 10:21
I need to clarify:
You are creating a new column to hold the new order ID field which will be statically and permanently assigned, not derived at read-time.
When a new row is inserted, the trigger will call a script to populate the field so no additional coding is required on insert.
Which raises a potential ongoing maintenance issue - the trigger is invisible and unexpected by most users 
Unless it is formally documented in the calling code.
Something should be provided to make it visible to the administrator for troubleshooting
When the administrator changes a setting (such as the next order number) you regenerate the trigger.
Is that the gist?

Presumably existing orders will retain their long order numbers.  Retroactive numbering is bound to upset the G-men.  So these will have to be populated into the new field for existing orders.

Ultimately, it should be possible for the existing long order numbers to become invisible if desired.
Russ

**Comment by abrookbanks** [comment] 2018-02-13 10:25
Yes I've considered all that. It will be automated with no need for maintenance.

**Comment by abrookbanks** [comment] 2018-02-13 17:27
Testing to be done but looking good so far. Movie here: http://static.cubecart.com/Flexible_Order_Numbers.mp4

**Comment by Dirty-Butter** [comment] 2018-02-13 19:42
Regarding your warning about an order number becoming truncated to 99. Would a seller be able to easily change to more leading zeroes some time in the future as the number of orders approaches the existing number of digit limits? Would that mess up past order numbers? Would admins need a warning that they are approaching "running out of human readable numbers"? Sorry for newbie questions, but a newbie thinks differently than someone who knows what they're doing LOL.

**Comment by abrookbanks** [comment] 2018-02-13 19:55
It's a good question. Do you think it should have a min value of say 5 or off?

It will also regenerate every order if it changes. Maybe it shouldn't.

**Comment by PloughGuy** [comment] 2018-02-13 20:34
Almost there...

From my personal point of view, this is already acceptable.

But...
**Issue 1 - Persistence**
From the video, it appears that the order numbers are derived at display time.  You change a setting and all existing numbers are changed. From an audit (and tax compliance) perspective, this is not correct.

I will have issued a tax-relevant invoice to a customer with a number on it that no longer matches my records.  The entire order number, with prefix, suffix, digits, and offset must be indelibly recorded by us in the form that was presented to the customer.  This will be a requirement for any VAT tax juristriction since this is the primary means of policing tax fraud.  And we don’t want to annoy a tax fraud detector.  Remember what happened to the other Al.  Mr Capone was eventually sent up the river for tax fraud.  Wouldn’t want to produce a product that aids and abets...

**Issue 2 - Captions in Settings**
From the Dept of Nitpicking Details, the bit at the end is a “suffix”.  “Postfix” is a mathematical notation.

The length caption should be “Incremental order number length with leading zeros”.  As written it says we will put 6 zeros in front of the number.  The note below might be clearer as ‘For order 1 a value of six will generate “000001”. Set to 0 to disable leading zeros.’  And put a “:” after “Caution:”

Other than that, it’s perfect.

**Comment by Dirty-Butter** [comment] 2018-02-13 20:37
I can't give advice for what's best for others. I can tell you what I did and let you learn from my thinking process. When I started, I started with 1000, because I didn't want my store to look brand new. I used the PC for plushcatalog because I use ES for the same setup on our estates store.  Our plushcatalog store is now in the 4000's, so it would be quite a while before I run out. I would not want old order numbers to be changed if I ever had to add more digits - way too confusing for me I think. And I DO like having the year of the order in the ID, but only if it changes automatically to the next year.
![sequentialsettings](https://user-images.githubusercontent.com/6146505/36172170-a62620f8-10ca-11e8-8c71-3415958fe644.png)

**Comment by PloughGuy** [comment] 2018-02-13 20:41
Butter’s remark  regarding running out of displayable numbers is a good one.   A few lines of code that issues a  warning that we are within three months running out of numbers based on current order generation rate would be useful.   I don’t think a minimum number is necessary  but a warning if it set to 5 or less might be appropriate.

**Comment by abrookbanks** [comment] 2018-02-13 20:45
Thanks both. I'll review these points and make some changes.

**Comment by PloughGuy** [comment] 2018-02-13 20:47
Butter,
Automating the year Is an interesting idea but we would need to put in a pattern rather than a number of digits for example a COBOL-style string like YYYY000000.

IMHO, That should be raised as a seperate request.

**Comment by abrookbanks** [comment] 2018-02-14 16:32
![screen shot 2018-02-14 at 16 31 18](https://user-images.githubusercontent.com/4520803/36215657-9cfbd77c-11a4-11e8-896a-9f1d093a70d2.png)

![screen shot 2018-02-14 at 16 31 11](https://user-images.githubusercontent.com/4520803/36215662-9fb0ed86-11a4-11e8-8939-f86fc3fa256a.png)

**Comment by Dirty-Butter** [comment] 2018-02-14 17:09
Looks great! Would it be possible to test out this code on 6.1.14?

**Comment by abrookbanks** [comment] 2018-02-14 17:40
Only by using the 6.2.0 branch of code but it's no way ready for production yet.

**Comment by Dirty-Butter** [comment] 2018-02-14 18:08
That's what I figured, but didn't hurt to ask. Very encouraged by your progress with this!

**Comment by abrookbanks** [comment] 2018-02-14 18:15
Thanks. We are really do a new version with features.

**Comment by PloughGuy** [comment] 2018-02-15 00:06
Looking fine, Al.

But of course...

**Proposal 1**
I think the "Starting Id" implies that this will be the first number.  Asking for the number before the first number is exposing the internals and it is likely to cause a mental hiccup in the user.  Asking for "First order number minus 1" makes it feel not quite finished.

It really should be "First order number".  If the customer enters 1, then we record 0 as the starting id.  If the user enters 1000, then the first order should be 1000, not 1001.

**Proposal 2**
The "Show me a sample" function is beautiful.  Nicely done.  Perhaps the function of the button should be "Save then Preview".  Otherwise the ergonomic flow is odd as in enter settings, go to the bottom of the form to Save, then go up to Preview.

**And a question**
Please confirm that we (as in "you") are now saving the fully formed order number in the order.  The "Force format to all past orders" implies this, but the giant purple snorkelwhacker in my anxiety closet needs to know for sure.

**Proposal 3**
Perhaps "Apply" rather than "Force".  Force sounds so brutal. 

**Deeply Wary Observation 1**
The "Force/Apply format to past orders" function represents a risk from a Tax Audit point of view because it potentially breaks the connection between vendor records and customer records.  Unless, of course, the original number is still available and visible.  I feel deeply nervous about the compliance implications of providing this capability - breaking the relationship between customer and vendor documents in a VAT jurisdiction is generally verboten.   And not all store-keepers will be aware of it.

A vendor that demonstrates a move from a non-compliant to a compliant stance is in a better position than one damages the audit trail...

**Comment by PloughGuy** [comment] 2018-02-15 00:14
And another thing:
If I have incremental order numbers in place, and I want to change the sequence for a new year, I should see the _current_ next order number when I come into settings, so I have a better chance of not causing a regression.

Do we have a unique index on the incremental order number field to prevent duplicates?  I presume a database error would be a better outcome than a big bunch of duplicated order numbers in the event of a cock-up.

**Comment by abrookbanks** [comment] 2018-02-15 11:29
@PloughGuy Thanks there is some really constructive stuff here. 

**Response to Proposal 1**
It won't be the first one as the previous orders won't be touched unless "Force format to all past orders" is checked. I'm struggling to come up with the best terminology for this. 

**Response to Proposal 2**
The button doesn't save anything. It can't submit the page and load an ajaxy modal. For this reason preview after save seems to fit best albeit a bit clunky from a UX point of view. Actually it could but being asynchronous it may or may not work reliably. 

**Response to "And a question"**
Yes the format is saved. It's not generated in real time each time. If the format changes past orders will keep their old format. Say it starts on traditional then to incrememtal with no formatting and then to say having a prefix. he history will remain unchanged unless told to update. It's stores in a new column called `custom_oid`. 

**Response to Proposal 3**
Agreed. I'll change to Apply which is a bit less fearsome. 

**Response to Deeply Wary Observation 1**
I agree. I can see merchants asking for this feature regardless however so I think we need it. A merchant needs to be aware about the legalities of their operations. I can see a scenario where a new merchants gets three sales then find this feature. They might want to change them all and reissue invoices.

**Comment by abrookbanks** [comment] 2018-02-15 11:30
@PloughGuy 
> Do we have a unique index on the incremental order number field to prevent duplicates?

Yes. It will always be unique as it is synced to the auto incremented `id` field.

**Comment by abrookbanks** [comment] 2018-02-15 11:37
@PloughGuy 

> It really should be "First order number". If the customer enters 1, then we record 0 as the starting id. If the user enters 1000, then the first order should be 1000, not 1001.

There is confusion here. If we already have 500 orders the system and the first order number is set to 1000. The next order will be 1501. Maybe this needs to be dynamic somehow and/or terminologically different.

**Comment by PloughGuy** [comment] 2018-02-15 20:15
As the people who increase the fibre content of their canned soups by adding asbestos can tell you, Truthful Labeling is not always the answer.

We really need this to be next order number.  I see the challenge.  The shop is humming along accepting orders, and the difference is potentially a moving target.  Plus we want to prevent duplicates.

To guide the user, we can report the most recent order number in the text if ION is already enabled.

To determine the correct difference, we can lock the order-summary table for a few microseconds to freeze the order-ids, calculate the increment, save it away, then unlock.  We are talking about a 1ms disruption. 

We can even insist that the administrator closes the shop to do this.  It is an uncommon event, after all.

Or are you wrestling with a different demon?

**Comment by abrookbanks** [comment] 2018-02-15 20:23
I don't we can have a starting order number less than the current maximum.

**Comment by PloughGuy** [comment] 2018-02-15 22:17
If I start with an offset of 1000 and I accept 1000 orders, then I try to set the offset to 1, what happens?

**Comment by abrookbanks** [comment] 2018-02-16 10:42
It's a good question and something I was thinking about too funnily enough. The next value will have to be the same or higher.

**Comment by PloughGuy** [comment] 2018-02-16 11:32
I really, really, really, really, really, really think the user should be dealing in absolute next_order_number numbers, because if we can't work it out, the user has no chance.

Really, really, really, really, really, really...

I desperately want this to be done right so it stays done and we never, ever have to come back to it again.

**Comment by abrookbanks** [comment] 2018-02-16 12:03
I would say that once the offset is made and orders come in it can't be changed. I can't see a way to make this absolute without taking logic away from SQL to PHP which in turn means a total rewrite now.

**Comment by PloughGuy** [comment] 2018-02-16 19:50
Fair enough.  The user can change the prefix, the suffix, the number of digits.  Should be enough.

From the initialisation POV, then, if the table has 10,000 orders in it and the offset is set to 0, the next order will be 10,001.  Is that correct?

**Comment by Dirty-Butter** [comment] 2018-02-16 20:58
The only reason I can see to make a future change after initially moving to sequential system would be if you realize you need more digits. It wouldn't make sense to me to try to change the starting number AGAIN - is that the issue you are trying to resolve?

**Comment by abrookbanks** [comment] 2018-02-19 11:53
> is that the issue you are trying to resolve

Yes partially.

**Comment by PloughGuy** [comment] 2018-02-20 02:58
Al,
I'm all fired up!  When do we get to see it.
You mentioned 6.2 - is there a release date scheduled?
Russ

**Comment by abrookbanks** [comment] 2018-02-20 09:00
> is there a release date scheduled

No I'm afraid not. I have extremely limited resources and the support help desk comes first over everything. A busy week on the help desk will mean no development. It's not very predictable aside from just after release which is always crazy busy. I don't have the revenue to hire dedicated staff.

**Comment by PloughGuy** [comment] 2018-02-20 20:28
Fair enough.  Are you thinking sooner rather than later?  As in before June or after-ish.

**Comment by abrookbanks** [comment] 2018-02-20 20:59
Before June unless we have any force majeure. I actually have a new born due in mid May so that might just about count as that. Haha. Also due to move into a new house at about the same time.

6.2 will only have a small amount of new features. Hopefully it will be ready in a few weeks.

**Comment by Dirty-Butter** [comment] 2018-02-20 22:19
YES, that counts as a "force majeure". Time to burn the midnight oil now and get the upgrade done well before birthday, or expect to delay it until at least end of July would be my guess. Congrats on the upcoming birth!!! :)

**Comment by abrookbanks** [comment] 2018-02-20 22:37
Thanks. It will be done before then. 😀

**Comment by PloughGuy** [comment] 2018-02-20 22:46
Cripes, Al, what are you doing to yourself?
Baby, schmaby - most people do that by accident.  My congrats are for finding the strength to move  house!  Get yourself some nice big removalists.  And whatever you do, don't watch "The Chain".  You have enough stress already.

**Comment by Dirty-Butter** [comment] 2018-02-21 00:10
Decided to install a 6.2.0 upgrade and see how this is working. Seems to be stable so far, but have not had time to really kick the tires. But I have a clarification - I would like to keep the yearly designation in orders, even if I have to do it manually.  Obviously I would prefer automatic, but I understand that's a minor issue.
So, I CAN change the prefix or suffix each year without any issue - just don't force old orders to change, right?

**Comment by PloughGuy** [comment] 2018-02-21 01:12
To do it right, you have to stay sober enough to take the store offline just as Old Lang Syne starts, change the prefix, wait for the clock to stop bonging then get it back online to meet the rush of drunken revellers who get an extra high from shopping.  A plug-in that automates this should be a nice little earner...

**Comment by Dirty-Butter** [comment] 2018-02-21 01:42
I already use a piece of php code that automatically changes the year to keep the copyright date correct. It would be nice if something similar could be used within the admin code here.

**Comment by PloughGuy** [comment] 2018-02-21 01:58
To do it properly, it has to be guaranteed correct.  That means take the store down at 11:59:50, change the global containing the prefix, then start it up at 00:01.  Should be possible to get that working in 10 months, you’d think.

**Comment by Dirty-Butter** [comment] 2018-02-21 01:59
I have 3 old style order numbers on our trial store. I did NOT set to force old orders to the new pattern. I set the Increment Increase to 4027 (my last actual order number on live store). I did not put anything in the suffix box, but prefer to maintain my current style completely if possible. I expected to see the Preview to show the next order number to be 2018-PC-4028. But it's Previewed as 2018-PC-4031. Is that what it should do? It looks to me like if I had done that on our live store the preview would have shown the next order number as being up in the 8,000's????

**Comment by PloughGuy** [comment] 2018-02-21 02:03
Of course, there is no need to do it at midnight, and no need to tak the store down.  The first order to notice that the prefix does not match the year can fix it before it saves the order and activates the trigger.  I expect the trigger itself would have to be updated, now I think about it.

**Comment by Dirty-Butter** [comment] 2018-02-21 02:06
LOL you'll have it all figured out before the night is over

**Comment by PloughGuy** [comment] 2018-02-21 02:12
Al has coded it so the new order number is the sum of the order_id and the offset that you enter.   Every new order changes the result, so...

To guarantee that you get continuity, you should take the store down, find the highest order_id with phpMyAdmin, calculate what you need to do to it to get your next number, and that gives the offset.  Set it, ensure your Bistromath is correct using the Preview function, then open the doors again.

It is entirely possible that in your case, it will be negative.  Al, are negs allowed?

**Comment by PloughGuy** [comment] 2018-02-21 02:13
It’s just after lunch here, so I’m firing on all 7 functioning cylinders.

**Comment by Dirty-Butter** [comment] 2018-02-21 02:17
Well that's where my non-code view of things comes in handy to a programmer's brain. I was totally surprised by the preview result. Won't be an issue for people who don't already have a Sequential system in place. But there are folks on pre-v6 versions who would be using some kind of mod and the few who are using Chuggyskin's. THEY will be surprised. I'm getting off for the night. :)

**Comment by Dirty-Butter** [comment] 2018-02-21 02:31
OK - I thought I was getting off. So I went to try a negative number. It lets me preview that BUT I can't get rid of the 4027 I had already saved - so I can Preview and see the result I want. But if I goof - which I initially did - I can't fix it. I should be able to go into the database and get rid of the 4027, but that's definitely something to work on tomorrow. I looked back through comments from you and Al, and I should have realized what was going to happen - but I was expecting it to just pick up the next number in the sequence and didn't notice it had skipped those 3.  G'nite for me.

**Comment by abrookbanks** [comment] 2018-02-21 09:00
I'll have a look to see if we can add macros to the prefix and suffix. It might be we can easily automate year/month/day/hour/min/sec. No promises though. 

I can't bare to think of Rosemary working as the NYE clock chimes and I'm unlikely to be in a fit state to help out. Ha. 

> So, I CAN change the prefix or suffix each year without any issue - just don't force old orders to change, right?

Yes that's right. 

> are negs allowed? 

Nope but I can't see any reason why they shouldn't be... I'll test it.

**Comment by PloughGuy** [comment] 2018-02-21 10:21
Golly, macros! This is becoming deluxier every day...  I really wish I had a use for all this yummy goodness.  However everything I need is there, so yay team!

**Comment by abrookbanks** [comment] 2018-02-21 10:22
... not so easy ...

**Comment by abrookbanks** [comment] 2018-02-21 10:42
Date Specifiers (or macros) work well!

![screen shot 2018-02-21 at 10 40 21](https://user-images.githubusercontent.com/4520803/36475825-ddfda6d4-16f3-11e8-8c1f-d68e589643f9.png)

**Comment by Dirty-Butter** [comment] 2018-02-21 15:05
It's breaking the Preview for me. Zero seems to be what I need to put in the Increment Increase box to get the next consecutive order number to come up.

**Comment by abrookbanks** [comment] 2018-02-21 15:06
Can you tell me the values that don't work? Appreciate your help. :)

**Comment by Dirty-Butter** [comment] 2018-02-21 15:30
I tried with and without using the %Y. I saved each one, cleared Cache, and tried again. Neither one worked - just having the date mechanism available on the page seemed to be enough to mess it up.
I tested before upgrading to the new code, since I had to edit the php config file to get rid of my original 4027. Yesterday's code works for me with zero Incremental Increase and preview works. Change the three files and Preview does not work.

**Comment by abrookbanks** [comment] 2018-02-21 15:39
It works well for me. Not sure what to say without knowing the value of each field.

**Comment by Dirty-Butter** [comment] 2018-02-21 15:44
OK - this is a pure test site. I'll try a new upgrade and see if that fixes it.

**Comment by Dirty-Butter** [comment] 2018-02-21 18:30
Well I ended up wiping the whole site and installing again. I still can't get Preview to show anything - just blank info in it. So I made an Admin for you - will message the login info.

**Comment by abrookbanks** [comment] 2018-02-21 18:47
Ok thanks.

**Comment by abrookbanks** [comment] 2018-02-22 16:30
I'm actually really happy with this now. Closing for real work beta testing.... (before June).

Rosemary I'll check your store and apply any code changes to this branch if we need then. 

Thanks Guys!!!

**Comment by PloughGuy** [comment] 2018-02-22 20:15
So that implies you solves Dirty’s problem then? 

You can’t just leave a bloke hangin’...

**Comment by abrookbanks** [comment] 2018-02-22 20:17
No not at all. Please see my comment above. I'm waiting for access to check it. It will be reopened if needs be.

**Comment by Dirty-Butter** [comment] 2018-02-22 21:51
Sorry - Ian helped me setup an FTP account for you, but I can't figure out how to make it work on CuteFTP. I misunderstood and thought you were satisfied it was MY error on the install. Will message you the ftp info as best I can.

**Comment by abrookbanks** [comment] 2018-02-22 21:53
Yes please I'd like to test your store.

**Comment by abrookbanks** [comment] 2018-02-23 07:31
Reopening because I just hit me that some mysql users might not be able to create triggers. A check needs to be made that the trigger set worked and revert if not.

**Comment by PloughGuy** [comment] 2018-02-23 08:44
The alternative solution that I nicked from the interwebs earlier then benchmarked-and-tested  (using a table and an atomic SQL statement) might help out here...

**Comment by PloughGuy** [comment] 2018-02-23 08:44
The table can be created as part of the upgrade to 6.2.

**Comment by abrookbanks** [comment] 2018-02-23 08:57
Sounds a bit over complicated when we can use a simple trigger. If the MySQL user doesn't have permission to read/write triggers then they can be granted in cPanel or by the hosting company.

**Comment by PloughGuy** [comment] 2018-02-23 10:28
Don’t forget about the tail.  A ytable with a visible SQL statement will possibly cause you - as in Al, proud father, occasional removalist  and dedicated support engineer - less long term heartache than a trigger that operates out of sight and  requires hosting partners to change their policies.  (I can’t even get mine to activate storable SQL in phpMyAdmin.)  

The trigger is a very neat solution, but ...  Think about the long term.  Is it going to generate blow-back?  The table-and-atomic-statement solution is readily understood and has no dark corners.  Is it possible that a cPanel update might delete the trigger? Is it possible that a user might delete the trigger?  Then there is that whole weird initialisation calculus that you will have to document in a comprehensible way and then explain again and again and again.  Yech!

A table with an easy-to-explain starting value and a simple test that asks “is there a bigger value than this?” to prevent dups might give you a quieter, easier life.  Al, I raise this just because I care.  Dirty Rosemary cares.  We all care.  You are like a god to us - we need you to be happy.

And I can’t help feeling that dark-side coding for a system that is often run by gifted amateurs on environments that change in unpredictable ways at the whim of the inexplicably self-confident high school drop-outs that hosting providers invariably  employ is not going to deliver a happy Al in the long term.

Over...

PS: my store has been working moderately perfectly since 2009.  Today, I get a 403 error when I try to update stock numbers.  Yesterday, it worked.  Some teenage mutant admin has been mucking about with the permissions again.  And the “m” was a typo.  This same problem, or similar, seems to happen every couple of years.  It is the only problem I ever see.

PPS:  My hosting folk just came back with a response 8 minutes after I reported the problem, at 8:00pm.  “Looks like ModSecurity may be in play and interpreting it as a malicious change/attack. I've whitelisted this now.”  Can’t fault the responsiveness - this fixed the problem.  But I can fault the fault.  Someone changed a rule somewhere, then I can’t update prices.

**Comment by PloughGuy** [comment] 2018-02-23 10:42
Question for Al:  if the trigger disappears, does the order creation method detect it and fix it?  If not, will the store start dropping (probably all) transactions because of duplicate keys?

**Comment by abrookbanks** [comment] 2018-02-23 10:46
I literally can't see any reason at all why it would disappear. I suppose if you move hosting and you imported the database and the user didn't have permissions to create the trigger it would get lost. Thats not really a concern for CubeCart though.

Are you saying your hosting company doesn't allow you to use triggers?

**Comment by PloughGuy** [comment] 2018-02-23 10:51
I expect they allow me to use triggers. I can do a science experiment to find out.  Just saying that code in files and data in tables are relatively well understood by the general public, but triggers, not so much.  I am merely exploring hardening options.

**Comment by abrookbanks** [comment] 2018-02-23 10:54
I would have thought triggers would be the cleanest way and the merchant/developer shouldn't need to know anything about them as CubeCart handles it all for them. I do need to make it fool proof though and make sure the trigger was created successfully.

**Comment by PloughGuy** [comment] 2018-02-23 10:55
Foolproof is the word.  Evolution is making better fools every day...

**Comment by PloughGuy** [comment] 2018-02-23 11:02
If the Lord does choose to taketh away the trigger, do we get a duo key error?   I presume it will create one order with the default orderId then the second one will fail.  Is that correct?

If the field is NOT NULL and the trigger vanishes, what happens?  Can we detect this error and check that the trigger is OK then try again?  This would be self-healing without a cost to each order other than the success check, which I hope already happens.

So something like “If the insert fails, recreate the trigger and try one more time.”

**Comment by abrookbanks** [comment] 2018-02-23 11:08
I'll test it out and see. However once a trigger is made it should just stay. I can't see any reason for the lord to taketh it away.

**Comment by Dirty-Butter** [comment] 2018-02-23 12:58
The Stability and performance improvement fixed my problem. THANKS Al!! And I was correct that using zero as the Increment Increase continues my existing sequence on the test site. It is definitely going to be an issue if the admin saves the page after preview and then realizes they want to save it again with a different value. I DO still know how to decode base64 config, wipe out a value, and then encode with what I want. Many would not. You do have that super powerful and potentially catastrophic section in maintenance that you're trusting everyday admins to respect - maybe you should consider giving admins a chance for a redo on the Increment Increase?

**Comment by abrookbanks** [comment] 2018-02-23 14:37
Ok. Happy and closing again.

**Closed by abrookbanks** 2018-02-23 14:37 UTC
Labels: feature request

**Comment by PloughGuy** [comment] 2018-02-23 23:13
Al said:  _I'll test it out and see. However once a trigger is made it should just stay. I can't see any reason for the lord to taketh it away._

He moves in mysterious ways, especially when it comes to computerised solutions, which he seems to find personally offensive. "I created the universe, life, DNA and evolution in seven days.  It has worked a treat for over four thousand years.  You guys have been working on IT for 70 years and look - I poke here and over it goes...  Ha!  Created in His own image indeed!  Who came up with that one?"

If there is a way for it to go wrong, it will.  David Mitchell as Shakespeare should have said: "A groat's-worth of hardening doth buy a guinea-worth of leisure."  But he didn't.  Still a good quote though.

**Comment by abrookbanks** [comment] 2018-02-24 07:09
Thinking about this.. it should carry on working as it's still reliant on the traditional order I'd format. Then once the trigger is put back any empty fields will be populated. In the mean time some blank order numbers will be seen. Not a disaster. Any number of things can go wrong with CubeCart. Bridge will need to be crossed when it does.

**Comment by PloughGuy** [comment] 2018-02-24 22:27
Our thoughts and prayers are with it...

Good call. At the first sign of trouble, though, we have a potential solution in the recipe book.
Get back to the packing...
R
