### ISSUE TITLE
Superfluous images appear in products

### ISSUE THREAD

**Issue by chilled35** [cubecart/v6#241] opened 2015-02-19 11:09 UTC
1. Create new product, assigning price/description, leaving product images empty.
2. View product on live site, images from other products show.

**Comment by Diablo0** [comment] 2015-02-19 14:32
I'm seeing the same issue.   No image is checked for many products however when viewing the product on the live site, all other images that are on other products are showing on the product that doesn't have any images selected.

**Comment by abrookbanks** [comment] 2015-02-19 14:49
Duplicate of #213 fix can be found there.

**Closed by abrookbanks** 2015-02-19 14:49 UTC
Labels: duplicate

**Comment by chilled35** [comment] 2015-03-03 01:29
Can't see how implementing the code fix in 213 helps with this matter?  I replaced the code as per suggestions in 213 and the site still shows every image in the file manager, irrespective of what's actually selected in the product listing...

**Comment by abrookbanks** [comment] 2015-03-03 07:29
Please make sure you are on the latest code build with cleared cache and it will be fine.

**Comment by chilled35** [comment] 2015-03-03 11:31
Will do... :)

**Comment by chilled35** [comment] 2015-03-03 12:39
Sadly updating to 6.0.0b6 doesn't fix this problem - here's an example of a single guitar page with all the other product photos too, having cleared the cache too:  http://thebarrymusicshop.com/vintage-av3.html

**Comment by abrookbanks** [comment] 2015-03-03 12:46
If you were on beta 6 the admin login to your store would look like this.. 

![screen shot 2015-03-03 at 12 44 46](https://cloud.githubusercontent.com/assets/4520803/6462685/180b904c-c1a3-11e4-80c3-f290e98b8853.png)

.. and not like this:

![screen shot 2015-03-03 at 12 44 37](https://cloud.githubusercontent.com/assets/4520803/6462705/420f7444-c1a3-11e4-8534-93e4c7d9efdf.png)

**Comment by chilled35** [comment] 2015-03-03 12:54
I uploaded 6.0.0b6 overwriting whatever was on the server, ran setup, 'upgraded' and that was that :/

**Comment by chilled35** [comment] 2015-03-03 12:56
Ah... I've just realised my schoolboy error.... I didn't check the path on the server before uploading.  The alternative 5.2.16 has been overwritten!

**Comment by abrookbanks** [comment] 2015-03-03 13:00
Whoops.

**Comment by chilled35** [comment] 2015-03-03 13:02
<HangsHeadInShame>
Mmm...the ftp upload is painfully slow on this server so I have a few anxious minutes left to see the site working as normal :)
</HangsHeadInShame>

**Comment by chilled35** [comment] 2015-03-03 13:22
Bingo! No more extra images...
