### ISSUE TITLE
6.0.12: content.checkout.confirm.php relies too heavily on JS

### ISSUE THREAD

**Issue by cb2004** [cubecart/v6#1155] opened 2016-06-23 12:17 UTC
Turn off JS and remove the required attribute from fields and the confirm routine, in my eyes needs a lot of work. The biggest problem is there is zero server side validation. But also forms are disabled by the hide class, where these should be hidden with JS. Also the required attribute can confuse things (this is what is handled well with JS).

Happy to help make this step a little bit better. I understand some of this can be made better within the template, but server side validation will need to be implemented.

To start off, the login form should be hidden with CSS. The link within 'Already registered? Log In' should link to the login page if JS is switched off and display the login form if not. Delivery address should be hidden with JS.

**Comment by cb2004** [comment] 2016-06-24 12:35
A good example of server side error checking is if you remove the required attributes from the password fields, and leave the 'I would like to create an account' checked. This allows you through, I am presuming with a blank password. Not good.

**Comment by abrookbanks** [comment] 2016-08-02 10:49
Thanks for this. Yes CubeCart is very dependant on JS. Rewrite time!

**Comment by abrookbanks** [comment] 2016-08-02 10:49
Closed by mistake and reopened.

**Comment by cb2004** [comment] 2016-08-02 10:53
@abrookbanks I don't think there will need to be much of a rewrite. There will need to be error checking added to the core code, then the JS can do what its doing now with the server side error checking as fallback. Happy to help and test if you need me.

**Comment by abrookbanks** [comment] 2016-08-02 10:53
I see. Yes thats not so bad then. Thanks!

**Comment by Noodleyman** [comment] 2016-10-16 09:08
I just stumbled across this ticket whilst looking for something else and it caught my eye. The comments in this ticket go directly against https://github.com/cubecart/v6/issues/979#issuecomment-251665570 where I requested more server side validation.

So, will, or won't this be addressed?

**Comment by abrookbanks** [comment] 2016-10-16 13:41
I would say that so long as there is no security implication it's fine to rely on JavaScript.

**Closed by abrookbanks** 2016-10-16 13:41 UTC

**Comment by cb2004** [comment] 2016-10-16 15:18
I kind of see where you are coming from with the security comment, but the fact is CubeCart does not work properly with JS disabled. This is kind of acceptable for display elements as you can make them degrade gracefully, but the backend should not rely on JS to do checking for everything to work as intended, that's insane. Server side validation should be primary, JS should be secondary.

**Comment by abrookbanks** [comment] 2016-10-16 19:09
Yeah. I'm in the fence here. CubeCart's typical merchant is low to mid end and I'm not sure stats in JS these days.

**Comment by cb2004** [comment] 2016-10-16 20:16
Previous versions of Cubecart had great server side validation so I am not sure why it was not carried over from V4. Validation should always be performed server-side - you can never fully trust client-side validation. Especially with the use of a plugin that may never be updated or stop working in future browsers. The fact that somebody can sign up as a member with a blank password is proof that client side validation should not be relied upon. Even low end merchants would not want that. I think pigeon-holing CubeCart to any market doesn't relate here as this is not a high end feature. Client-side validation is just an added UX bonus so the user doesn't have to submit and reload a page simply because a value in a form isn't valid.

**Comment by abrookbanks** [comment] 2016-10-17 06:05
From a developer best practise point of view I totally agree. There is server side validation on things like the address and email etc.

I've not seen any reported problems since the release of v5 around this issue.

**Comment by Noodleyman** [comment] 2016-10-17 07:15
Reported issue:
https://github.com/cubecart/v6/issues/979

Although the root cause is older/unsupported browsers, but with server side validation that wouldn't matter as only the visuals may not function correctly.

I've also found out last week that there are issues with JS and address vallidation on older IOS devices (iPads) which is breaking addresses, and thus causing invalid shipping rates/prices due to the way the All in one module module is configured.

simple server side validation would catch these type if issues and prevent the introduction of invalid data conditions which can have knock on effects to both standard, and third part modules.

in my opinion, in order to make the "core" CubeCart engine as robust as possible  server side validation is a must have because client side validation can't be trusted and we can't assume that every customer will use a device of browser from the supported list.

It's not a difficult task to add server side validation, it could even be written as a plugin or new configuration tab within the store settings, giving people the ability to toggle on/off those things they want to validate.
