### ISSUE TITLE
{BUG} - CC606 - Caching the Admin Area

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#678] opened 2015-07-10 10:47 UTC
I just upgraded a store from CC605 to CC606. After the update I was not able to get into the admin area, I was presented with a white screen.

The error log of the server was presenting me with the following error:
[10-Jul-2015 11:41:00 Europe/Dublin] PHP Parse error:  syntax error, unexpected T_VARIABLE in /home/myoffice/public_html/cache/skin/5262a6227821d84e3448607100b187dd3560be4a_0.file.dashboard.index.php.php on line 109

This presents several problems.
1) There should be no caching of pages in the admin area (Or so I've been told previously)

2) This was caused because the store uses a custom admin skin based off of an earlier 6x admin skin. This is to prevent updates overwriting custom changes to the admin skin. It appears as of 606 you must use the admin skin bundled with 606 otherwise you can't log into the admin area due to the above error.

The upgrade process should be improved to check if a custom admin skin is being used and warn you. It should also force the default admin skin to be "Default" when upgrading to 606 so that you can gain access to the admin area after the update. There should be no caching enabled within the admin area.

Work Around:
To work around this issue I had to duplicate the 606 Default admin skin, then rename it to the custom skin name. As the old page is already cached, the files /cache/skin directory needs to be manually deleted from the server after which you can gain access to the admin area.

**Comment by abrookbanks** [comment] 2015-08-19 09:59
Duplicate of #571 

Initial bug report with Smarty here: https://github.com/smarty-php/smarty/issues/60

No fix can be made unless we always stay on a Smarty version < 3.1.25

**Closed by abrookbanks** 2015-08-19 09:59 UTC
Labels: duplicate

**Comment by Noodleyman** [comment] 2015-08-19 10:02
Caching is only the first part of this ticket. there are also issues with custom admin skins and the upgrade process
