### ISSUE TITLE
Option Sets do not display selected values in orders

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1654] opened 2017-06-02 10:26 UTC
This has been an issue in the past, but I thought it was recently resolved. It's resurfaced in the 6.1.8 release.

Product has options allocated via an option set
![image](https://cloud.githubusercontent.com/assets/10614018/26721917/beab2952-4785-11e7-9700-2059a8104327.png)

I validated there are no records in the CubeCart_option_assign table for this product, only the association to the set via CubeCart_options_set_product exists.

After placing an order, the values selected by the customer are not visible.
![image](https://cloud.githubusercontent.com/assets/10614018/26722449/e3ab68f0-4787-11e7-9d8e-4a7dda56c69a.png)

![image](https://cloud.githubusercontent.com/assets/10614018/26722015/1b6ad71e-4786-11e7-9e76-dab0ec9b2480.png)

This makes it impossible for the store admin / picker to know what to send the customer without having to contact them.

**Comment by Noodleyman** [comment] 2017-06-02 10:32
As a temporary, crude work around so orders can be processed, I made the following changes.

**element.product_options.php**
```
<!-- Temp Workaround-->
{if isset($product.temp_option_fix)}
<pre>{$product.temp_option_fix}
</pre>
{/if}

```

**orders.index.inc.php**
AFTER: 
`foreach ($inventory as $product) {`

ADD:
```
					// Lets work around broken option sets....
					if(isset($product['options_array']) && !empty($product['options_array'])){
						$normal_array = unserialize($product['options_array']);
						$non_screwed_up = '';
						if(isset($normal_array) && is_array($normal_array) && !empty($normal_array)){
							foreach($normal_array as $key => $val){

								// What is the option group name...
								$on = $GLOBALS['db']->select('CubeCart_option_group', 'option_name', array('option_id' => $key));
								$non_screwed_up .= '<b>' . $on[0]['option_name'] . '</b>: ' . $val[0] . '<br/>';
							}
						}
						$product['temp_option_fix'] = $non_screwed_up;
					}
```

**Comment by abrookbanks** [comment] 2017-08-14 11:42
I haven't been able to reproduce this.. but I expect it's one of the following reasons;

- Maybe the stored array data is just too big for the database field. 
- Maybe the stored serialised array doesn't like some of the special characters like the registered trade mark symbol.

**Comment by abrookbanks** [comment] 2017-08-14 11:47
Maybe you can SQL dump the following CubeCart_options* tables for me?

I can then assigned these options to a product and do some tests.

**Comment by abrookbanks** [comment] 2017-09-28 10:48
Thanks for the private sql file to reproduce this. There are three options sets. Any particular one I should assign to a product?

**Comment by abrookbanks** [comment] 2017-09-28 10:48
Ah "All Options" .. duh.....

**Comment by abrookbanks** [comment] 2017-09-28 10:53
It's caused by the special characters like © and maybe the forward slash because the PHP serialise function is terrible..

**Comment by Noodleyman** [comment] 2017-09-28 11:32
Ah…

 

Nice catch!

 

So, needs the strings encoded, or stripped to their HTML number, or HTML name in the array before they are serialized. A quick loop through the array should probably solve that.

**Comment by abrookbanks** [comment] 2017-09-28 11:34
This is an all dayer or two.. still working on it.. so many numbers and relationships!!

**Comment by abrookbanks** [comment] 2017-09-28 12:30
Commit https://github.com/cubecart/v6/commit/4fed69ce6f16fb031fc855d80d9713b898c2b94a make sure all text fields show in order summary... 

![screen shot 2017-09-28 at 13 29 24](https://user-images.githubusercontent.com/4520803/30966548-308e8b5e-a451-11e7-93e8-9d329eebefe6.png)

**Comment by abrookbanks** [comment] 2017-09-28 14:38
Right back to the issue at hand..... I think we have to change to json_encode....

**Comment by abrookbanks** [comment] 2017-09-28 14:59
I think its working!
http://static.cubecart.com/github-1654.mp4

I then tried again using all kinds of special characters and it didn't flinch. 

Closing.. but welcoming feedback and will reopen if we still have problems.

**Closed by abrookbanks** 2017-09-28 14:59 UTC

**Comment by abrookbanks** [comment] 2017-09-28 15:33
.. i forgot to check my code in ..

**Comment by Noodleyman** [comment] 2017-09-30 08:19
Thanks Al

Will port this to the customer site and validate sometime next week.

**Comment by abrookbanks** [comment] 2017-09-30 08:32
Great make sure the database encoding us all UTF8. Database, table and column.

**Comment by Noodleyman** [comment] 2017-09-30 08:37
Will do :), It's something I keep an eye out for usually, although the odd upgraded v3 DB has those kind of issues.
