### ISSUE TITLE
WorldPay Plugin return.php 500 error

### ISSUE THREAD

**Issue by whitepandaltd** [cubecart/v6#1884] opened 2018-02-26 20:38 UTC
There is a php bug in the worldpay plugin that if the Deluxe bxSlider from Semperfi is turned on then the return.php path will get a 500 error when worldpay trys to contact to the store and redirect the customer after a successful payment. If the bxslider is turned off then there is no error.

**Comment by bhsmither** [comment] 2018-02-26 21:02
Can you help us by determining where PHP is crashing?

https://forums.cubecart.com/topic/51550-how-to-create-the-error-log/

**Comment by whitepandaltd** [comment] 2018-02-26 21:34
Enclosed is the php error log from the hosting server. I will follow your instructions on how to create an error log to see if thats different now.

[24-Feb-2018 10:56:18 UTC] PHP Warning:  require_once(modules/plugins/SFWS_Deluxe_bxSlider/class.deluxe_bxslider.php) [<a href='http://docs.php.net/manual/en/function.require-once.php'>function.require-once.php</a>]: failed to open stream: No such file or directory in /home/indoorxtremeco/public_html/modules/plugins/SFWS_Deluxe_bxSlider/hooks/class.gui.css.php on line 4
[24-Feb-2018 10:56:18 UTC] PHP Fatal error:  require_once() [<a href='http://docs.php.net/manual/en/function.require.php'>function.require.php</a>]: Failed opening required 'modules/plugins/SFWS_Deluxe_bxSlider/class.deluxe_bxslider.php' (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php:/home/indoorxtremeco/public_html/modules/plugins/SFWS_Deluxe_Document_Manager:/home/indoorxtremeco/public_html/modules/plugins/SFWS_Custom_Foundation_5_Skin_Configuration:/home/indoorxtremeco/public_html/modules/plugins/SFWS_Ajax_Configurable_Search_Box:/home/indoorxtremeco/public_html/modules/plugins/SFWS_Multiple_Category_Menus:/home/indoorxtremeco/public_html/modules/plugins/SFWS_Plugin_Updates_Available:/home/indoorxtremeco/public_html/modules/plugins/SFWS_Deluxe_bxSlider:/home/indoorxtremeco/public_html/modules/plugins/SFWS_Store_Health_Check:/home/indoorxtremeco/public_html/modules/plugins/Google_Merchant_Feed') in /home/indoorxtremeco/public_html/modules/plugins/SFWS_Deluxe_bxSlider/hooks/class.gui.css.php on line 4

**Comment by whitepandaltd** [comment] 2018-02-26 21:48
I recreated the 500 by going to file ....modules/gateway/WorldPay/return.php at 21.43. Unfortunately that did not show on the error report:
After turning the bxslider off that url then works with no 500 error.

[26-Feb-2018 21:37:50 UTC] PHP Warning:  Stored session data did not match DB record. Session aborted as possible session hijack. Old IP Address: '82.12.194.3' New IP Address: '82.12.194.3' Old User Agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36' New User Agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36' in /home/indoorxtremeco/public_html/classes/session.class.php on line 702
[26-Feb-2018 21:37:52 UTC] PHP Warning:  Invalid Security Token in /home/indoorxtremeco/public_html/classes/sanitize.class.php on line 152

**Comment by bhsmither** [comment] 2018-02-26 22:31
The instructions on how to create the error log certainly says that there will be an `error_log` in CubeCart's main folder. This case is different because the "initial executing script", from which all other scripts are included or functions called, is **not** `index.php` in Cubecart's main folder.

PHP **should** write the `error_log` file (unless specifically told where to write it as part of the filename argumant) in the same directory as the "initial executing script". This would be wherever `return.php` is located.

**Comment by whitepandaltd** [comment] 2018-02-26 22:43
error log from where return.php is located:

[26-Feb-2018 21:43:40 UTC] PHP Warning:  require_once(modules/plugins/SFWS_Deluxe_bxSlider/class.deluxe_bxslider.php) [<a href='http://docs.php.net/manual/en/function.require-once.php'>function.require-once.php</a>]: failed to open stream: No such file or directory in /home/indoorxtremeco/public_html/modules/plugins/SFWS_Deluxe_bxSlider/hooks/class.gui.css.php on line 4
[26-Feb-2018 21:43:40 UTC] PHP Fatal error:  require_once() [<a href='http://docs.php.net/manual/en/function.require.php'>function.require.php</a>]: Failed opening required 'modules/plugins/SFWS_Deluxe_bxSlider/class.deluxe_bxslider.php' (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php:/home/indoorxtremeco/public_html/modules/plugins/SFWS_Deluxe_Document_Manager:/home/indoorxtremeco/public_html/modules/plugins/SFWS_Custom_Foundation_5_Skin_Configuration:/home/indoorxtremeco/public_html/modules/plugins/SFWS_Ajax_Configurable_Search_Box:/home/indoorxtremeco/public_html/modules/plugins/SFWS_Multiple_Category_Menus:/home/indoorxtremeco/public_html/modules/plugins/SFWS_Plugin_Updates_Available:/home/indoorxtremeco/public_html/modules/plugins/SFWS_Deluxe_bxSlider:/home/indoorxtremeco/public_html/modules/plugins/SFWS_Store_Health_Check:/home/indoorxtremeco/public_html/modules/plugins/Google_Merchant_Feed') in /home/indoorxtremeco/public_html/modules/plugins/SFWS_Deluxe_bxSlider/hooks/class.gui.css.php on line 4

**Comment by bhsmither** [comment] 2018-02-26 23:30
I think the problem is that the code in the module's file `/hooks/class.gui.css.php`, line 4, is using a full relative path for the require_once, `modules/plugins/SFWS_Deluxe_bxSlider/class.deluxe_bxslider.php`.

Examine the contents of this file, line 4, and let us know what it is in your reply.

SFWS will need to fix this.

You can try the following:
```
require_once(__DIR__ . "../class.deluxe_bxslider.php");
```
EDIT:
```
require_once(__DIR__ . "/../class.deluxe_bxslider.php");
```

This says, "Whatever directory I am in now, go up one directory and find the file there." (I think.)

If this is the case, other files in the /hooks/ directory may have the same coding situation.

**Comment by whitepandaltd** [comment] 2018-02-27 08:19
this is the line 4 code

require_once('modules'.CC_DS.'plugins'.CC_DS.'SFWS_Deluxe_bxSlider'.CC_DS.'class.deluxe_bxslider.php');

**Comment by whitepandaltd** [comment] 2018-02-27 09:14
I have spoken with SFWS and they believe that it is a bug with the WorldPay gateway as there are no issues with any other gateway. They are looking at it but believe that this is something that will need changing with the cubecart worldpay gateway going forward.

**Comment by abrookbanks** [comment] 2018-02-27 09:17
Closing as "SFWS_Deluxe_bxSlider" has nothing to do with WorldPay.

**Closed as completed by abrookbanks** 2018-02-27 09:17 UTC

**Comment by abrookbanks** [comment] 2018-02-27 09:19
Brian is right. There is a fault with the extension as it can't cope with its include path from the remote.php file. Please take this up further with SFWS. All other payment gateways work because they don't *need* a response to fixed file without URL parameters. remote.php is a work around to keep WorldPay happy. Alternatively if you can open a support ticket we can fix it. This is not a WorldPay bug.

**Comment by bhsmither** [comment] 2018-02-27 15:18
See what happens when you make the change to the code as suggested by the above (edited) statement.

**Comment by abrookbanks** [comment] 2018-02-27 15:28
> See what happens when you make the change to the code as suggested by the above (edited) statement.

Yes I expect that will fix it. Hope it works for you @whitepandaltd (Marco) ;)
