### ISSUE TITLE
Total price changes at checkout because of VAT calculation method

### ISSUE THREAD

**Issue by jac0511** [cubecart/v6#2210] opened 2018-11-09 20:56 UTC
When the products total e.g. 303,00 € and Finnish VAT is 24 %, the total price in the checkout changes to 302,99 €. I guess this happens because in the checkout the VAT is added to rounded prices excluding VAT. The prices are defined to include VAT in the shop. Is there a way to show the VAT inclusive prices also in the checkout (only show the amount of VAT and not prices excluding VAT)?

**Comment by abrookbanks** [comment] 2018-11-14 07:30
I think sprintf function needs to be replaced with round.

**Comment by abrookbanks** [comment] 2019-02-07 17:22
This has been added to the 6.2.4 milestone because more granular logging of tax has been added to 6.2.3. This means if this issue can be reproduced in 6.2.4 we should be able to see where it went wrong and finally put a nail in this coffin.

**Comment by abrookbanks** [comment] 2019-08-14 12:05
Due to tax inclusive prices there can on some occasions be a 0.01 discrepancy. It's been revisited 101 times now and always raises its head. 

The tax system need another complete rewrite and products should always be entered excluding tax. Closing for now. Major version update required.

**Closed as completed by abrookbanks** 2019-08-14 12:05 UTC
Labels: wontfix/unsure
