### ISSUE TITLE
Bad maths in basket

### ISSUE THREAD

**Issue by Prb4000** [cubecart/v6#3434] opened 2023-11-20 13:27 UTC
Here's a new problem. This used to work fine but now it doesn't. I assume the problem has arrived with the latest update.

Attached are three screen grabs. The first one shows the product screen. Everything is correct. I have added one to the basket and the basket price is correct - top right corner of the product screen.

Screen grab number 2 shows the check out page where the price is now wrong.

This is literally costing me money!

The problem is most likely related to the "Turret only" option which has an absolute price and overrides the product price. The "Quality" option price is not added.

Interestingly the "Size" option price is added on to the "Turret only" option price correctly. See screen grab number 3.

![Bad maths1](https://github.com/cubecart/v6/assets/67736774/71ce03eb-c06e-4bb2-a210-bb4dd0d35cd7)
![Bad maths2](https://github.com/cubecart/v6/assets/67736774/ea895a2d-eaf3-4141-8f5a-c4cb74c9e833)
![Bad maths3](https://github.com/cubecart/v6/assets/67736774/5fc6566a-c597-426b-80c5-fb199ec17544)

**Comment by abrookbanks** [comment] 2023-11-20 15:40
What version did you upgrade from.

**Comment by Prb4000** [comment] 2023-11-20 15:50
Hi Al
I didn't do the upgrade, Ian at Havenswift does all that for me.He keeps it up to date so presumably whatever the previous version was.
Ian will be able to give you much better information than me

Peter 

    On Monday, 20 November 2023 at 15:40:49 GMT, Al Brookbanks ***@***.***> wrote:  
 
 


What version did you upgrade from.

**Comment by havenswift-hosting** [comment] 2023-11-20 15:52
From 6.5.1 to 6.5.3

**Comment by abrookbanks** [comment] 2023-11-20 15:53
If you go to the back end and go to the **Product Options** section. You can order the product options. 

Can you put **Turret Only** above **Quality** as a work around for now. I expect that will solve it.

**Comment by Prb4000** [comment] 2023-11-20 16:19
Yes, from a quick check that appears to have fixed it.

    On Monday, 20 November 2023 at 15:54:00 GMT, Al Brookbanks ***@***.***> wrote:  
 
 


If you go to the back end and go to the Product Options section. You can order the product options.

Can you put Turret Only above Quality as a work around for now. I expect that will solve it.

**Comment by abrookbanks** [comment] 2023-11-20 16:36
Ok.. I don't think it was designed in mind with being used alongside other priced options.

**Comment by abrookbanks** [comment] 2023-11-21 11:27
I can't reproduce this on my development store. Very odd. Closing for now but will look into it on a case by case situation in the future.

<img width="1019" alt="Screenshot 2023-11-21 at 11 26 37" src="https://github.com/cubecart/v6/assets/4520803/f96c7ab1-3f1c-4554-a105-5ae5a5205dd2">

**Closed as completed by abrookbanks** 2023-11-21 11:27 UTC
Labels: invalid
