### ISSUE TITLE
Checkout Flow Bug

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#773] opened 2015-08-29 04:04 UTC
If I press the "Log in" link on the confirm page and enter my log in details I do not get to choose the payment method and instead simply proceeds to the next page of the checkout?

**Comment by abrookbanks** [comment] 2015-09-04 13:24
This is intentional. The login routine will always override anything else. Enabling this part of the form would just be ignored. After login it should be possible to choose the payment method which from my testing works.

**Comment by bondimedical3** [comment] 2015-09-05 00:44
If you log in from the confirm page it simply selects the first payment method and asks for payment?

**Comment by bondimedical3** [comment] 2015-09-05 07:44
![screenshot_2015-09-05-17-42-57](https://cloud.githubusercontent.com/assets/10808588/9698359/ab0e89c8-53f5-11e5-95d2-f710a684f4a5.png)
To clarify I am talking about the blue "Log in" link here

**Comment by bondimedical3** [comment] 2015-09-26 04:56
Hello Al. Has this been fixed yet?

**Comment by jasehead** [comment] 2016-08-03 12:26
+1 from me - this is a reproducible bug in multiple browsers/viewports.  Basically, the payment options are available during checkout until you click the blue log in text link - then the payment options are hidden.  This is a bug and it should not be intentional behaviour.

Here are the steps to reproduce the issue:
1) If already logged in, then log out
2) Go to the home page of the store
3) Add an item to basket
4) Open basket and click Secure Checkout
5) Scroll to the bottom of the checkout page to see that Choose Payment Method and options are visible
6) Scroll back to top and where it says Profile - Already registered? Log In - click the blue Log In link
7) Scroll to the bottom of the page to see that Choose Payment Method and options are now hidden

Checkout is still possible but will only work using the default payment method because the customer no longer has a choice.  It makes no sense to hide payment options - please fix.

**Comment by bondimedical3** [comment] 2016-08-03 22:58
I have pointed this out to Al multiple times and he has not fixed it. I managed to fix it myself by making the link the same as the Login/Register link in the top right hand corner. It's a simple change in the core.

**Comment by abrookbanks** [comment] 2016-08-04 07:59
Thanks yes this still needs to be looked at. We're open source now and I was hoping for more community contributions to help with issues. They are few and far between though.

**Comment by jasehead** [comment] 2016-08-04 09:38
I've done some further testing of the checkout flow and I have to admit that I'm no longer able to get the checkout to proceed with the payment methods still hidden. I'm pretty sure that it DID happen but now I can't reproduce the circumstances (would have to play with different browsers and viewports).

However, from testing I can say offer some points.

Unregistered customer is the default basket shown complete with payment details. I expect that if ALL details are completed then the unregistered customer clicks Secure Checkout at the bottom and the payment is processed. Great.

However, if a previously registered customer arrives at the same page and scrolls down to review then they see the payment details.  They scroll back to the top to click the Log In text link and most of the page is hidden - fair enough, they don't want the address details just enough to log in.  But hang on - where did the payment options go???

The returning customer enters their email and password - no way to check if they got it right though - and then they either click the update basket button or the secure checkout button. Let's go with secure checkout.  Hang on, that looks like the same page again but their address has appeared and the payment options are back - and they have to click the Secure Checkout button AGAIN to proceed.

So it's confusing and annoying in small ways - not quite frustration though.

SUGGESTIONS:

* Add a Log In button to the log in area - that will refresh the page at the correct point in the checkout process - address details and payment options appear after login

* - OR - Change the Log In text link to /login.html#login_form - that will take the customer to the standard login which also includes "Forgotten your password?" and "Remember Me?" options as well as a Log In button.  Successful login should return the customer to the checkout with address details and payment options visible.

**Comment by jasehead** [comment] 2016-08-04 11:41
I've done some further testing of the checkout flow and I have to admit that I'm no longer able to get the checkout to proceed with the payment methods still hidden. I'm pretty sure that it DID happen but now I can't reproduce the circumstances (would have to play with different browsers and viewports).

However, from testing I can say offer some points.

Unregistered customer is the default basket shown, complete with payment details. I expect that if ALL details are completed then the unregistered customer clicks Secure Checkout at the bottom and the payment is processed. Great.

However, if a previously registered customer arrives at the same page and scrolls down to review they see the payment details. They then scroll back to the top to click the Log In text link and most of the page is hidden - fair enough, they don't want the address details just enough to log in. But hang on - where did the payment options go???

The returning customer enters their email and password - no way to check if they got it right though - and then they either click the update basket button or the secure checkout button. Let's go with secure checkout. Hang on, that looks like the same page again but their address has appeared and the payment options are back - and they have to click the Secure Checkout button AGAIN to proceed.

So it's confusing and annoying in small ways - not quite frustration though.

SUGGESTIONS (feature request):

* Add a Log In button to the log in area - that will refresh the page at the correct point in the checkout process - address details and payment options appear after login

* OR - (as per bondimedical3) Change the Log In text link to /login.html#login_form - that will take the customer to the standard login which also includes "Forgotten your password?" and "Remember Me?" options as well as a Log In button. Successful login should return the customer to the checkout with address details and payment options visible.

With either option the returning/registered customer fills in their email address and password, clicks a login button, then only clicks the secure checkout button once on the checkout page.

**Comment by jasehead** [comment] 2016-08-04 11:42
I've done some further testing of the checkout flow and I have to admit that I'm no longer able to get the checkout to proceed with the payment methods still hidden. I'm pretty sure that it DID happen but now I can't reproduce the circumstances (would have to play with different browsers and viewports).

However, from testing I can offer some points.

Unregistered customer is the default basket shown, complete with payment details. I expect that if ALL details are completed then the unregistered customer clicks Secure Checkout at the bottom and the payment is processed. Great.

However, if a previously registered customer arrives at the same page and scrolls down to review they see the payment details. They then scroll back to the top to click the Log In text link and most of the page is hidden - fair enough, they don't want the address details just enough to log in. But hang on - where did the payment options go???

The returning customer enters their email and password - no way to check if they got it right though - and then they either click the update basket button or the secure checkout button. Let's go with secure checkout. Hang on, that looks like the same page again but their address has appeared and the payment options are back - and they have to click the Secure Checkout button AGAIN to proceed.

So it's confusing and annoying in small ways - not quite frustration though.

SUGGESTIONS (feature request):

* Add a Log In button to the log in area - that will refresh the page at the correct point in the checkout process - address details and payment options appear after login

* OR - (as per bondimedical3) Change the Log In text link to /login.html#login_form - that will take the customer to the standard login which also includes "Forgotten your password?" and "Remember Me?" options as well as a Log In button. Successful login should return the customer to the checkout with address details and payment options visible.

With either option the returning/registered customer fills in their email address and password, clicks a login button, then only clicks the secure checkout button once on the checkout page.

**Comment by jasehead** [comment] 2016-08-04 11:45
I've done some further testing of the checkout flow and I have to admit that I'm no longer able to get the checkout to proceed with the payment methods still hidden. I'm pretty sure that it DID happen but now I can't reproduce the circumstances (would have to play with different browsers and viewports).

However, from testing I can offer some points.

Unregistered customer is the default basket shown, complete with payment details. I expect that if ALL details are completed then the unregistered customer clicks Secure Checkout at the bottom and the payment is processed. Great.

However, if a previously registered customer arrives at the same page and scrolls down to review they see the payment details. They then scroll back to the top to click the Log In text link and most of the page is hidden - fair enough, they don't want the address details just enough to log in. But hang on - where did the payment options go???

The returning customer enters their email and password - no way to check if they got it right though - and then they either click the update basket button or the secure checkout button. Let's go with secure checkout. Hang on, that looks like the same page again but their address has appeared and the payment options are back - and they have to click the Secure Checkout button AGAIN to proceed.

So it's confusing and annoying in small ways - not quite frustration though.

SUGGESTIONS (feature request):

Add a Log In button to the log in area - that will refresh the page at the correct point in the checkout process - address details and payment options appear after login

OR - (as per bondimedical3) Change the Log In text link to /login.html#login_form - that will take the customer to the standard login which also includes "Forgotten your password?" and "Remember Me?" options as well as a Log In button. Successful login should return the customer to the checkout with address details and payment options visible.

With either option the returning/registered customer fills in their email address and password, clicks a login button, then only clicks the secure checkout button once on the checkout page to proceed to payment.

**Comment by jasehead** [comment] 2016-08-04 11:45
I've done some further testing of the checkout flow and I have to admit that I'm no longer able to get the checkout to proceed with the payment methods still hidden. I'm pretty sure that it DID happen but now I can't reproduce the circumstances (would have to play with different browsers and viewports).

However, from testing I can offer some points.

Unregistered customer is the default basket shown, complete with payment details. I expect that if ALL details are completed then the unregistered customer clicks Secure Checkout at the bottom and the payment is processed. Great.

However, if a previously registered customer arrives at the same page and scrolls down to review they see the payment details. They then scroll back to the top to click the Log In text link and most of the page is hidden - fair enough, they don't want the address details just enough to log in. But hang on - where did the payment options go???

The returning customer enters their email and password - no way to check if they got it right though - and then they either click the update basket button or the secure checkout button. Let's go with secure checkout. Hang on, that looks like the same page again but their address has appeared and the payment options are back - and they have to click the Secure Checkout button AGAIN to proceed.

So it's confusing and annoying in small ways - not quite frustration though.

SUGGESTIONS (feature request):

* Add a Log In button to the log in area - that will refresh the page at the correct point in the checkout process - address details and payment options appear after login

* OR - (as per bondimedical3) Change the Log In text link to /login.html#login_form - that will take the customer to the standard login which also includes "Forgotten your password?" and "Remember Me?" options as well as a Log In button. Successful login should return the customer to the checkout with address details and payment options visible.

With either option the returning/registered customer fills in their email address and password, clicks a login button, then only clicks the secure checkout button once on the checkout page to proceed to payment.

**Comment by jasehead** [comment] 2016-08-04 11:46
I've done some further testing of the checkout flow and I have to admit that I'm no longer able to get the checkout to proceed with the payment methods still hidden. I'm pretty sure that it DID happen but now I can't reproduce the circumstances (would have to play with different browsers and viewports).

However, from testing I can offer some points.

Unregistered customer is the default basket shown, complete with payment details. I expect that if ALL details are completed then the unregistered customer clicks Secure Checkout at the bottom and they proceed to payment. Great.

However, if a previously registered customer arrives at the same page and scrolls down to review they see the payment details. They then scroll back to the top to click the Log In text link and most of the page is hidden - fair enough, they don't want the address details just enough to log in. But hang on - where did the payment options go???

The returning customer enters their email and password - no way to check if they got it right though - and then they either click the update basket button or the secure checkout button. Let's go with secure checkout. Hang on, that looks like the same page again but their address has appeared and the payment options are back - and they have to click the Secure Checkout button AGAIN to proceed.

So it's confusing and annoying in small ways - not quite frustration though.

SUGGESTIONS (feature request):

* Add a Log In button to the log in area - that will refresh the page at the correct point in the checkout process - address details and payment options appear after login

* OR - (as per bondimedical3) Change the Log In text link to /login.html#login_form - that will take the customer to the standard login which also includes "Forgotten your password?" and "Remember Me?" options as well as a Log In button. Successful login should return the customer to the checkout with address details and payment options visible.

With either option the returning/registered customer fills in their email address and password, clicks a login button, then only clicks the secure checkout button once on the checkout page to proceed to payment.

**Comment by jasehead** [comment] 2016-08-04 11:58
I've done some further testing of the checkout flow and I have to admit that I'm no longer able to get the checkout to proceed with the payment methods still hidden.  As per bondimedical3 on 05 Sep 2015, logging in from checkout hid the payment options.  Proceeding with checkout resulted in the first (hidden) payment method being used.  But now I can't reproduce the problem.

However, from testing I can offer some points.

Unregistered customer is the default basket shown, complete with payment details. I expect that if ALL details are completed then the unregistered customer clicks Secure Checkout once at the bottom and they proceed to payment. Great.

However, if a previously registered customer arrives at the same page and scrolls down to review they see the payment details. They then scroll back to the top to click the Log In text link and most of the page is hidden - fair enough, they don't want the address details just enough to log in. But hang on - where did the payment options go???

The returning customer enters their email and password - no way to check if they got it right though - and then they either click the update basket button or the secure checkout button. Let's go with secure checkout. Hang on, that looks like the same page again but their address has appeared and the payment options are back - and they have to click the Secure Checkout button AGAIN to proceed.

So it's confusing and annoying in small ways - not quite frustration though.

SUGGESTIONS (feature request):

* Add a Log In button to the log in area - that will refresh the page at the correct point in the checkout process - address details and payment options appear after login

* OR - (as per bondimedical3) Change the Log In text link to /login.html#login_form - that will take the customer to the standard login which also includes "Forgotten your password?" and "Remember Me?" options as well as a Log In button.  Successful login should return the customer to the checkout with address details and payment options visible.

With either option the returning/registered customer fills in their email address and password, clicks a login button, then only clicks the secure checkout button once on the checkout page to proceed to payment.

**Comment by jasehead** [comment] 2016-12-01 23:22
After complaints from customers about no "Forgotten your password" link on the checkout login, I've bitten the bullet and changed line 91 in /skins/{your skin}/templates/content.checkout.confirm php

From:
````<p>{$LANG.account.already_registered} <a href="#" id="checkout_login">{$LANG.account.log_in}</a></p>

To:
````<p>{$LANG.account.already_registered} <a href="{$STORE_URL}/login.html#login_form">{$LANG.account.log_in}</a></p>

**Comment by jasehead** [comment] 2016-12-01 23:35
After complaints from customers about no "Forgotten your password" link on the checkout login, I've bitten the bullet and changed line 91 in /skins/{your skin}/templates/content.checkout.confirm php

From:
`<p>{$LANG.account.already_registered} <a href="#" id="checkout_login">{$LANG.account.log_in}</a></p>`

To:
`<p>{$LANG.account.already_registered} <a href="{$STORE_URL}/login.html#login_form">{$LANG.account.log_in}</a></p>`

**Comment by abrookbanks** [comment] 2017-02-06 14:51
I'm closing this because after login you can now choose payment method instead of it jumping directly to the payment screen. This was a bug fixed in a different report.

**Closed by abrookbanks** 2017-02-06 14:51 UTC
Labels: invalid / unreproducible
