### ISSUE TITLE
Contact Us RichText Editor issue

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#48] opened 2015-01-11 00:26 UTC
HTML formatting within the Content Box is not working, even when using Source Code setting - haven't tested any other documents yet.

**Comment by bhsmither** [comment] 2015-01-11 02:21
The Sanitize class no longer uses a set of exempted POST keys. Thus, the value for _every_ POST key gets sent through the `_safety()` function.

In `_safety()`, the value is run through a FILTER_SANITIZE_STRING which strips out HTML tags.

This might not be a quick fix.

**Comment by Dirty-Butter** [comment] 2015-01-11 02:27
Is that what that setting about parsing smarty is for?

On January 10, 2015, at 8:21 PM, Brian Smither <notifications@github.com> wrote:

The Sanitize class no longer uses a set of exempted POST keys. Thus, the value for every POST key gets sent through the _safety() function.

In _safety(), the value is run through a FILTER_SANITIZE_STRING which strips out HTML tags.

This might not be a quick fix.

**Comment by bhsmither** [comment] 2015-01-11 02:40
HTML tags use the open-angle and close-angle. Smarty tags use the open-brace and close-brace and will survive sanitation. The Sanitizer applies to all input 

I do not yet know what "Parse Smarty Tags" will do. I think it does **not** allow a POSTed value to escape sanitization.

**Comment by Dirty-Butter** [comment] 2015-01-11 14:06
So how can I get v6 to allow simple paragraph, font color editing, etc. in the document boxes? Or is this a bug?

**Comment by bhsmither** [comment] 2015-01-11 16:18
I see the Sanitizer stripping out all HTML tags, so how a simple text color change got saved, I don't know.

Is this a bug? I would say so since you reported here.

**Comment by Dirty-Butter** [comment] 2015-01-11 20:19
It's working correctly for me now, but not sure why. I have had trouble getting CC cache cleared. There doesn't seem to be a way within v6 to turn off cache, and FF is being stubborn, too.

**Comment by abrookbanks** [comment] 2015-01-13 11:34
I can't reproduce this but I *think* this is due to an earlier cache bug which is now fixed. The admin CP now clears the cache on each page load rather than trying to decide when bits need clearing.

**Closed by abrookbanks** 2015-01-13 11:34 UTC
Labels: invalid
