### ISSUE TITLE
Not all emails are logged 

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1653] opened 2017-06-01 18:36 UTC
Not all emails being sent from within CubeCart are being recorded in the new email logging function.

I havent yet tracked down any pattern with what customer order emails are being recorded and which ones are not being recorded - the emails are actually being sent, but sometimes the record in the email log isn't recorded

**Comment by abrookbanks** [comment] 2017-06-05 14:50
Did you find which one wasn't?

**Comment by abrookbanks** [comment] 2017-06-07 08:30
I have closed this until more info is provided. All email sent though the mailer.class.php file is logged. As far as I am aware this is all official code.

**Comment by havenswift-hosting** [comment] 2017-07-10 16:14
We have multiple examples of this across different sites and can provide access to one customer site that recently experienced this if you wish (privately obviously !).  This customer had four orders within a couple of hours, two of which the admin received the order notification and the emails were recorded within CubeCart and shown in WHM Email history and two of which were not received, not recorded in the email log and no record of them having ever been sent. 

So it appears that for some orders under some circumstances, emails to the store admin when sent at Pending stage are simply not being sent. No obvious correlation with shipping method or payment method used

**Comment by abrookbanks** [comment] 2017-07-10 16:27
> under some circumstances

Thats the key. I'll try to reproduce this.

**Comment by havenswift-hosting** [comment] 2017-07-10 16:31
LOL - I completely agree, just the type of issue we all love.  Spent a large number of hours looking at this but have now seen it on enough different sites to believe it is an issue - let me know if you would like access to the latest client site

**Comment by nutbags** [comment] 2017-07-10 16:37
My site has taken 5 orders so far today and according to my email log only 2 of the customers received an email acknowledgement when order placed, and then when I changed the status to completed. Apparently the other 3 customers had no emails other than my own direct "thank you" message. From memory it's been this way since the 6.1.7 upgrade a couple of months ago. Ian at Havenswift has been working on it.

**Comment by abrookbanks** [comment] 2017-07-25 08:49
Closed until I have steps to reproduce.

**Comment by bhsmither** [comment] 2017-07-27 04:20
Adding my observations:
Some CC code uses `$mailer->Send()` which does not log, and some code use `$mailer->sendEmail(args)` which does log after using `Send()`.

`Send()`ing emails from the Contact Us page, the Test Email in admin (inserted into the Request Log), and re-sending an email from Statistics Email Log (inserted into the Email Log).

**Comment by DiMarca-Online** [comment] 2017-07-29 12:59
Unfortunately we are also having these issues. More and more so, it seems. 

Havenswift is looking at it for us. Ian can give you the ordernumbers of the ones that don't receive any notification (and neither do we).

**Comment by abrookbanks** [comment] 2017-08-02 11:43
> Unfortunately we are also having these issues. More and more so, it seems.

It can't happen more and more as the coding doesn't change.

> Some CC code uses $mailer->Send() which does not log, and some code use $mailer->sendEmail(args) which does log after using Send().

It looks like only the contact form uses Send so that doesn't explain this.

**Comment by abrookbanks** [comment] 2017-08-02 11:44
In the advanced section of your store settings can you check the Log Retention days?

![screen shot 2017-08-02 at 12 44 31](https://user-images.githubusercontent.com/4520803/28872265-59bd4e1e-7780-11e7-934d-5020597c53d6.png)

**Comment by DiMarca-Online** [comment] 2017-08-02 12:05
"It can't happen more and more as the coding doesn't change."

I wish I could explain it, but this is really the case. I keep receiving e-mails from customers that ask whether I received the order, whether the order is already sent, etc. That didn't happen a few weeks ago.

**Comment by abrookbanks** [comment] 2017-08-02 12:37
I've spent the morning working on this with numerous test cases. The emails always send and are always logged (apart from contact us form until now).

I have to close this until someone can provide reliable steps to reproduce this.

**Closed by abrookbanks** 2017-08-02 12:37 UTC

**Comment by DiMarca-Online** [comment] 2017-08-02 12:43
I don't know if you meant the question about the log retention days for me, but they are all set to 30 days.

**Comment by bhsmither** [comment] 2017-08-02 18:04
There is this:
https://forums.cubecart.com/topic/52741-no-emails-being-sent-to-customers/

I have suggested temporary diagnostic edits to record key points in the email logging code.

**Comment by DiMarca-Online** [comment] 2017-08-10 13:53
Yesterday and today up until this moment I received 8 orders. I did not receive ANY order confirmation e-mails at all. Not 1.

**Comment by abrookbanks** [comment] 2017-08-10 14:56
I've been developing a Braintree integration. Over 70 orders placed and I can't reproduce this.

**Comment by DiMarca-Online** [comment] 2017-08-10 17:04
:-(

**Comment by bhsmither** [comment] 2017-08-10 17:16
If at all possible, and this will require that you have a different domain email address from your store's domain, reset CubeCart's Store Settings, Advanced tab, SMTP Server setting to some other server you have permission to use.

**Comment by DiMarca-Online** [comment] 2017-08-10 17:56
Ian from Havenswift is on it, but thanks for the suggestion :-D

**Comment by bhsmither** [comment] 2017-08-10 18:03
My domain's email SMTP server is also hosted by Havenswift.
https://forums.cubecart.com/topic/52785-mail-stopped-working/

**Comment by havenswift-hosting** [comment] 2018-03-01 14:55
Re-opening as now know exactly what is causing this, at least in the case of the missing order emails for the DiMarca-Online store !  (The issue referred to by @bhsmither was a cPanel bug that affected a large number of cPanel installations worldwide for a few days until it was fixed by them)

The affected customers (older historical ones) somehow had their language set to en-UK instead of en-GB !  There appears to be no way that this is possible currently so may have been a bug in a much older version of Cubecart

This causes the Order Email sending process to crash, not send any emails (to the customer or the store admin user) nor record the emails in the CubeCart Email Log

The data against all customers and order_summary records has been manually updated to fix this issue with this client but suggest

1) CubeCart should check if an email has been sent and if there is any reason why it hasnt, then record that fact and any error information in the CubeCart Error Log

2) The email itself should be recorded in the Email Log as with other sending failures so that it could be sent at a later date

**Comment by abrookbanks** [comment] 2018-03-01 14:59
I don't think en-UK is something we have ever used. Sounds like this is just a total one off.

**Comment by abrookbanks** [comment] 2018-03-01 15:04
However it shouldn't allow the user_language to be set to a value that isn't enabled so lets treat that as a bug.

**Comment by havenswift-hosting** [comment] 2018-03-01 15:05
The data must have gotten into the database somehow through Cubecart as the customer information wasnt manually added that way and I did say it was older data.  I think if it is affecting one customer then there is a strong likelihood of it affecting some more although I havent come across it before either but obscure bugs are like that.  However, that isnt really the point - the email sending process should cope with any type of error and record both the fact that the error happened and also record the Email details into the Email Log

**Comment by abrookbanks** [comment] 2018-03-01 15:31
Thanks Ian. Fix works well to make sure value retrieved against customer record is valid for the store at its current config.

**Comment by abrookbanks** [comment] 2018-03-01 15:32
.. tested with language column set to `en-UK` results in language set to `en-GB`.

**Comment by abrookbanks** [comment] 2018-03-01 15:51
Second "validity" check.. I think I need a break..
