### ISSUE TITLE
additional items added to order - not charged for

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2464] opened 2020-02-04 10:35 UTC
This has been around for a while and I've heard the occasional report from a number of people, but never been able to reproduce or explain it.. today, I made some progress in understanding this issue, although still do not have it entirely worked out. 

Sometimes, there is a report of a rogue item on a customer order which looks like it hasn't been charged for. The item can be a duplicate item of one already in the order or an entirely different item (IE, same item twice as two line items, rather than 2x quantity of the same item).  This can be noted by the subtotal not matching the line items in the order.

Whilst trying to figure it out today, In some cases, I've noticed that the cart_order_id at the SESSION level is not aligned with the order ID which was written to the CubeCart_order_summary table AFTER it's already added data to order_summary and order_inventory, aka during checkout at a payment gateway step.

In some cases, the data gets updated/inserted to the order inventory table again, but with the different cart_order_id from the session. however, the inventory data at this point is essentially orphaned. 

This is very unlikely to ever show up an issue, especially if using traditional order numbers because the change of the orphaned order ID ever getting re-used by a new order is very low.. However, IF  you are using sequential order ID,  in which case it will get re-used and will create a problem, essentially adding additional line items to a new order which show as not being charged for.

I've managed to reproduce it at least twice, but the steps to reproduce do not produce consistent results. the actual trigger of the issue is unknown. I suspect on some level it relates to ghost customers / session data / cache / session timeout values, but this is just a theory. If I figure out something definitive, I'll update it here. 

There is a weird, hard to reproduce defect lurking.

**Comment by Noodleyman** [comment] 2020-02-06 08:57
On some level, I've got some basic steps which can be used to reproduce part of the issue, but these steps are still a work in progress and do not isolate all the underlying elements.

replicated on a clean install of 6.2.8.

as a customer, add an item, checkout as guest so that the order is added to the database. (order status doesn't matter).

from admin area, delete the order.

as customer on store front, purchase the same item, checkout again with the same details, guest etc. 

the newly created order is broken. 

CubeCart_summary contains the correct data and new order ID, CubeCart_inventory contains a record with the OLD order ID.

**Comment by abrookbanks** [comment] 2020-02-11 12:14
It could be something like the order class taking an earlier set value for Order->_order_id but externally. I could even be extension specific. Proper headache. Good work thus far.  :beer:

**Comment by Noodleyman** [comment] 2020-02-11 12:30
one pattern where I've walked the access logs that stands out, is adding an item to a basket, leaving the site and returning multiple days later, adding more items and checking out.

**Comment by abrookbanks** [comment] 2020-02-11 13:04
Definitely sounds like session value mismatch right? We've both talked to Elaine about this. 
Session garbage collection time could be the issue. Maybe CubeCarts session time should match the garbage collection time.

**Comment by abrookbanks** [comment] 2020-02-20 10:34
There are some really interesting notes here:
https://stackoverflow.com/questions/24337474/ini-set-session-gc-maxlifetime-for-1-day

Essentially I believe the conclusion is that CubeCart setting the session time as 604800 seconds could just be a complete waste of time.

**Comment by abrookbanks** [comment] 2020-02-20 10:36
Using a handler like memcached would be so much better. I know this has been discussed in the past.

**Comment by Noodleyman** [comment] 2020-02-20 10:40
this particular issue fried my brain. I even walked the access logs for a couple of examples to try and figure out the reproduction steps. It appears in most cases it's when somebody added something to their basket, went away then came back "later". Having checked the various session configs I wasn't able to isolate the root cause. I can't confirm it happens every time with the steps to reproduce.

I've a feeling it may link somehow with the saved cart data getting merged with a new order, however that is just a random theory without any proof. I can't be 100% confident that cache is a factor. I think it's something session related but wasn't able to get to the bottom of it. I don't think the use of alternate cache systems would influence the behaviour. 

For now, I'm waiting for another example if it happens again and will dive into it again.

**Comment by abrookbanks** [comment] 2020-02-20 10:41
Yes well doing getting as far as you did. It's a monster.

**Comment by Noodleyman** [comment] 2020-02-20 10:43
one thing I can say with certainty.. time is a factor

**Comment by abrookbanks** [comment] 2020-02-20 10:43
From what I am gathering setting the gc_maxlifetime to match $this->_session_timeout is perfectly fine. But another script in the server with a lower gc_maxlifetime will wipe it out for all. 

The problem is other storage methods like memcached aren't available to most merchants.

**Comment by abrookbanks** [comment] 2020-02-20 11:37
I think we can relate this to #1306. I'm keen to get sessions working with memcached especially for our hosted product.

**Comment by abrookbanks** [comment] 2020-02-20 11:39
Damn it. Typo on commit. Please see: a395f16465affb7a82abc86352a206d84369756b

**Comment by abrookbanks** [comment] 2020-02-20 11:51
Works really well for me. Hopefully this resolves this issue for merchants using memcached at least.

![Untitled](https://user-images.githubusercontent.com/4520803/74931340-4e99d580-53d7-11ea-8a2c-8ba06c620c3f.png)

**Comment by abrookbanks** [comment] 2020-02-25 10:06
Closing this as I feel this is a positive step to help improve stability. We need to keep this in our minds and recommend memcached where possible.

**Closed as completed by abrookbanks** 2020-02-25 10:06 UTC
