### ISSUE TITLE
Bug: jQuery and jQueryUI Packages to be Upgraded

### ISSUE THREAD

**Issue by tonyrsutton** [cubecart/v6#2795] opened 2021-02-21 19:49 UTC
Discussion: https://forums.cubecart.com/topic/56707-tracing-the-404s/?do=findComment&comment=246558

Missing images from the ui-images images

ui-bg_glass_75_dadada_1x400.png
ui-bg_glass_55_fbf9ee_1x400.png 
ui-bg_glass_75_e6e6e6_1x400.png
ui-bg_highlight-soft_75_cccccc_1x100.png
ui-icons_222222_256x240.png
ui-bg_flat_75_ffffff_40x100.png

Related bug report - #1664

Can the missing images please be added in the next release so it stops hitting as images not found in the access_log?

Thanks,

**Comment by bhsmither** [comment] 2021-02-21 20:17
I think there is nothing wrong with the web server logging 404 on missing page resources. Or any 404. The web server does this because the web server is supposed to do this.

What needs not to happen is waking up CubeCart to deal with this request. That was solved with declarations in .htaccess many versions ago.

These image files *should have* been packaged with the matched version of the jQueryUI package being used (currently v1.11.2). So, I concur this merits a code check, but then, I don't see anything amiss in the admin screens.

**Comment by bhsmither** [comment] 2021-02-21 20:47
This could very well be caused by the fact that CubeCart is erroneously using the `min.css` file from v1.10.4, but named 1.11.2, and using the imageset from v1.11.2.

**Comment by bhsmither** [comment] 2021-02-21 20:54
Maybe change the subject to: `jQuery and jQueryUI Packages to be Upgraded`?

Also, it seems the file jquery-1.11.2.min.js has an internal note that it is actually v1.11.1.

**Comment by tonyrsutton** [comment] 2021-02-21 21:14
Subject line updated, thanks.

**Comment by abrookbanks** [comment] 2021-03-08 10:32
Closing as this seems to work really well for me. I'd be grateful if you can test it. I'll reopen if any issues are discovered.

**Comment by abrookbanks** [comment] 2021-03-08 14:35
Already a bug with checkboxes:

```
Uncaught Error: Syntax error, unrecognized expression: img.checkbox[rel=#visible]
    at Function.fa.error (jquery.min.js:2)
    at fa.tokenize (jquery.min.js:2)
    at fa.select (jquery.min.js:2)
    at Function.fa [as find] (jquery.min.js:2)
    at n.fn.init.find (jquery.min.js:2)
    at new n.fn.init (jquery.min.js:2)
    at n (jquery.min.js:2)
    at HTMLInputElement.<anonymous> (plugins.php?286d23c009a1cf44f3ef1231b14573e9:543)
    at HTMLInputElement.dispatch (jquery.min.js:3)
```

**Comment by abrookbanks** [comment] 2021-03-08 14:42
Closing again unless anything else comes up...

**Closed as completed by abrookbanks** 2021-03-08 14:42 UTC
Labels: 3rd Party
