### ISSUE TITLE
Address book bug

### ISSUE THREAD

**Issue by farl4biz** [cubecart/v6#433] opened 2015-03-30 08:27 UTC
I have a major problem on http://www.hebbestools.nl. People who signed in cannot add their address and so cannot place an order. I get the message: Saving address failed (translated from Dutch). 
There is no error about it in the error logboek in the admin. And I want to say we did not delete (drop) the database while upgrading to the latest version. I am using the latest version 6.0.2.

![schermafbeelding 2015-03-28 om 12 31 52](https://cloud.githubusercontent.com/assets/2842652/6881733/79de1d8a-d56c-11e4-8d33-d968e8f50df8.png)

**Comment by abrookbanks** [comment] 2015-03-30 09:47
Duplicate of #305 
Internal helpdesk ticket id 101849
Forums topic: https://forums.cubecart.com/topic/49493-address-cannot-be-saved/#entry207231

**Comment by abrookbanks** [comment] 2015-03-30 10:44
This is caused by a failed upgrade. No action needed.

**Closed by abrookbanks** 2015-03-30 10:44 UTC
Labels: invalid / unreproducible
