### ISSUE TITLE
newsletter.class.php:205 - Call to a member function is() on null

### ISSUE THREAD

**Issue by mjvids** [cubecart/v6#2699] opened 2020-11-29 00:34 UTC
i am getting a error newsletter.class.php:205 - Call to a member function is() on null

please help

**Comment by bhsmither** [comment] 2020-11-29 07:57
Duplicate of #2655.

In CC641, in admin, Error Log, System Error Log tab, you might see this error. If so, hovering over the error will show a trace of where this error came from.

Can you reproduce this? If so, enable debug mode, cause the error, and look at the System Error Log table.

**Closed as completed** 2020-11-29 19:06 UTC
Labels: duplicate
