### ISSUE TITLE
Textarea in content causes issues

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2225] opened 2019-01-24 14:27 UTC
create or edit a document, and add some basic, simple content in source mode

```
<div class="small-12 large-8 columns"><label class="show-for-medium-up" for="additional_information">Additional Details</label><textarea id="additional_information" name="returns[additional_information]"></textarea></div>
```
save, navigate away then edit the item you updated or created... broken.. :) save button is down the page, and content malformed meaning you can't then edit.

looks like the </textarea> causes issues.

**Comment by abrookbanks** [comment] 2019-01-25 13:15
I can't find this in the source code? Is it modified?

**Comment by Noodleyman** [comment] 2019-01-25 13:47
copy/paste into the text editor in "SOURCE" mode.... then save

IE, don't copy/paste it as content, paste it as source.

**Comment by abrookbanks** [comment] 2019-01-25 13:48
Oh I see! :P

**Comment by Noodleyman** [comment] 2019-01-25 13:56
:P

**Comment by abrookbanks** [comment] 2019-01-25 14:14
Blaming the kids. Bad night last night. I've got man flu too.

**Comment by bhsmither** [comment] 2019-01-25 20:39
Would this be more a problem with how CKEditor works? Or rather, has a still unsolved problem?
Possible duplicate of #1008

Maybe removing reliance on a `<textarea>` and using a `<div>`, or an invalid tag such as `<editorarea>`.

**Comment by bhsmither** [comment] 2019-01-26 01:33
The problem is that `<textarea>` cannot nested. And `<div>`s are all over the page. I haven't found how to declare `<editorarea>` as a valid substitute for `<textarea>`.

A work around from 2012 involves `htmlentities()` on the way from the database to the template, and the reverse back to the database.

**Comment by abrookbanks** [comment] 2019-01-29 15:15
@bhsmither is onto something. From my testing html "encoding" helps. 

For me this works. Please can you confirm.

```
<textarea name="document[doc_content]" id="doc-content" class="textbox fck">{$DOCUMENT.doc_content|escape:"html"}</textarea>
```

**Comment by abrookbanks** [comment] 2019-01-29 15:19
Can you confirm the commit above works. From my testing it works fine for all areas fo CubeCart including full HTML page editing.

**Comment by bhsmither** [comment] 2019-01-29 22:13
Is this the best solution? (I haven't tested it yet, so I don't know the side-effects.)

The question is: Is this a skin problem? Certainly it can be worked around by using a Smarty modifier in the template, but then this must be implemented for all (admin) skins.

The actual problem is the nesting of `<textarea>` tags. And this is, at it's core, a "user provided data" problem.

I would argue the solution is better handled in the PHP code. I would argue the best solution is to use a different tag - something that can be legally nested - that CKeditor would target.

But if wanting to stay with this solution, it still needs to be applied to:
* customers.email.php near line 44
* documents.email.php near lines 149 and 209
* documents.invoice.php near line 15

**Comment by abrookbanks** [comment] 2019-01-30 07:22
Yes it's working flawlessly. Can't see any side effects.

**Closed as completed** 2019-01-31 14:13 UTC
