### ISSUE TITLE
Top button bug

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#488] opened 2015-04-25 09:40 UTC
If you scroll to the bottom of a long page the top button appears. When you press this it takes you to the top. If you scroll down again then the text in the top button turns white and is barely legible?

**Comment by bondimedical3** [comment] 2015-04-27 03:31
This issue only occurs for small and medium devices

**Comment by abrookbanks** [comment] 2015-05-22 16:18
I can't reproduce this at all. What browser are you using?

**Comment by bondimedical3** [comment] 2015-05-23 01:04
I am using the Chrome browser on a mobile.

**Comment by bondimedical3** [comment] 2015-05-23 01:09
I have noticed its simply an up arrow now. But if you go to the homepage of your demo store,  scroll to the bottom, press on the up arrow, then scroll down again the up arrow turns white and is barely visible.

**Comment by abrookbanks** [comment] 2015-05-26 09:24
Great! Thanks for this one. It's fixed now.

**Closed by abrookbanks** 2015-05-26 09:24 UTC
